/** Identidades persistentes para nodos cardiovasculares sin ficha educativa. */
export const cardiovascularStableIdByOriginalName = {
  "Left coronary artery": "cardiovascular.model-node-0001",
  "Anterior interventricular artery": "cardiovascular.model-node-0002",
  "Septal branches of anterior interventricular artery": "cardiovascular.model-node-0003",
  "Circumflex artery of heart": "cardiovascular.model-node-0004",
  "Right coronary artery": "cardiovascular.model-node-0005",
  "Right inferolateral branch of right coronary artery": "cardiovascular.model-node-0006",
  "Inferior papillary muscle of left ventricle": "cardiovascular.model-node-0007",
  "Anterior papillary muscle of right ventricle": "cardiovascular.model-node-0008",
  "Inferior papillary muscle of right ventricle": "cardiovascular.model-node-0009",
  "Septal papillary muscle of right ventricle": "cardiovascular.model-node-0010",
  "Inferior leaflet of right atrioventricular valve": "cardiovascular.model-node-0011",
  "Posterior leaflet of left atrioventricular valve": "cardiovascular.model-node-0012",
  "Septal leaflet of right atrioventricular valve": "cardiovascular.model-node-0013",
  "Left coronary leaflet": "cardiovascular.model-node-0014",
  "Non-coronary leaflet": "cardiovascular.model-node-0015",
  "Right coronary leaflet": "cardiovascular.model-node-0016",
  "Anterior semilunar leaflet of pulmonary valve": "cardiovascular.model-node-0017",
  "Left semilunar leaflet of pulmonary valve": "cardiovascular.model-node-0018",
  "Right semilunar leaflet of pulmonary valve": "cardiovascular.model-node-0019",
  "Anterior basal segmental artery of left lung": "cardiovascular.model-node-0020",
  "Lateral basal segmental artery of left lung": "cardiovascular.model-node-0021",
  "Medial basal segmental artery of left lung": "cardiovascular.model-node-0022",
  "Posterior basal segmental artery of left lung": "cardiovascular.model-node-0023",
  "Superior segmental artery of left lung": "cardiovascular.model-node-0024",
  "Anterior segmental artery of left lung": "cardiovascular.model-node-0025",
  "Apical segmental artery of left lung": "cardiovascular.model-node-0026",
  "Inferior lingular artery of left lung": "cardiovascular.model-node-0027",
  "Posterior segmental artery of left lung": "cardiovascular.model-node-0028",
  "Superior lingular artery of left lung": "cardiovascular.model-node-0029",
  "Bifurcation of pulmonary trunk": "cardiovascular.model-node-0030",
  "Inferior lobar artery of right lung": "cardiovascular.model-node-0031",
  "Anterior basal segmental artery of right lung": "cardiovascular.model-node-0032",
  "Lateral basal segmental artery of right lung": "cardiovascular.model-node-0033",
  "Medial basal segmental artery of right lung": "cardiovascular.model-node-0034",
  "Posterior basal segmental artery of right lung": "cardiovascular.model-node-0035",
  "Superior segmental artery of right lung": "cardiovascular.model-node-0036",
  "Middle lobar artery of right lung": "cardiovascular.model-node-0037",
  "Lateral segmental artery of right lung": "cardiovascular.model-node-0038",
  "Medial segmental artery of right lung": "cardiovascular.model-node-0039",
  "Superior lobar artery of right lung": "cardiovascular.model-node-0040",
  "Anterior segmental artery of right lung": "cardiovascular.model-node-0041",
  "Apical segmental artery of right lung": "cardiovascular.model-node-0042",
  "Posterior segmental artery of right lung": "cardiovascular.model-node-0043",
  "Abdominal aorta": "cardiovascular.model-node-0044",
  "Common hepatic artery": "cardiovascular.model-node-0045",
  "Gastroduodenal artery": "cardiovascular.model-node-0046",
  "Proper hepatic artery": "cardiovascular.model-node-0047",
  "Left gastric artery": "cardiovascular.model-node-0048",
  "Splenic artery": "cardiovascular.model-node-0049",
  "Inferior mesenteric artery": "cardiovascular.model-node-0050",
  "Left colic artery": "cardiovascular.model-node-0051",
  "Ascending branch of left colic artery": "cardiovascular.model-node-0052",
  "Descending branch of left colic artery": "cardiovascular.model-node-0053",
  "Sigmoid arteries": "cardiovascular.model-node-0054",
  "Superior anorectal artery": "cardiovascular.model-node-0055",
  "Inferior phrenic artery": "cardiovascular.model-node-0056",
  "Left renal artery": "cardiovascular.model-node-0057",
  "Anterior branch of renal artery.l": "cardiovascular.model-node-0058",
  "Inferior suprarenal artery.l": "cardiovascular.model-node-0059",
  "Intrarenal arteries of left kidney": "cardiovascular.model-node-0060",
  "Posterior branch of renal artery.l": "cardiovascular.model-node-0061",
  "Left testicular artery": "cardiovascular.model-node-0062",
  "Lumbar arteries.l": "cardiovascular.model-node-0063",
  "Lumbar arteries.r": "cardiovascular.model-node-0064",
  "Right renal artery": "cardiovascular.model-node-0065",
  "Anterior branch of renal artery.r": "cardiovascular.model-node-0066",
  "Inferior suprarenal artery.r": "cardiovascular.model-node-0067",
  "Intrarenal arteries of right kidney": "cardiovascular.model-node-0068",
  "Posterior branch of renal artery.r": "cardiovascular.model-node-0069",
  "Right testicular artery.r": "cardiovascular.model-node-0070",
  "Superior mesenteric artery": "cardiovascular.model-node-0071",
  "Ileocolic artery": "cardiovascular.model-node-0072",
  "Appendicular artery": "cardiovascular.model-node-0073",
  "Colic branch of ileocolic artery": "cardiovascular.model-node-0074",
  "Ileal branch of ileocolic artery": "cardiovascular.model-node-0075",
  "Inferior pancreaticoduodenal artery": "cardiovascular.model-node-0076",
  "Anterior inferior pancreaticoduodenal artery": "cardiovascular.model-node-0077",
  "Marginal artery": "cardiovascular.model-node-0078",
  "Middle colic artery": "cardiovascular.model-node-0079",
  "Right colic artery": "cardiovascular.model-node-0080",
  "Common iliac artery.l": "cardiovascular.model-node-0081",
  "External iliac artery.l": "cardiovascular.model-node-0082",
  "Inferior epigastric artery.l": "cardiovascular.model-node-0083",
  "Internal iliac artery.l": "cardiovascular.model-node-0084",
  "Anterior division of internal iliac artery.l": "cardiovascular.model-node-0085",
  "Inferior gluteal artery.l": "cardiovascular.model-node-0086",
  "Internal pudendal artery.l": "cardiovascular.model-node-0087",
  "Deep artery of penis.l": "cardiovascular.model-node-0088",
  "Dorsal artery of penis.l": "cardiovascular.model-node-0089",
  "Posterior division of internal iliac artery.l": "cardiovascular.model-node-0090",
  "Iliolumbar artery.l": "cardiovascular.model-node-0091",
  "Iliacus branch of iliolumbar artery.l": "cardiovascular.model-node-0092",
  "Lumbar branch of iliolumbar artery.l": "cardiovascular.model-node-0093",
  "Spinal branch of iliolumbar artery.l": "cardiovascular.model-node-0094",
  "Superior gluteal artery.l": "cardiovascular.model-node-0095",
  "Common iliac artery.r": "cardiovascular.model-node-0096",
  "External iliac artery.r": "cardiovascular.model-node-0097",
  "Inferior epigastric artery.r": "cardiovascular.model-node-0098",
  "Internal iliac artery.r": "cardiovascular.model-node-0099",
  "Anterior division of internal iliac artery.r": "cardiovascular.model-node-0100",
  "Inferior gluteal artery.r": "cardiovascular.model-node-0101",
  "Internal pudendal artery.r": "cardiovascular.model-node-0102",
  "Deep artery of penis.r": "cardiovascular.model-node-0103",
  "Dorsal artery of penis.r": "cardiovascular.model-node-0104",
  "Obturator artery.l": "cardiovascular.model-node-0105",
  "Obturator artery.r": "cardiovascular.model-node-0106",
  "Posterior division of internal iliac artery.r": "cardiovascular.model-node-0107",
  "Iliolumbar artery.r": "cardiovascular.model-node-0108",
  "Iliacus branch of iliolumbar artery.r": "cardiovascular.model-node-0109",
  "Lumbar branch of iliolumbar artery.r": "cardiovascular.model-node-0110",
  "Spinal branch of iliolumbar artery.r": "cardiovascular.model-node-0111",
  "Superior gluteal artery.r": "cardiovascular.model-node-0112",
  "Median sacral artery": "cardiovascular.model-node-0113",
  "Posterior intercostal arteries.l": "cardiovascular.model-node-0114",
  "Posterior intercostal arteries.r": "cardiovascular.model-node-0115",
  "Subcostal artery.l": "cardiovascular.model-node-0116",
  "Subcostal artery.r": "cardiovascular.model-node-0117",
  "Superior phrenic arteries": "cardiovascular.model-node-0118",
  "Anterior spinal artery.l": "cardiovascular.model-node-0119",
  "Anterior spinal artery.r": "cardiovascular.model-node-0120",
  "Anterior communicating artery": "cardiovascular.model-node-0121",
  "Posterior communicating artery.l": "cardiovascular.model-node-0122",
  "Posterior communicating artery.r": "cardiovascular.model-node-0123",
  "Femoral artery.l": "cardiovascular.model-node-0124",
  "Deep external pudendal artery.l": "cardiovascular.model-node-0125",
  "Deep femoral artery.l": "cardiovascular.model-node-0126",
  "Lateral circumflex femoral artery.l": "cardiovascular.model-node-0127",
  "Descending branch of lateral circumflex femoral artery.l": "cardiovascular.model-node-0128",
  "Medial circumflex femoral artery.l": "cardiovascular.model-node-0129",
  "Perforating femoral arteries.l": "cardiovascular.model-node-0130",
  "Popliteal artery.l": "cardiovascular.model-node-0131",
  "Anterior tibial artery.l": "cardiovascular.model-node-0132",
  "Dorsalis pedis artery.l": "cardiovascular.model-node-0133",
  "Arcuate artery.l": "cardiovascular.model-node-0134",
  "Dorsal metatarsal arteries.l": "cardiovascular.model-node-0135",
  "Dorsal digital arteries of foot.l": "cardiovascular.model-node-0136",
  "Deep plantar artery.l": "cardiovascular.model-node-0137",
  "Lateral tarsal artery.l": "cardiovascular.model-node-0138",
  "Inferior lateral genicular artery.l": "cardiovascular.model-node-0139",
  "Inferior medial genicular artery.l": "cardiovascular.model-node-0140",
  "Middle genicular artery.l": "cardiovascular.model-node-0141",
  "Patellar anastomosis.l": "cardiovascular.model-node-0142",
  "Posterior tibial artery.l": "cardiovascular.model-node-0143",
  "Calcaneal branches of posterior tibial artery.l": "cardiovascular.model-node-0144",
  "Fibular artery.l": "cardiovascular.model-node-0145",
  "Calcaneal branches of fibular artery.l": "cardiovascular.model-node-0146",
  "Lateral plantar artery.l": "cardiovascular.model-node-0147",
  "Plantar arch.l": "cardiovascular.model-node-0148",
  "Plantar metatarsal arteries.l": "cardiovascular.model-node-0149",
  "Common plantar digital arteries.l": "cardiovascular.model-node-0150",
  "Proper plantar digital arteries.l": "cardiovascular.model-node-0151",
  "Perforating branches of plantar metatarsal arteries.l": "cardiovascular.model-node-0152",
  "Medial plantar artery.l": "cardiovascular.model-node-0153",
  "Superficial branch of medial plantar artery.l": "cardiovascular.model-node-0154",
  "Superior lateral genicular artery.l": "cardiovascular.model-node-0155",
  "Superior medial genicular artery.l": "cardiovascular.model-node-0156",
  "Superficial epigastric artery.l": "cardiovascular.model-node-0157",
  "Superficial external pudendal artery.l": "cardiovascular.model-node-0158",
  "Femoral artery.r": "cardiovascular.model-node-0159",
  "Deep external pudendal artery.r": "cardiovascular.model-node-0160",
  "Deep femoral artery.r": "cardiovascular.model-node-0161",
  "Lateral circumflex femoral artery.r": "cardiovascular.model-node-0162",
  "Descending branch of lateral circumflex femoral artery": "cardiovascular.model-node-0163",
  "Medial circumflex femoral artery.r": "cardiovascular.model-node-0164",
  "Perforating femoral arteries.r": "cardiovascular.model-node-0165",
  "Popliteal artery.r": "cardiovascular.model-node-0166",
  "Anterior tibial artery.r": "cardiovascular.model-node-0167",
  "Dorsalis pedis artery.r": "cardiovascular.model-node-0168",
  "Arcuate artery.r": "cardiovascular.model-node-0169",
  "Dorsal metatarsal arteries.r": "cardiovascular.model-node-0170",
  "Dorsal digital arteries of foot.r": "cardiovascular.model-node-0171",
  "Deep plantar artery.r": "cardiovascular.model-node-0172",
  "Lateral tarsal artery.r": "cardiovascular.model-node-0173",
  "Inferior lateral genicular artery.r": "cardiovascular.model-node-0174",
  "Inferior medial genicular artery.r": "cardiovascular.model-node-0175",
  "Middle genicular artery.r": "cardiovascular.model-node-0176",
  "Patellar anastomosis.r": "cardiovascular.model-node-0177",
  "Posterior tibial artery.r": "cardiovascular.model-node-0178",
  "Calcaneal branches of posterior tibial artery.r": "cardiovascular.model-node-0179",
  "Fibular artery.r": "cardiovascular.model-node-0180",
  "Calcaneal branches of fibular artery.r": "cardiovascular.model-node-0181",
  "Lateral plantar artery.r": "cardiovascular.model-node-0182",
  "Plantar arch.r": "cardiovascular.model-node-0183",
  "Plantar metatarsal arteries.r": "cardiovascular.model-node-0184",
  "Common plantar digital arteries.r": "cardiovascular.model-node-0185",
  "Proper plantar digital arteries.r": "cardiovascular.model-node-0186",
  "Perforating branches of plantar metatarsal arteries.r": "cardiovascular.model-node-0187",
  "Medial plantar artery.r": "cardiovascular.model-node-0188",
  "Superficial branch of medial plantar artery.r": "cardiovascular.model-node-0189",
  "Superior lateral genicular artery.r": "cardiovascular.model-node-0190",
  "Superior medial genicular artery.r": "cardiovascular.model-node-0191",
  "Superficial epigastric artery.r": "cardiovascular.model-node-0192",
  "Superficial external pudendal artery.r": "cardiovascular.model-node-0193",
  "Left common carotid artery": "cardiovascular.model-node-0194",
  "External carotid artery.l": "cardiovascular.model-node-0195",
  "Ascending pharyngeal artery.l": "cardiovascular.model-node-0196",
  "Facial artery.l": "cardiovascular.model-node-0197",
  "Angular artery.l": "cardiovascular.model-node-0198",
  "Inferior labial artery.l": "cardiovascular.model-node-0199",
  "Submental artery.l": "cardiovascular.model-node-0200",
  "Superior labial artery.l": "cardiovascular.model-node-0201",
  "Maxillary artery.l": "cardiovascular.model-node-0202",
  "Anterior deep temporal artery.l": "cardiovascular.model-node-0203",
  "Artery of pterygoid canal.l": "cardiovascular.model-node-0204",
  "Buccal artery.l": "cardiovascular.model-node-0205",
  "Descending palatine artery.l": "cardiovascular.model-node-0206",
  "Greater palatine artery.l": "cardiovascular.model-node-0207",
  "Inferior alveolar artery.l": "cardiovascular.model-node-0208",
  "Mental branch of inferior alveolar artery.l": "cardiovascular.model-node-0209",
  "Mylohyoid branch of inferior alveolar artery.l": "cardiovascular.model-node-0210",
  "Infra-orbital artery.l": "cardiovascular.model-node-0211",
  "Middle meningeal artery.l": "cardiovascular.model-node-0212",
  "Accessory branch of middle meningeal artery.l": "cardiovascular.model-node-0213",
  "Posterior deep temporal artery.l": "cardiovascular.model-node-0214",
  "Posterior lateral nasal branches of sphenopalatine artery..l": "cardiovascular.model-node-0215",
  "Posterior septal branches of sphenopalatine artery.l": "cardiovascular.model-node-0216",
  "Posterior superior alveolar artery.l": "cardiovascular.model-node-0217",
  "Occipital artery.l": "cardiovascular.model-node-0218",
  "Superficial temporal artery.l": "cardiovascular.model-node-0219",
  "Frontal branch of superficial temporal artery.l": "cardiovascular.model-node-0220",
  "Transverse facial artery.l": "cardiovascular.model-node-0221",
  "Internal carotid artery.l": "cardiovascular.model-node-0222",
  "Middle cerebral artery (M1-segment).l": "cardiovascular.model-node-0223",
  "Distal lateral striate branches.l": "cardiovascular.model-node-0224",
  "Insular branches of middle cerebral artery (M2-segment).l": "cardiovascular.model-node-0225",
  "Anterior temporal branch.l": "cardiovascular.model-node-0226",
  "Artery of precentral sulcus.l": "cardiovascular.model-node-0227",
  "Middle cerebral artery (M3 segment).l": "cardiovascular.model-node-0228",
  "Artery of central sulcus.l": "cardiovascular.model-node-0229",
  "Parietal branches of middle cerebral artery.l": "cardiovascular.model-node-0230",
  "Postcentral arterial branch.l": "cardiovascular.model-node-0231",
  "Posterior parietal artery.l": "cardiovascular.model-node-0232",
  "Posterior temporal branch.l": "cardiovascular.model-node-0233",
  "Temporal branches of middle cerebral artery.l": "cardiovascular.model-node-0234",
  "Temporo-occipital branch.l": "cardiovascular.model-node-0235",
  "Branch to angular gyrus.l": "cardiovascular.model-node-0236",
  "Prefrontal artery.l": "cardiovascular.model-node-0237",
  "Lateral frontobasal artery.l": "cardiovascular.model-node-0238",
  "Proximal lateral striate branches.l": "cardiovascular.model-node-0239",
  "Ophthalmic artery.l": "cardiovascular.model-node-0240",
  "Anterior ethmoidal artery.l": "cardiovascular.model-node-0241",
  "Anterior septal branches of anterior ethmoidal artery.l": "cardiovascular.model-node-0242",
  "Central retinal artery.l": "cardiovascular.model-node-0243",
  "Lacrimal artery.l": "cardiovascular.model-node-0244",
  "Long posterior ciliary arteries.l": "cardiovascular.model-node-0245",
  "Posterior ethmoidal artery.l": "cardiovascular.model-node-0246",
  "Septal branches of posterior ethmoidal artery.l": "cardiovascular.model-node-0247",
  "Short posterior ciliary arteries.l": "cardiovascular.model-node-0248",
  "Supra-orbital artery.l": "cardiovascular.model-node-0249",
  "Supratrochlear artery.l": "cardiovascular.model-node-0250",
  "Left subclavian artery": "cardiovascular.model-node-0251",
  "Axillary artery.l": "cardiovascular.model-node-0252",
  "Anterior circumflex humeral artery.l": "cardiovascular.model-node-0253",
  "Brachial artery.l": "cardiovascular.model-node-0254",
  "Deep brachial artery.l": "cardiovascular.model-node-0255",
  "Middle collateral artery.l": "cardiovascular.model-node-0256",
  "Radial collateral artery.l": "cardiovascular.model-node-0257",
  "Inferior ulnar collateral artery.l": "cardiovascular.model-node-0258",
  "Radial artery.l": "cardiovascular.model-node-0259",
  "Deep palmar arch.l": "cardiovascular.model-node-0260",
  "Palmar metacarpal arteries.l": "cardiovascular.model-node-0261",
  "Dorsal carpal anastomosis.l": "cardiovascular.model-node-0262",
  "Dorsal metacarpal arteries.l": "cardiovascular.model-node-0263",
  "Dorsal digital arteries of hand.l": "cardiovascular.model-node-0264",
  "Palmar carpal branch of radial artery.l": "cardiovascular.model-node-0265",
  "Superior ulnar collateral artery.l": "cardiovascular.model-node-0266",
  "Ulnar artery.l": "cardiovascular.model-node-0267",
  "(Ulnar recurrent artery).l": "cardiovascular.model-node-0268",
  "Common interosseous artery.l": "cardiovascular.model-node-0269",
  "Posterior interosseous artery.l": "cardiovascular.model-node-0270",
  "Recurrent interosseous artery.l": "cardiovascular.model-node-0271",
  "Dorsal carpal branch of ulnar artery.l": "cardiovascular.model-node-0272",
  "Superficial palmar arch.l": "cardiovascular.model-node-0273",
  "Common palmar digital arteries.l": "cardiovascular.model-node-0274",
  "Proper palmar digital arteries.l": "cardiovascular.model-node-0275",
  "Lateral thoracic artery.l": "cardiovascular.model-node-0276",
  "Posterior circumflex humeral artery.l": "cardiovascular.model-node-0277",
  "Subscapular artery.l": "cardiovascular.model-node-0278",
  "Circumflex scapular artery.l": "cardiovascular.model-node-0279",
  "Thoracodorsal artery.l": "cardiovascular.model-node-0280",
  "Thoraco-acromial artery.l": "cardiovascular.model-node-0281",
  "Pectoral branches of thoraco-acromial artery.l": "cardiovascular.model-node-0282",
  "Costocervical trunk.l": "cardiovascular.model-node-0283",
  "Deep cervical artery.l": "cardiovascular.model-node-0284",
  "Supreme intercostal artery.l": "cardiovascular.model-node-0285",
  "First posterior intercostal artery.l": "cardiovascular.model-node-0286",
  "Second posterior intercostal artery.l": "cardiovascular.model-node-0287",
  "Internal thoracic artery.l": "cardiovascular.model-node-0288",
  "Musculophrenic artery.l": "cardiovascular.model-node-0289",
  "Superior epigastric artery.l": "cardiovascular.model-node-0290",
  "Thyrocervical trunk.l": "cardiovascular.model-node-0291",
  "Inferior thyroid artery.l": "cardiovascular.model-node-0292",
  "Suprascapular artery.l": "cardiovascular.model-node-0293",
  "Transverse cervical artery.l": "cardiovascular.model-node-0294",
  "(Deep branch of transverse cervical artery).l": "cardiovascular.model-node-0295",
  "(Superficial branch of transverse cervical artery).l": "cardiovascular.model-node-0296",
  "Vertebral artery.l": "cardiovascular.model-node-0297",
  "Posterior inferior cerebellar artery.l": "cardiovascular.model-node-0298",
  "Right common carotid artery": "cardiovascular.model-node-0299",
  "External carotid artery.r": "cardiovascular.model-node-0300",
  "Ascending pharyngeal artery.r": "cardiovascular.model-node-0301",
  "Facial artery.r": "cardiovascular.model-node-0302",
  "Angular artery.r": "cardiovascular.model-node-0303",
  "Inferior labial artery.r": "cardiovascular.model-node-0304",
  "Submental artery.r": "cardiovascular.model-node-0305",
  "Superior labial artery.r": "cardiovascular.model-node-0306",
  "Maxillary artery.r": "cardiovascular.model-node-0307",
  "Anterior deep temporal artery.r": "cardiovascular.model-node-0308",
  "Artery of pterygoid canal.r": "cardiovascular.model-node-0309",
  "Buccal artery.r": "cardiovascular.model-node-0310",
  "Descending palatine artery.r": "cardiovascular.model-node-0311",
  "Greater palatine artery.r": "cardiovascular.model-node-0312",
  "Inferior alveolar artery.r": "cardiovascular.model-node-0313",
  "Mental branch of inferior alveolar artery.r": "cardiovascular.model-node-0314",
  "Mylohyoid branch of inferior alveolar artery.r": "cardiovascular.model-node-0315",
  "Infra-orbital artery.r": "cardiovascular.model-node-0316",
  "Middle meningeal artery.r": "cardiovascular.model-node-0317",
  "Accessory branch of middle meningeal artery.r": "cardiovascular.model-node-0318",
  "Posterior deep temporal artery.r": "cardiovascular.model-node-0319",
  "Posterior lateral nasal branches of sphenopalatine artery..r": "cardiovascular.model-node-0320",
  "Posterior septal branches of sphenopalatine artery.r": "cardiovascular.model-node-0321",
  "Posterior superior alveolar artery.r": "cardiovascular.model-node-0322",
  "Occipital artery.r": "cardiovascular.model-node-0323",
  "Superficial temporal artery.r": "cardiovascular.model-node-0324",
  "Frontal branch of superficial temporal artery.r": "cardiovascular.model-node-0325",
  "Transverse facial artery.r": "cardiovascular.model-node-0326",
  "Internal carotid artery.r": "cardiovascular.model-node-0327",
  "Anterior cerebral artery.l": "cardiovascular.model-node-0328",
  "Callosomarginal artery.l": "cardiovascular.model-node-0329",
  "Frontal branches of callosomarginal artery.l": "cardiovascular.model-node-0330",
  "Orbitofrontal branches of anterior cerebral artery.l": "cardiovascular.model-node-0331",
  "Pericallosal artery.l": "cardiovascular.model-node-0332",
  "Anterior cerebral artery.r": "cardiovascular.model-node-0333",
  "Callosomarginal artery.r": "cardiovascular.model-node-0334",
  "Frontal branches of callosomarginal artery.r": "cardiovascular.model-node-0335",
  "Orbitofrontal branches of anterior cerebral artery.r": "cardiovascular.model-node-0336",
  "Pericallosal artery.r": "cardiovascular.model-node-0337",
  "Middle cerebral artery (M1-segment).r": "cardiovascular.model-node-0338",
  "Distal lateral striate branches.r": "cardiovascular.model-node-0339",
  "Insular branches of middle cerebral artery (M2).r": "cardiovascular.model-node-0340",
  "Anterior temporal branch.r": "cardiovascular.model-node-0341",
  "Artery of precentral sulcus.r": "cardiovascular.model-node-0342",
  "Middle cerebral artery (M3-segment).r": "cardiovascular.model-node-0343",
  "Artery of central sulcus.r": "cardiovascular.model-node-0344",
  "Parietal branches of middle cerebral artery.r": "cardiovascular.model-node-0345",
  "Postcentral arterial branch.r": "cardiovascular.model-node-0346",
  "Posterior parietal artery.r": "cardiovascular.model-node-0347",
  "Posterior temporal branch.r": "cardiovascular.model-node-0348",
  "Temporal branches of middle cerebral artery.r": "cardiovascular.model-node-0349",
  "Temporo-occipital branch.r": "cardiovascular.model-node-0350",
  "Branch to angular gyrus.r": "cardiovascular.model-node-0351",
  "Prefrontal artery.r": "cardiovascular.model-node-0352",
  "Lateral frontobasal artery.r": "cardiovascular.model-node-0353",
  "Proximal lateral striate branches.r": "cardiovascular.model-node-0354",
  "Ophthalmic artery.r": "cardiovascular.model-node-0355",
  "Anterior ethmoidal artery.r": "cardiovascular.model-node-0356",
  "Anterior septal branches of anterior ethmoidal artery.r": "cardiovascular.model-node-0357",
  "Central retinal artery.r": "cardiovascular.model-node-0358",
  "Lacrimal artery.r": "cardiovascular.model-node-0359",
  "Long posterior ciliary arteries.r": "cardiovascular.model-node-0360",
  "Posterior ethmoidal artery.r": "cardiovascular.model-node-0361",
  "Septal branches of posterior ethmoidal artery.r": "cardiovascular.model-node-0362",
  "Short posterior ciliary arteries.r": "cardiovascular.model-node-0363",
  "Supra-orbital artery.r": "cardiovascular.model-node-0364",
  "Supratrochlear artery.r": "cardiovascular.model-node-0365",
  "Right subclavian artery": "cardiovascular.model-node-0366",
  "Axillary artery.r": "cardiovascular.model-node-0367",
  "Anterior circumflex humeral artery.r": "cardiovascular.model-node-0368",
  "Brachial artery.r": "cardiovascular.model-node-0369",
  "Deep brachial artery.r": "cardiovascular.model-node-0370",
  "Middle collateral artery.r": "cardiovascular.model-node-0371",
  "Radial collateral artery.r": "cardiovascular.model-node-0372",
  "Inferior ulnar collateral artery.r": "cardiovascular.model-node-0373",
  "Radial artery.r": "cardiovascular.model-node-0374",
  "Deep palmar arch.r": "cardiovascular.model-node-0375",
  "Palmar metacarpal arteries.r": "cardiovascular.model-node-0376",
  "Dorsal carpal anastomosis.r": "cardiovascular.model-node-0377",
  "Dorsal metacarpal arteries.r": "cardiovascular.model-node-0378",
  "Dorsal digital arteries of hand.r": "cardiovascular.model-node-0379",
  "Palmar carpal branch of radial artery.r": "cardiovascular.model-node-0380",
  "Superior ulnar collateral artery.r": "cardiovascular.model-node-0381",
  "Ulnar artery.r": "cardiovascular.model-node-0382",
  "(Ulnar recurrent artery).r": "cardiovascular.model-node-0383",
  "Common interosseous artery.r": "cardiovascular.model-node-0384",
  "Posterior interosseous artery.r": "cardiovascular.model-node-0385",
  "Recurrent interosseous artery.r": "cardiovascular.model-node-0386",
  "Dorsal carpal branch of ulnar artery.r": "cardiovascular.model-node-0387",
  "Superficial palmar arch.r": "cardiovascular.model-node-0388",
  "Common palmar digital arteries.r": "cardiovascular.model-node-0389",
  "Proper palmar digital arteries.r": "cardiovascular.model-node-0390",
  "Lateral thoracic artery.r": "cardiovascular.model-node-0391",
  "Posterior circumflex humeral artery.r": "cardiovascular.model-node-0392",
  "Subscapular artery.r": "cardiovascular.model-node-0393",
  "Circumflex scapular artery.r": "cardiovascular.model-node-0394",
  "Thoracodorsal artery.r": "cardiovascular.model-node-0395",
  "Thoraco-acromial artery.r": "cardiovascular.model-node-0396",
  "Pectoral branches of thoraco-acromial artery.r": "cardiovascular.model-node-0397",
  "Costocervical trunk.r": "cardiovascular.model-node-0398",
  "Deep cervical artery.r": "cardiovascular.model-node-0399",
  "Supreme intercostal artery.r": "cardiovascular.model-node-0400",
  "First posterior intercostal artery.r": "cardiovascular.model-node-0401",
  "Second posterior intercostal artery.r": "cardiovascular.model-node-0402",
  "Internal thoracic artery.r": "cardiovascular.model-node-0403",
  "Musculophrenic artery.r": "cardiovascular.model-node-0404",
  "Superior epigastric artery.r": "cardiovascular.model-node-0405",
  "Thyrocervical trunk.r": "cardiovascular.model-node-0406",
  "Inferior thyroid artery.r": "cardiovascular.model-node-0407",
  "Suprascapular artery.r": "cardiovascular.model-node-0408",
  "Transverse cervical artery.r": "cardiovascular.model-node-0409",
  "(Deep branch of transverse cervical artery).r": "cardiovascular.model-node-0410",
  "(Superficial branch of transverse cervical artery).r": "cardiovascular.model-node-0411",
  "Vertebral artery.r": "cardiovascular.model-node-0412",
  "Basilar artery": "cardiovascular.model-node-0413",
  "Anterior inferior cerebellar artery.l": "cardiovascular.model-node-0414",
  "Anterior inferior cerebellar artery.r": "cardiovascular.model-node-0415",
  "Lateral pontine branches of basilar artery.l": "cardiovascular.model-node-0416",
  "Lateral pontine branches of basilar artery.r": "cardiovascular.model-node-0417",
  "Medial pontine branches of basilar artery.l": "cardiovascular.model-node-0418",
  "Medial pontine branches of basilar artery.r": "cardiovascular.model-node-0419",
  "Posterior cerebral artery.l": "cardiovascular.model-node-0420",
  "Lateral occipital artery.l": "cardiovascular.model-node-0421",
  "Medial occipital artery.l": "cardiovascular.model-node-0422",
  "Parieto-occipital artery.l": "cardiovascular.model-node-0423",
  "Posterior cerebral artery.r": "cardiovascular.model-node-0424",
  "Medial occipital artery.r": "cardiovascular.model-node-0425",
  "Lateral occipital artery.r": "cardiovascular.model-node-0426",
  "Parieto-occipital artery.r": "cardiovascular.model-node-0427",
  "Superior cerebellar artery.l": "cardiovascular.model-node-0428",
  "Superior cerebellar artery.r": "cardiovascular.model-node-0429",
  "Posterior inferior cerebellar artery.r": "cardiovascular.model-node-0430",
  "Coronary sinus": "cardiovascular.model-node-0431",
  "Great cardiac vein": "cardiovascular.model-node-0432",
  "Inferior vein of left ventricle": "cardiovascular.model-node-0433",
  "Inferior vein of left ventricle (//Posterior '')": "cardiovascular.model-node-0434",
  "Middle cardiac vein": "cardiovascular.model-node-0435",
  "Inferior basal vein of left lung": "cardiovascular.model-node-0436",
  "Superior basal vein of left lung": "cardiovascular.model-node-0437",
  "Superior vein of left lung": "cardiovascular.model-node-0438",
  "Anterior vein of left lung": "cardiovascular.model-node-0439",
  "Apicoposterior vein of left lung": "cardiovascular.model-node-0440",
  "Lingular vein of left lung": "cardiovascular.model-node-0441",
  "Inferior lingular vein of left lung": "cardiovascular.model-node-0442",
  "Superior lingular vein of left lung": "cardiovascular.model-node-0443",
  "Inferior basal vein of right lung": "cardiovascular.model-node-0444",
  "Superior basal vein of right lung": "cardiovascular.model-node-0445",
  "Superior vein of right lung": "cardiovascular.model-node-0446",
  "Anterior vein of right lung": "cardiovascular.model-node-0447",
  "Apical vein of right lung": "cardiovascular.model-node-0448",
  "Lateral vein of right lung": "cardiovascular.model-node-0449",
  "Medial vein of right lung": "cardiovascular.model-node-0450",
  "Posterior vein of right lung": "cardiovascular.model-node-0451",
  "Inferior petrosal sinus.l": "cardiovascular.model-node-0452",
  "Inferior petrosal sinus.r": "cardiovascular.model-node-0453",
  "Basilar venous plexus": "cardiovascular.model-node-0454",
  "Anterior intercavernous sinus": "cardiovascular.model-node-0455",
  "Posterior intercavernous sinus": "cardiovascular.model-node-0456",
  "Cavernous sinus.l": "cardiovascular.model-node-0457",
  "Cavernous sinus.r": "cardiovascular.model-node-0458",
  "Sigmoid sinus.l": "cardiovascular.model-node-0459",
  "Transverse sinus.l": "cardiovascular.model-node-0460",
  "Superior petrosal sinus.l": "cardiovascular.model-node-0461",
  "Sigmoid sinus.r": "cardiovascular.model-node-0462",
  "Transverse sinus.r": "cardiovascular.model-node-0463",
  "Superior petrosal sinus.r": "cardiovascular.model-node-0464",
  "Inferior sagittal sinus": "cardiovascular.model-node-0465",
  "Occipital sinus": "cardiovascular.model-node-0466",
  "Straight sinus": "cardiovascular.model-node-0467",
  "Superior sagittal sinus": "cardiovascular.model-node-0468",
  "Inferior ophthalmic vein.l": "cardiovascular.model-node-0469",
  "Inferior ophthalmic vein.r": "cardiovascular.model-node-0470",
  "Superior ophthalmic vein.l": "cardiovascular.model-node-0471",
  "Superior ophthalmic vein.r": "cardiovascular.model-node-0472",
  "Femoral vein.l": "cardiovascular.model-node-0473",
  "Deep femoral vein.l": "cardiovascular.model-node-0474",
  "Perforating veins.l": "cardiovascular.model-node-0475",
  "Great saphenous vein.l": "cardiovascular.model-node-0476",
  "External pudendal veins.l": "cardiovascular.model-node-0477",
  "Superficial epigastric vein.l": "cardiovascular.model-node-0478",
  "Lateral circumflex femoral veins.l": "cardiovascular.model-node-0479",
  "Medial circumflex femoral veins.l": "cardiovascular.model-node-0480",
  "Popliteal vein.l": "cardiovascular.model-node-0481",
  "Anterior tibial veins.l": "cardiovascular.model-node-0482",
  "Genicular veins.l": "cardiovascular.model-node-0483",
  "Posterior tibial veins.l": "cardiovascular.model-node-0484",
  "Fibular veins.l": "cardiovascular.model-node-0485",
  "Lateral plantar veins.l": "cardiovascular.model-node-0486",
  "Plantar venous arch.l": "cardiovascular.model-node-0487",
  "Plantar metatarsal veins.l": "cardiovascular.model-node-0488",
  "Plantar digital veins.l": "cardiovascular.model-node-0489",
  "Medial plantar veins.l": "cardiovascular.model-node-0490",
  "Small saphenous vein.l": "cardiovascular.model-node-0491",
  "Dorsal venous arch of foot.l": "cardiovascular.model-node-0492",
  "Dorsal metatarsal veins.l": "cardiovascular.model-node-0493",
  "Dorsal digital veins of foot.l": "cardiovascular.model-node-0494",
  "Intercapitular veins of foot.l": "cardiovascular.model-node-0495",
  "Femoral vein.r": "cardiovascular.model-node-0496",
  "Deep femoral vein.r": "cardiovascular.model-node-0497",
  "Perforating veins.r": "cardiovascular.model-node-0498",
  "Great saphenous vein.r": "cardiovascular.model-node-0499",
  "External pudendal veins.r": "cardiovascular.model-node-0500",
  "Superficial dorsal veins of penis": "cardiovascular.model-node-0501",
  "Superficial epigastric vein.r": "cardiovascular.model-node-0502",
  "Lateral circumflex femoral veins.r": "cardiovascular.model-node-0503",
  "Medial circumflex femoral veins.r": "cardiovascular.model-node-0504",
  "Popliteal vein.r": "cardiovascular.model-node-0505",
  "Anterior tibial veins.r": "cardiovascular.model-node-0506",
  "Genicular veins.r": "cardiovascular.model-node-0507",
  "Posterior tibial veins.r": "cardiovascular.model-node-0508",
  "Fibular veins.r": "cardiovascular.model-node-0509",
  "Lateral plantar veins.r": "cardiovascular.model-node-0510",
  "Plantar venous arch.r": "cardiovascular.model-node-0511",
  "Plantar metatarsal veins.r": "cardiovascular.model-node-0512",
  "Plantar digital veins.r": "cardiovascular.model-node-0513",
  "Medial plantar veins.r": "cardiovascular.model-node-0514",
  "Small saphenous vein.r": "cardiovascular.model-node-0515",
  "Dorsal venous arch of foot.r": "cardiovascular.model-node-0516",
  "Dorsal metatarsal veins.r": "cardiovascular.model-node-0517",
  "Dorsal digital veins of foot.r": "cardiovascular.model-node-0518",
  "Intercapitular veins of foot.r": "cardiovascular.model-node-0519",
  "Hepatic portal vein": "cardiovascular.model-node-0520",
  "Splenic vein": "cardiovascular.model-node-0521",
  "Inferior mesenteric vein": "cardiovascular.model-node-0522",
  "Sigmoid veins": "cardiovascular.model-node-0523",
  "Left gastro-omental vein": "cardiovascular.model-node-0524",
  "Superior mesenteric vein": "cardiovascular.model-node-0525",
  "Middle colic vein": "cardiovascular.model-node-0526",
  "Right colic vein": "cardiovascular.model-node-0527",
  "Right gastro-omental vein": "cardiovascular.model-node-0528",
  "Hepatic veins": "cardiovascular.model-node-0529",
  "Inferior vena cava (abdominal part)": "cardiovascular.model-node-0530",
  "Common iliac vein.l": "cardiovascular.model-node-0531",
  "External iliac vein.l": "cardiovascular.model-node-0532",
  "Inferior epigastric vein.l": "cardiovascular.model-node-0533",
  "Iliolumbar vein.l": "cardiovascular.model-node-0534",
  "Internal iliac vein.l": "cardiovascular.model-node-0535",
  "Inferior gluteal veins.l": "cardiovascular.model-node-0536",
  "Internal pudendal vein.l": "cardiovascular.model-node-0537",
  "Lateral sacral veins.l": "cardiovascular.model-node-0538",
  "Superior gluteal veins.l": "cardiovascular.model-node-0539",
  "Common iliac vein.r": "cardiovascular.model-node-0540",
  "External iliac vein.r": "cardiovascular.model-node-0541",
  "Inferior epigastric vein.r": "cardiovascular.model-node-0542",
  "Iliolumbar vein.r": "cardiovascular.model-node-0543",
  "Internal iliac vein.r": "cardiovascular.model-node-0544",
  "Deep dorsal vein of penis": "cardiovascular.model-node-0545",
  "Inferior gluteal veins.r": "cardiovascular.model-node-0546",
  "Internal pudendal vein.r": "cardiovascular.model-node-0547",
  "Lateral sacral veins.r": "cardiovascular.model-node-0548",
  "Superior gluteal veins.r": "cardiovascular.model-node-0549",
  "Left renal vein": "cardiovascular.model-node-0550",
  "Intrarenal veins of left kidney": "cardiovascular.model-node-0551",
  "Left testicular vein": "cardiovascular.model-node-0552",
  "Lumbar veins.l": "cardiovascular.model-node-0553",
  "Lumbar veins.r": "cardiovascular.model-node-0554",
  "Right renal vein": "cardiovascular.model-node-0555",
  "Intrarenal veins of right kidney": "cardiovascular.model-node-0556",
  "Right testicular vein": "cardiovascular.model-node-0557",
  "Internal jugular vein.l": "cardiovascular.model-node-0558",
  "Common facial vein.l": "cardiovascular.model-node-0559",
  "Anterior division of retromandibular vein.l": "cardiovascular.model-node-0560",
  "Retromandibular vein.l": "cardiovascular.model-node-0561",
  "Maxillary veins.l": "cardiovascular.model-node-0562",
  "Superficial temporal veins.l": "cardiovascular.model-node-0563",
  "Facial vein.l": "cardiovascular.model-node-0564",
  "Angular vein.l": "cardiovascular.model-node-0565",
  "Inferior labial veins.l": "cardiovascular.model-node-0566",
  "Submental vein.l": "cardiovascular.model-node-0567",
  "Superior labial vein.l": "cardiovascular.model-node-0568",
  "Lingual vein.l": "cardiovascular.model-node-0569",
  "Superior thyroid vein.l": "cardiovascular.model-node-0570",
  "Internal jugular vein.r": "cardiovascular.model-node-0571",
  "Common facial vein.r": "cardiovascular.model-node-0572",
  "Anterior division of retromandibular vein.r": "cardiovascular.model-node-0573",
  "Retromandibular vein.r": "cardiovascular.model-node-0574",
  "Maxillary veins.r": "cardiovascular.model-node-0575",
  "Superficial temporal veins.r": "cardiovascular.model-node-0576",
  "Facial vein.r": "cardiovascular.model-node-0577",
  "Angular vein.r": "cardiovascular.model-node-0578",
  "Inferior labial veins.r": "cardiovascular.model-node-0579",
  "Submental vein.r": "cardiovascular.model-node-0580",
  "Superior labial vein.r": "cardiovascular.model-node-0581",
  "Lingual vein.r": "cardiovascular.model-node-0582",
  "Superior thyroid vein.r": "cardiovascular.model-node-0583",
  "Left subclavian vein": "cardiovascular.model-node-0584",
  "Axillary vein.l": "cardiovascular.model-node-0585",
  "Anterior circumflex humeral vein.l": "cardiovascular.model-node-0586",
  "Basilic vein.l": "cardiovascular.model-node-0587",
  "Median cubital vein.l": "cardiovascular.model-node-0588",
  "Median antebrachial vein.l": "cardiovascular.model-node-0589",
  "Brachial veins.l": "cardiovascular.model-node-0590",
  "Radial veins.l": "cardiovascular.model-node-0591",
  "Deep venous palmar arch.l": "cardiovascular.model-node-0592",
  "Ulnar veins.l": "cardiovascular.model-node-0593",
  "Superficial venous palmar arch.l": "cardiovascular.model-node-0594",
  "Palmar digital veins.l": "cardiovascular.model-node-0595",
  "Cephalic vein.l": "cardiovascular.model-node-0596",
  "Dorsal venous network of hand.l": "cardiovascular.model-node-0597",
  "Dorsal digital veins of hand.l": "cardiovascular.model-node-0598",
  "Lateral thoracic vein.l": "cardiovascular.model-node-0599",
  "Posterior circumflex humeral vein.l": "cardiovascular.model-node-0600",
  "Subscapular vein.l": "cardiovascular.model-node-0601",
  "Circumflex scapular vein.l": "cardiovascular.model-node-0602",
  "Thoracodorsal vein.l": "cardiovascular.model-node-0603",
  "External jugular vein.l": "cardiovascular.model-node-0604",
  "Anterior jugular vein.l": "cardiovascular.model-node-0605",
  "Posterior auricular vein.l": "cardiovascular.model-node-0606",
  "Posterior division of retromandibular vein.l": "cardiovascular.model-node-0607",
  "Suprascapular vein.l": "cardiovascular.model-node-0608",
  "Right subclavian vein": "cardiovascular.model-node-0609",
  "Axillary vein.r": "cardiovascular.model-node-0610",
  "Anterior circumflex humeral vein.r": "cardiovascular.model-node-0611",
  "Basilic vein.r": "cardiovascular.model-node-0612",
  "Median cubital vein.r": "cardiovascular.model-node-0613",
  "Median antebrachial vein.r": "cardiovascular.model-node-0614",
  "Brachial veins.r": "cardiovascular.model-node-0615",
  "Radial veins.r": "cardiovascular.model-node-0616",
  "Deep venous palmar arch.r": "cardiovascular.model-node-0617",
  "Ulnar veins.r": "cardiovascular.model-node-0618",
  "Superficial venous palmar arch.r": "cardiovascular.model-node-0619",
  "Palmar digital veins.r": "cardiovascular.model-node-0620",
  "Cephalic vein.r": "cardiovascular.model-node-0621",
  "Dorsal venous network of hand.r": "cardiovascular.model-node-0622",
  "Dorsal digital veins of hand.r": "cardiovascular.model-node-0623",
  "Lateral thoracic vein.r": "cardiovascular.model-node-0624",
  "Posterior circumflex humeral vein.r": "cardiovascular.model-node-0625",
  "Subscapular vein.r": "cardiovascular.model-node-0626",
  "Circumflex scapular vein.r": "cardiovascular.model-node-0627",
  "Thoracodorsal vein.r": "cardiovascular.model-node-0628",
  "External jugular vein.r": "cardiovascular.model-node-0629",
  "Anterior jugular vein.r": "cardiovascular.model-node-0630",
  "Posterior auricular vein.r": "cardiovascular.model-node-0631",
  "Posterior division of retromandibular vein.r": "cardiovascular.model-node-0632",
  "Suprascapular vein.r": "cardiovascular.model-node-0633",
  "Azygos vein": "cardiovascular.model-node-0634",
  "Accessory hemi-azygos vein": "cardiovascular.model-node-0635",
  "Hemi-azygos vein": "cardiovascular.model-node-0636",
  "Left ascending lumbar vein": "cardiovascular.model-node-0637",
  "Left subcostal vein": "cardiovascular.model-node-0638",
  "Right ascending lumbar vein": "cardiovascular.model-node-0639",
  "Right subcostal vein": "cardiovascular.model-node-0640",
  "Right superior intercostal vein": "cardiovascular.model-node-0641",
  "Right superior phrenic vein": "cardiovascular.model-node-0642",
  "Left brachiocephalic vein": "cardiovascular.model-node-0643",
  "Internal thoracic veins.l": "cardiovascular.model-node-0644",
  "Musculophrenic veins.l": "cardiovascular.model-node-0645",
  "Superior epigastric veins.l": "cardiovascular.model-node-0646",
  "Left superior intercostal vein": "cardiovascular.model-node-0647",
  "Vertebral vein.l": "cardiovascular.model-node-0648",
  "Occipital vein.l": "cardiovascular.model-node-0649",
  "Right brachiocephalic vein": "cardiovascular.model-node-0650",
  "Internal thoracic veins.r": "cardiovascular.model-node-0651",
  "Musculophrenic veins.r": "cardiovascular.model-node-0652",
  "Superior epigastric veins.r": "cardiovascular.model-node-0653",
  "Vertebral vein.r": "cardiovascular.model-node-0654",
  "Occipital vein.r": "cardiovascular.model-node-0655"
} as const;
