/**
 * Identidades persistentes para estructuras musculares sin ficha educativa.
 * Los valores se conservan aunque cambien nombres, orden o índices del GLB.
 */
export const muscularStableIdByOriginalName = {
  "Linea alba": "muscular.model-node-0002",
  "Músculo cuadrado lumbar.l": "muscular.model-node-0003",
  "Músculo cuadrado lumbar.r": "muscular.model-node-0004",
  "Ligamento inguinal.l": "muscular.model-node-0005",
  "Ligamento inguinal.r": "muscular.model-node-0007",
  "Músculo piramidal.l": "muscular.model-node-0011",
  "Músculo piramidal.r": "muscular.model-node-0012",
  "Músculo largo de la cabeza.l": "muscular.model-node-0028",
  "Músculo largo de la cabeza.r": "muscular.model-node-0029",
  "Músculo largo del cuello.l": "muscular.model-node-0030",
  "Músculo largo del cuello.r": "muscular.model-node-0031",
  "Músculo recto anterior de la cabeza.l": "muscular.model-node-0032",
  "Músculo recto anterior de la cabeza.r": "muscular.model-node-0033",
  "Músculo recto lateral de la cabeza.l": "muscular.model-node-0034",
  "Músculo recto lateral de la cabeza.r": "muscular.model-node-0035",
  "Constrictor inferior de la faringe.l": "muscular.model-node-0037",
  "Constrictor inferior de la faringe.r": "muscular.model-node-0038",
  "Constrictor medio de la faringe.l": "muscular.model-node-0039",
  "Constrictor medio de la faringe.r": "muscular.model-node-0040",
  "Constrictor superior de la faringe.l": "muscular.model-node-0041",
  "Constrictor superior de la faringe.r": "muscular.model-node-0042",
  "Músculo estilofaríngeo.l": "muscular.model-node-0043",
  "Músculo estilofaríngeo.r": "muscular.model-node-0044",
  "Músculo esternotiroideo.l": "muscular.model-node-0048",
  "Músculo esternotiroideo.r": "muscular.model-node-0049",
  "Músculo aritenoideo transverso": "muscular.model-node-0055",
  "Músculo cricoaritenoideo lateral.l": "muscular.model-node-0056",
  "Músculo cricoaritenoideo lateral.r": "muscular.model-node-0057",
  "Músculo cricoaritenoideo posterior.l": "muscular.model-node-0058",
  "Músculo cricoaritenoideo posterior.r": "muscular.model-node-0059",
  "Porción ariepiglótica del músculo aritenoideo oblicuo.l": "muscular.model-node-0061",
  "Porción ariepiglótica del músculo aritenoideo oblicuo.r": "muscular.model-node-0062",
  "Porción externa del músculo tiroaritenoideo.l": "muscular.model-node-0063",
  "Porción externa del músculo tiroaritenoideo.r": "muscular.model-node-0064",
  "Porción oblicua del músculo cricotiroideo.l": "muscular.model-node-0065",
  "Porción oblicua del músculo cricotiroideo.r": "muscular.model-node-0066",
  "Porción recta del músculo cricotiroideo.l": "muscular.model-node-0067",
  "Porción recta del músculo cricotiroideo.r": "muscular.model-node-0068",
  "Porción tiroepiglótica del músculo tiroaritenoideo.l": "muscular.model-node-0069",
  "Porción tiroepiglótica del músculo tiroaritenoideo.r": "muscular.model-node-0070",
  "Músculo estilohioideo.l": "muscular.model-node-0078",
  "Músculo estilohioideo.r": "muscular.model-node-0079",
  "Músculo geniohioideo.l": "muscular.model-node-0080",
  "Músculo geniohioideo.r": "muscular.model-node-0081",
  "Músculo geniogloso.l": "muscular.model-node-0091",
  "Músculo geniogloso.r": "muscular.model-node-0092",
  "Músculo hiogloso.l": "muscular.model-node-0093",
  "Músculo hiogloso.r": "muscular.model-node-0094",
  "Músculo palatofaríngeo.l": "muscular.model-node-0097",
  "Músculo palatofaríngeo.r": "muscular.model-node-0098",
  "Anillo tendinoso común.l": "muscular.model-node-0100",
  "Anillo tendinoso común.r": "muscular.model-node-0101",
  "Elevador del párpado superior.l": "muscular.model-node-0102",
  "Elevador del párpado superior.r": "muscular.model-node-0103",
  "Músculo oblicuo inferior del bulbo ocular.l": "muscular.model-node-0104",
  "Músculo oblicuo inferior del bulbo ocular.r": "muscular.model-node-0105",
  "Músculo oblicuo superior del bulbo ocular.l": "muscular.model-node-0106",
  "Músculo oblicuo superior del bulbo ocular.r": "muscular.model-node-0107",
  "Músculo recto inferior.l": "muscular.model-node-0108",
  "Músculo recto inferior.r": "muscular.model-node-0109",
  "Músculo recto lateral.l": "muscular.model-node-0110",
  "Músculo recto lateral.r": "muscular.model-node-0111",
  "Músculo recto medial.l": "muscular.model-node-0112",
  "Músculo recto medial.r": "muscular.model-node-0113",
  "Músculo recto superior.l": "muscular.model-node-0114",
  "Músculo recto superior.r": "muscular.model-node-0115",
  "Tarso inferior.l": "muscular.model-node-0117",
  "Tarso inferior.r": "muscular.model-node-0118",
  "Tarso superior.l": "muscular.model-node-0119",
  "Tarso superior.r": "muscular.model-node-0120",
  "Tróclea del músculo oblicuo superior.l": "muscular.model-node-0121",
  "Tróclea del músculo oblicuo superior.r": "muscular.model-node-0122",
  "Cabeza inferior del músculo pterigoideo lateral.l": "muscular.model-node-0123",
  "Cabeza inferior del músculo pterigoideo lateral.r": "muscular.model-node-0124",
  "Cabeza superior del músculo pterigoideo lateral.l": "muscular.model-node-0125",
  "Cabeza superior del músculo pterigoideo lateral.r": "muscular.model-node-0126",
  "Músculo pterigoideo medial.l": "muscular.model-node-0127",
  "Músculo pterigoideo medial.r": "muscular.model-node-0128",
  "Aponeurosis epicraneal.l": "muscular.model-node-0136",
  "Aponeurosis epicraneal.r": "muscular.model-node-0137",
  "Músculo frontal.l": "muscular.model-node-0139",
  "Músculo frontal.r": "muscular.model-node-0140",
  "Músculo occipital.l": "muscular.model-node-0141",
  "Músculo occipital.r": "muscular.model-node-0142",
  "Músculo temporoparietal.l": "muscular.model-node-0143",
  "Músculo temporoparietal.r": "muscular.model-node-0144",
  "Depresor del labio inferior.l": "muscular.model-node-0148",
  "Depresor del labio inferior.r": "muscular.model-node-0149",
  "Depresor del septo nasal.l": "muscular.model-node-0150",
  "Depresor del septo nasal.r": "muscular.model-node-0151",
  "Depresor del ángulo oral.l": "muscular.model-node-0152",
  "Depresor del ángulo oral.r": "muscular.model-node-0153",
  "Elevador del angulo de la boca.l": "muscular.model-node-0154",
  "Elevador del angulo de la boca.r": "muscular.model-node-0155",
  "Elevador del labio superior.l": "muscular.model-node-0156",
  "Elevador del labio superior.r": "muscular.model-node-0157",
  "Elevador nasolabial.l": "muscular.model-node-0158",
  "Elevador nasolabial.r": "muscular.model-node-0159",
  "Músculo corrugador del supercilio.l": "muscular.model-node-0164",
  "Músculo corrugador del supercilio.r": "muscular.model-node-0165",
  "Músculo espinal de la cabeza.l": "muscular.model-node-0184",
  "Músculo espinal de la cabeza.r": "muscular.model-node-0185",
  "Músculo espinal del cuello.l": "muscular.model-node-0186",
  "Músculo espinal del cuello.r": "muscular.model-node-0187",
  "Músculo espinal del tórax.l": "muscular.model-node-0188",
  "Músculo espinal del tórax.r": "muscular.model-node-0189",
  "Músculo iliocostal del cuello": "muscular.model-node-0191",
  "Músculo iliocostal del cuello.r": "muscular.model-node-0192",
  "Músculo iliocostal del tórax.l": "muscular.model-node-0193",
  "Músculo iliocostal del tórax.r": "muscular.model-node-0194",
  "Músculo iliocostal lumbar.l": "muscular.model-node-0195",
  "Músculo iliocostal lumbar.r": "muscular.model-node-0196",
  "Músculo longísimo de la cabeza.l": "muscular.model-node-0198",
  "Músculo longísimo de la cabeza.r": "muscular.model-node-0199",
  "Músculo longísimo del tórax.l": "muscular.model-node-0200",
  "Músculo longísimo del tórax.r": "muscular.model-node-0201",
  "Músculo longísmo del cuello.l": "muscular.model-node-0202",
  "Músculo longísmo del cuello.r": "muscular.model-node-0203",
  "Músculo esplenio de la cabeza.l": "muscular.model-node-0207",
  "Músculo esplenio de la cabeza.r": "muscular.model-node-0208",
  "Músculo esplenio del cuello.l": "muscular.model-node-0209",
  "Músculo esplenio del cuello.r": "muscular.model-node-0210",
  "Músculos interespinosos del cuello.l": "muscular.model-node-0212",
  "Músculos interespinosos del cuello.r": "muscular.model-node-0213",
  "Músculos interespinosos del tórax.l": "muscular.model-node-0214",
  "Músculos interespinosos del tórax.r": "muscular.model-node-0215",
  "Músculos interespinosos lumbares.l": "muscular.model-node-0216",
  "Músculos interespinosos lumbares.r": "muscular.model-node-0217",
  "Músculo oblicuo inferior de la cabeza.l": "muscular.model-node-0220",
  "Músculo oblicuo inferior de la cabeza.r": "muscular.model-node-0221",
  "Músculo oblicuo superior de la cabeza.l": "muscular.model-node-0222",
  "Músculo oblicuo superior de la cabeza.r": "muscular.model-node-0223",
  "Músculo recto posterior mayor de la cabeza.l": "muscular.model-node-0224",
  "Músculo recto posterior mayor de la cabeza.r": "muscular.model-node-0225",
  "Músculo recto posterior menor de la cabeza.l": "muscular.model-node-0226",
  "Músculo recto posterior menor de la cabeza.r": "muscular.model-node-0227",
  "Músculo semiespinoso del cuello.l": "muscular.model-node-0236",
  "Músculo semiespinoso del cuello.r": "muscular.model-node-0237",
  "Músculo semiespinoso del tórax.l": "muscular.model-node-0238",
  "Músculo semiespinoso del tórax.r": "muscular.model-node-0239",
  "Rotadores.l": "muscular.model-node-0243",
  "Rotadores.r": "muscular.model-node-0244",
  "Elevador de la escápula.l": "muscular.model-node-0245",
  "Elevador de la escápula.r": "muscular.model-node-0246",
  "Músculo romboides mayor.l": "muscular.model-node-0249",
  "Músculo romboides mayor.r": "muscular.model-node-0250",
  "Músculo romboides menor.l": "muscular.model-node-0251",
  "Músculo romboides menor.r": "muscular.model-node-0252",
  "Músculo serrato posterior inferior.l": "muscular.model-node-0253",
  "Músculo serrato posterior inferior.r": "muscular.model-node-0254",
  "Músculo serrato posterior superior.l": "muscular.model-node-0255",
  "Músculo serrato posterior superior.r": "muscular.model-node-0256",
  "Partes dorsales de los m. lumbares intertransversarios lat..l": "muscular.model-node-0265",
  "Partes dorsales de los m. lumbares intertransversarios lat..r": "muscular.model-node-0266",
  "Partes ventrales de los m. lumbares intertransvarios lat..l": "muscular.model-node-0267",
  "Partes ventrales de los m. lumbares intertransvarios lat..r": "muscular.model-node-0268",
  "Músculo coccígeo.l": "muscular.model-node-0271",
  "Músculo coccígeo.r": "muscular.model-node-0272",
  "Arco tendinoso del elevador del ano.l": "muscular.model-node-0273",
  "Arco tendinoso del elevador del ano.r": "muscular.model-node-0274",
  "Músculo iliococcígeo.l": "muscular.model-node-0276",
  "Músculo iliococcígeo.r": "muscular.model-node-0277",
  "Músculo puboanal.l": "muscular.model-node-0278",
  "Músculo puboanal.r": "muscular.model-node-0279",
  "Músculo pubococcígeo.l": "muscular.model-node-0280",
  "Músculo pubococcígeo.r": "muscular.model-node-0281",
  "Esfínter anal externo.l": "muscular.model-node-0283",
  "Esfínter anal externo.r": "muscular.model-node-0284",
  "Elevadores cortos de las costillas.l": "muscular.model-node-0288",
  "Elevadores cortos de las costillas.r": "muscular.model-node-0289",
  "Elevadores largos de las costillas.l": "muscular.model-node-0291",
  "Elevadores largos de las costillas.r": "muscular.model-node-0292",
  "Músculo subclavio.l": "muscular.model-node-0304",
  "Músculo subclavio.r": "muscular.model-node-0305",
  "Músculo transverso del tórax.l": "muscular.model-node-0306",
  "Músculo transverso del tórax.r": "muscular.model-node-0307",
  "(Bolsa iliopectínea).l": "muscular.model-node-0316",
  "(Bolsa iliopectínea).r": "muscular.model-node-0317",
  "(Bolsa prepatelar subtendinosa).l": "muscular.model-node-0318",
  "(Bolsa prepatelar subtendinosa).r": "muscular.model-node-0319",
  "Bolsa anserina.l": "muscular.model-node-0320",
  "Bolsa anserina.r": "muscular.model-node-0321",
  "Bolsa calcánea subcutánea.l": "muscular.model-node-0322",
  "Bolsa calcánea subcutánea.r": "muscular.model-node-0323",
  "Bolsa calcánea subtendinosa.l": "muscular.model-node-0324",
  "Bolsa calcánea subtendinosa.r": "muscular.model-node-0325",
  "Bolsa del musculo semimembranoso.l": "muscular.model-node-0326",
  "Bolsa del musculo semimembranoso.r": "muscular.model-node-0327",
  "Bolsa del músculo piriforme.l": "muscular.model-node-0328",
  "Bolsa del músculo piriforme.r": "muscular.model-node-0329",
  "Bolsa infrapatelar profunda.l": "muscular.model-node-0330",
  "Bolsa infrapatelar profunda.r": "muscular.model-node-0331",
  "Bolsa isquiática del obturador interno.l": "muscular.model-node-0334",
  "Bolsa isquiática del obturador interno.r": "muscular.model-node-0335",
  "Bolsa prepatelar subcutánea.l": "muscular.model-node-0336",
  "Bolsa prepatelar subcutánea.r": "muscular.model-node-0337",
  "Bolsa subcutánea de la tuberosidad de la tibia.l": "muscular.model-node-0338",
  "Bolsa subcutánea de la tuberosidad de la tibia.r": "muscular.model-node-0339",
  "Bolsa subcutánea del maléolo lateral.l": "muscular.model-node-0340",
  "Bolsa subcutánea del maléolo lateral.r": "muscular.model-node-0341",
  "Bolsa subcutánea del maléolo medial.l": "muscular.model-node-0342",
  "Bolsa subcutánea del maléolo medial.r": "muscular.model-node-0343",
  "Bolsa subcutánea infrapatelar.l": "muscular.model-node-0344",
  "Bolsa subcutánea infrapatelar.r": "muscular.model-node-0345",
  "Bolsa subtendínea del obturador interno.l": "muscular.model-node-0350",
  "Bolsa subtendínea del obturador interno.r": "muscular.model-node-0351",
  "Bolsa subtendínea ilíaca.l": "muscular.model-node-0352",
  "Bolsa subtendínea ilíaca.r": "muscular.model-node-0353",
  "Bolsa suprapatelar.l": "muscular.model-node-0362",
  "Bolsa suprapatelar.r": "muscular.model-node-0363",
  "Bolsa trocantérica del músculo glúteo mínimo.l": "muscular.model-node-0366",
  "Bolsa trocantérica del músculo glúteo mínimo.r": "muscular.model-node-0367",
  "Bolsa trocantérica subcutánea.l": "muscular.model-node-0368",
  "Bolsa trocantérica subcutánea.r": "muscular.model-node-0369",
  "Bolsas glúteas intermusculares.l": "muscular.model-node-0371",
  "Bolsas glúteas intermusculares.r": "muscular.model-node-0372",
  "Subfacial prepatellar bursa.l": "muscular.model-node-0373",
  "Subfacial prepatellar bursa.r": "muscular.model-node-0374",
  "Trochanteric bursa of gluteus medius muscle.l": "muscular.model-node-0375",
  "Trochanteric bursa of gluteus medius muscle.r": "muscular.model-node-0376",
  "Extensor largo de los dedos.l": "muscular.model-node-0379",
  "Tendón del extensor largo de los dedos.l": "muscular.model-node-0378",
  "Extensor largo de los dedos.r": "muscular.model-node-0381",
  "Tendón del extensor largo de los dedos.r": "muscular.model-node-0380",
  "Extensor largo del hállux.l": "muscular.model-node-0382",
  "Extensor largo del hállux.r": "muscular.model-node-0383",
  "Retináculo patelar lateral.l": "muscular.model-node-0399",
  "Retináculo patelar lateral.r": "muscular.model-node-0400",
  "Retináculo patelar medial.l": "muscular.model-node-0401",
  "Retináculo patelar medial.r": "muscular.model-node-0402",
  "Músculo pectíneo.l": "muscular.model-node-0419",
  "Músculo pectíneo.r": "muscular.model-node-0420",
  "Obturador externo.l": "muscular.model-node-0421",
  "Obturador externo.r": "muscular.model-node-0422",
  "Flexor largo del hállux.l": "muscular.model-node-0424",
  "Flexor largo del hállux.r": "muscular.model-node-0425",
  "Músculo flexor largo de los dedos.l": "muscular.model-node-0426",
  "Músculo flexor largo de los dedos.r": "muscular.model-node-0427",
  "Músculo poplíteo.l": "muscular.model-node-0428",
  "Músculo poplíteo.r": "muscular.model-node-0429",
  "Músculo plantar.l": "muscular.model-node-0437",
  "Músculo plantar.r": "muscular.model-node-0438",
  "Tendón calcáneo.l": "muscular.model-node-0442",
  "Tendón calcáneo.r": "muscular.model-node-0443",
  "Músculo ilíaco.l": "muscular.model-node-0454",
  "Músculo ilíaco.r": "muscular.model-node-0455",
  "Psoas mayor.l": "muscular.model-node-0456",
  "Psoas mayor.r": "muscular.model-node-0457",
  "(Músculo oponente del dedo mínimo del pie).l": "muscular.model-node-0459",
  "(Músculo oponente del dedo mínimo del pie).r": "muscular.model-node-0460",
  "Abductor del dedo mínimo del pie.l": "muscular.model-node-0461",
  "Abductor del dedo mínimo del pie.r": "muscular.model-node-0462",
  "Abductor del hállux.l": "muscular.model-node-0463",
  "Abductor del hállux.r": "muscular.model-node-0464",
  "Cabeza oblicua del aductor del hállux.l": "muscular.model-node-0466",
  "Cabeza oblicua del aductor del hállux.r": "muscular.model-node-0467",
  "Cabeza transversa del aductor del hállux.l": "muscular.model-node-0468",
  "Cabeza transversa del aductor del hállux.r": "muscular.model-node-0469",
  "Extensor corto de los dedos.l": "muscular.model-node-0470",
  "Extensor corto de los dedos.r": "muscular.model-node-0471",
  "Extensor corto del hállux.l": "muscular.model-node-0472",
  "Extensor corto del hállux.r": "muscular.model-node-0473",
  "Cabeza lateral del flexor corto del hállux.l": "muscular.model-node-0476",
  "Cabeza lateral del flexor corto del hállux.r": "muscular.model-node-0477",
  "Cabeza medial del flexor corto del hállux.l": "muscular.model-node-0478",
  "Cabeza medial del flexor corto del hállux.r": "muscular.model-node-0479",
  "Flexor del dedo mínimo del pie.l": "muscular.model-node-0481",
  "Flexor del dedo mínimo del pie.r": "muscular.model-node-0482",
  "Músculo cuadrado plantar.l": "muscular.model-node-0483",
  "Músculo cuadrado plantar.r": "muscular.model-node-0484",
  "Músculo gemelo inferior.l": "muscular.model-node-0494",
  "Músculo gemelo inferior.r": "muscular.model-node-0495",
  "Músculo gemelo superior.l": "muscular.model-node-0496",
  "Músculo gemelo superior.r": "muscular.model-node-0497",
  "Tracto iliotibial.l": "muscular.model-node-0510",
  "Tracto iliotibial.r": "muscular.model-node-0512",
  "Tendon sheath of tibialis anterior.l": "muscular.model-node-0517",
  "Tendon sheath of tibialis anterior.r": "muscular.model-node-0518",
  "Vaina tendinosa del extensor largo de los dedos.l": "muscular.model-node-0519",
  "Vaina tendinosa del extensor largo de los dedos.r": "muscular.model-node-0520",
  "Vaina tendinosa común de los músculos fibulares.l": "muscular.model-node-0524",
  "Vaina tendinosa común de los músculos fibulares.r": "muscular.model-node-0525",
  "Vaina tendinosa plantar del músculo fibular largo.l": "muscular.model-node-0526",
  "Vaina tendinosa plantar del músculo fibular largo.r": "muscular.model-node-0527",
  "Vaina tendinosa del flexor largo de los dedos.l": "muscular.model-node-0529",
  "Vaina tendinosa del flexor largo de los dedos.r": "muscular.model-node-0530",
  "Vaina tendinosa del flexor largo del hállux.l": "muscular.model-node-0531",
  "Vaina tendinosa del flexor largo del hállux.r": "muscular.model-node-0532",
  "Vaina tendinosa del músculo tibial posterior.l": "muscular.model-node-0533",
  "Vaina tendinosa del músculo tibial posterior.r": "muscular.model-node-0534",
  "Bolsa bicipitoradial.l": "muscular.model-node-0536",
  "Bolsa bicipitoradial.r": "muscular.model-node-0537",
  "Bolsa subacromial.l": "muscular.model-node-0538",
  "Bolsa subacromial.r": "muscular.model-node-0539",
  "Bolsa subdeltoidea.l": "muscular.model-node-0540",
  "Bolsa subdeltoidea.r": "muscular.model-node-0541",
  "Coracobrachial bursa.l": "muscular.model-node-0551",
  "Coracobrachial bursa.r": "muscular.model-node-0552",
  "Subcutaneous acromial bursa.l": "muscular.model-node-0553",
  "Subcutaneous acromial bursa.r": "muscular.model-node-0554",
  "Flexor largo del pulgar.l": "muscular.model-node-0556",
  "Flexor largo del pulgar.r": "muscular.model-node-0557",
  "Flexor profundo de los dedos.l": "muscular.model-node-0558",
  "Flexor profundo de los dedos.r": "muscular.model-node-0559",
  "Cabeza humeral del flexor ulnar del carpo.l": "muscular.model-node-0563",
  "Cabeza humeral del flexor ulnar del carpo.r": "muscular.model-node-0564",
  "Cabeza humeroulnar del flexor superficial de los dedos.l": "muscular.model-node-0565",
  "Cabeza humeroulnar del flexor superficial de los dedos.r": "muscular.model-node-0566",
  "Cabeza radial del flexor superficial de los dedos.l": "muscular.model-node-0569",
  "Cabeza radial del flexor superficial de los dedos.r": "muscular.model-node-0570",
  "Cabeza ulnar del flexor ulnar del carpo.l": "muscular.model-node-0573",
  "Cabeza ulnar del flexor ulnar del carpo.r": "muscular.model-node-0574",
  "Flexor radial del carpo.l": "muscular.model-node-0575",
  "Flexor radial del carpo.r": "muscular.model-node-0576",
  "Músculo palmar largo.l": "muscular.model-node-0577",
  "Músculo palmar largo.r": "muscular.model-node-0578",
  "Abductor largo del pulgar.l": "muscular.model-node-0591",
  "Abductor largo del pulgar.r": "muscular.model-node-0592",
  "Extensor corto del pulgar.l": "muscular.model-node-0593",
  "Extensor corto del pulgar.r": "muscular.model-node-0594",
  "Extensor largo del pulgar.l": "muscular.model-node-0597",
  "Extensor largo del pulgar.r": "muscular.model-node-0598",
  "Cabeza humeral del extensor ulnar del carpo.l": "muscular.model-node-0602",
  "Cabeza humeral del extensor ulnar del carpo.r": "muscular.model-node-0603",
  "Cabeza ulnar del extensor ulnar del carpo.l": "muscular.model-node-0604",
  "Cabeza ulnar del extensor ulnar del carpo.r": "muscular.model-node-0605",
  "Extensor radial corto del carpo.l": "muscular.model-node-0610",
  "Extensor radial corto del carpo.r": "muscular.model-node-0611",
  "Extensor radial largo del carpo.l": "muscular.model-node-0612",
  "Extensor radial largo del carpo.r": "muscular.model-node-0613",
  "Músculo ancóneo.l": "muscular.model-node-0614",
  "Músculo ancóneo.r": "muscular.model-node-0615",
  "Cabeza oblicua del aductor del pulgar.l": "muscular.model-node-0631",
  "Cabeza oblicua del aductor del pulgar.r": "muscular.model-node-0632",
  "Cabeza profunda del flexor corto del pulgar.l": "muscular.model-node-0633",
  "Cabeza profunda del flexor corto del pulgar.r": "muscular.model-node-0634",
  "Cabeza superficial del flexor corto del pulgar.l": "muscular.model-node-0635",
  "Cabeza superficial del flexor corto del pulgar.r": "muscular.model-node-0636",
  "Cabeza transversa del aductor del pulgar.l": "muscular.model-node-0637",
  "Cabeza transversa del aductor del pulgar.r": "muscular.model-node-0638",
  "Tendon sheath - abd. pollicis longus - ext. pollicis brevis.l": "muscular.model-node-0676",
  "Tendon sheath - abd. pollicis longus - ext. pollicis brevis.r": "muscular.model-node-0677",
  "Tendon sheath of extensor digitorum and extensor indicis.l": "muscular.model-node-0680",
  "Tendon sheath of extensor digitorum and extensor indicis.r": "muscular.model-node-0681",
  "Tendon sheath of extensors carpi radialis.l": "muscular.model-node-0684",
  "Tendon sheath of extensors carpi radialis.r": "muscular.model-node-0685",
  "Vaina del tendón flexor común.l": "muscular.model-node-0689",
  "Vaina del tendón flexor común.r": "muscular.model-node-0690",
  "Cruciform part of fibrous sheath of digit of hand.l": "muscular.model-node-0696",
  "Cruciform part of fibrous sheath of digit of hand.r": "muscular.model-node-0697",
  "Vainas sinoviales de los dedos de la mano.l": "muscular.model-node-0698",
  "Vainas sinoviales de los dedos de la mano.r": "muscular.model-node-0699"
} as const satisfies Readonly<Record<string, string>>;

export type MuscularEducationalIdentityGroup = Readonly<{
  stableKey: string;
  anatomyIdBase: string;
  originalBaseNames: readonly string[];
}>;

/**
 * Particiones anatómicas explícitas para fichas que cubren más de una
 * estructura o más de una porción. Ninguna identidad depende de posiciones.
 */
export const muscularEducationalIdentityGroupsByEducationalId = {
  "muscular.masseter": [{
    stableKey: "muscle",
    anatomyIdBase: "muscular.masseter",
    originalBaseNames: ["Porción profunda del masétero", "Porción superficial del masétero"],
  }],
  "muscular.orbicularis-oculi": [{
    stableKey: "muscle",
    anatomyIdBase: "muscular.orbicularis-oculi",
    originalBaseNames: ["Parte palpebral del múculo orbicular del ojo", "Porción orbitaria del músculo orbicular del ojo"],
  }],
  "muscular.digastric": [{
    stableKey: "muscle",
    anatomyIdBase: "muscular.digastric",
    originalBaseNames: ["Tendón intermedio del músculo digástrico", "Vientre anterior del músculo digástrico", "Vientre posterior del músculo digástrico"],
  }],
  "muscular.scalene-group": [
    { stableKey: "anterior-scalene", anatomyIdBase: "muscular.scalene-group.anterior-scalene", originalBaseNames: ["Músculo escaleno anterior"] },
    { stableKey: "middle-scalene", anatomyIdBase: "muscular.scalene-group.middle-scalene", originalBaseNames: ["Músculo escaleno medio"] },
    { stableKey: "posterior-scalene", anatomyIdBase: "muscular.scalene-group.posterior-scalene", originalBaseNames: ["Músculo escaleno posterior"] },
  ],
  "muscular.infrahyoid-group": [
    { stableKey: "sternohyoid", anatomyIdBase: "muscular.infrahyoid-group.sternohyoid", originalBaseNames: ["Músculo esternohioideo"] },
    { stableKey: "omohyoid", anatomyIdBase: "muscular.infrahyoid-group.omohyoid", originalBaseNames: ["Músculo omohioideo"] },
    { stableKey: "thyrohyoid", anatomyIdBase: "muscular.infrahyoid-group.thyrohyoid", originalBaseNames: ["Músculo tirohioideo"] },
  ],
  "muscular.zygomaticus": [
    { stableKey: "major", anatomyIdBase: "muscular.zygomaticus.major", originalBaseNames: ["Músculo cigomático mayor"] },
    { stableKey: "minor", anatomyIdBase: "muscular.zygomaticus.minor", originalBaseNames: ["Músculo cigomático menor"] },
  ],
  "muscular.facial-expression": [
    { stableKey: "mentalis", anatomyIdBase: "muscular.facial-expression.mentalis", originalBaseNames: ["Músculo mental"] },
    { stableKey: "nasalis", anatomyIdBase: "muscular.facial-expression.nasalis", originalBaseNames: ["Músculo nasal"] },
    { stableKey: "procerus", anatomyIdBase: "muscular.facial-expression.procerus", originalBaseNames: ["Músculo prócer"] },
    { stableKey: "risorius", anatomyIdBase: "muscular.facial-expression.risorius", originalBaseNames: ["Músculo risorio"] },
  ],
  "muscular.pectoralis-major": [{
    stableKey: "muscle",
    anatomyIdBase: "muscular.pectoralis-major",
    originalBaseNames: ["(Porción abdominal del músculo pectoral mayor)", "Porción clavicular del músculo pectoral mayor", "Porción esternocostal del músculo pectoral mayor"],
  }],
  "muscular.trapezius": [
    { stableKey: "subtendinous-bursa", anatomyIdBase: "muscular.trapezius.subtendinous-bursa", originalBaseNames: ["Bolsa subtendinosa del músculo trapecio"] },
    { stableKey: "muscle", anatomyIdBase: "muscular.trapezius.muscle", originalBaseNames: ["Porción ascendente del músculo trapecio", "Porción descendente del músculo trapecio", "Porción transversa del músculo trapecio"] },
  ],
  "muscular.intercostals": [
    { stableKey: "external", anatomyIdBase: "muscular.intercostals.external", originalBaseNames: ["Músculos intercostales externos"] },
    { stableKey: "internal", anatomyIdBase: "muscular.intercostals.internal", originalBaseNames: ["Músculos intercostales internos"] },
    { stableKey: "innermost", anatomyIdBase: "muscular.intercostals.innermost", originalBaseNames: ["Músculos intercostales íntimos"] },
  ],
  "muscular.multifidus": [{
    stableKey: "muscle-group",
    anatomyIdBase: "muscular.multifidus",
    originalBaseNames: ["Músculo multifido del cuello", "Músculo multifido del tórax", "Músculo multifido lumbar"],
  }],
  "muscular.deltoid": [{
    stableKey: "muscle",
    anatomyIdBase: "muscular.deltoid",
    originalBaseNames: ["Porción acromial del músculo deltoides", "Porción clavicular del músculo deltoides", "Porción espinal escapular del músculo deltoides"],
  }],
  "muscular.biceps-brachii": [{
    stableKey: "muscle",
    anatomyIdBase: "muscular.biceps-brachii",
    originalBaseNames: ["Cabeza corta músculo del bíceps braquial", "Cabeza larga del músculo bíceps braquial"],
  }],
  "muscular.triceps-brachii": [
    { stableKey: "subtendinous-bursa", anatomyIdBase: "muscular.triceps-brachii.subtendinous-bursa", originalBaseNames: ["Bolsa subtendinosa del músculo tríceps braquial"] },
    { stableKey: "muscle", anatomyIdBase: "muscular.triceps-brachii.muscle", originalBaseNames: ["Cabeza larga del músculo tríceps braquial", "Cabeza lateral del músculo tríceps braquial", "Cabeza medial del músculo tríceps braquial"] },
  ],
  "muscular.infraspinatus": [
    { stableKey: "subtendinous-bursa", anatomyIdBase: "muscular.infraspinatus.subtendinous-bursa", originalBaseNames: ["Bolsa subtendinosa del músculo infraespinoso"] },
    { stableKey: "muscle", anatomyIdBase: "muscular.infraspinatus.muscle", originalBaseNames: ["Músculo infraespinoso"] },
  ],
  "muscular.teres-major": [
    { stableKey: "subtendinous-bursa", anatomyIdBase: "muscular.teres-major.subtendinous-bursa", originalBaseNames: ["Bolsa subtendinosa del músculo redondo mayor"] },
    { stableKey: "muscle", anatomyIdBase: "muscular.teres-major.muscle", originalBaseNames: ["Músculo redondo mayor"] },
  ],
  "muscular.pronators": [
    { stableKey: "pronator-teres", anatomyIdBase: "muscular.pronators.pronator-teres", originalBaseNames: ["Cabeza profunda del pronador redondo", "Cabeza superficial del pronador redondo"] },
    { stableKey: "pronator-quadratus", anatomyIdBase: "muscular.pronators.pronator-quadratus", originalBaseNames: ["Pronador cuadrado"] },
  ],
  "muscular.finger-extensors": [
    { stableKey: "extensor-digitorum", anatomyIdBase: "muscular.finger-extensors.extensor-digitorum", originalBaseNames: ["Extensor de los dedos"] },
    { stableKey: "extensor-digiti-minimi", anatomyIdBase: "muscular.finger-extensors.extensor-digiti-minimi", originalBaseNames: ["Extensor del dedo mínimo"] },
    { stableKey: "extensor-indicis", anatomyIdBase: "muscular.finger-extensors.extensor-indicis", originalBaseNames: ["Extensor del índice"] },
  ],
  "muscular.hand-intrinsics": [
    { stableKey: "lumbricals", anatomyIdBase: "muscular.hand-intrinsics.lumbricals", originalBaseNames: ["Músculos lumbricales de la mano"] },
    { stableKey: "dorsal-interossei", anatomyIdBase: "muscular.hand-intrinsics.dorsal-interossei", originalBaseNames: ["Músculos interóseos dorsales de la mano"] },
    { stableKey: "palmar-interossei", anatomyIdBase: "muscular.hand-intrinsics.palmar-interossei", originalBaseNames: ["Músculos interóseos palmares"] },
  ],
  "muscular.thenar": [
    { stableKey: "abductor-pollicis-brevis", anatomyIdBase: "muscular.thenar.abductor-pollicis-brevis", originalBaseNames: ["Abductor corto del pulgar"] },
    { stableKey: "opponens-pollicis", anatomyIdBase: "muscular.thenar.opponens-pollicis", originalBaseNames: ["Músculo oponente del pulgar"] },
  ],
  "muscular.hypothenar": [
    { stableKey: "abductor-digiti-minimi", anatomyIdBase: "muscular.hypothenar.abductor-digiti-minimi", originalBaseNames: ["Abductor del dedo mínimo de la mano"] },
    { stableKey: "opponens-digiti-minimi", anatomyIdBase: "muscular.hypothenar.opponens-digiti-minimi", originalBaseNames: ["Músculo oponente del dedo mínimo de la mano"] },
    { stableKey: "flexor-digiti-minimi", anatomyIdBase: "muscular.hypothenar.flexor-digiti-minimi", originalBaseNames: ["Flexor del dedo mínimo de la mano"] },
  ],
  "muscular.gluteus-maximus": [
    { stableKey: "ischial-bursa", anatomyIdBase: "muscular.gluteus-maximus.ischial-bursa", originalBaseNames: ["Bolsa isquiática del músculo glúteo máximo"] },
    { stableKey: "trochanteric-bursa", anatomyIdBase: "muscular.gluteus-maximus.trochanteric-bursa", originalBaseNames: ["Bolsa trocantérica del músculo glúteo máximo"] },
    { stableKey: "muscle", anatomyIdBase: "muscular.gluteus-maximus.muscle", originalBaseNames: ["Músculo glúteo máximo"] },
  ],
  "muscular.sartorius": [
    { stableKey: "subtendinous-bursa", anatomyIdBase: "muscular.sartorius.subtendinous-bursa", originalBaseNames: ["Bolsa subtendínea del músculo sartorio"] },
    { stableKey: "muscle", anatomyIdBase: "muscular.sartorius.muscle", originalBaseNames: ["Músculo sartorio"] },
  ],
  "muscular.biceps-femoris": [
    { stableKey: "inferior-subtendinous-bursa", anatomyIdBase: "muscular.biceps-femoris.inferior-subtendinous-bursa", originalBaseNames: ["Bolsa subtendínea inferior del músculo bíceps femoral"] },
    { stableKey: "superior-bursa", anatomyIdBase: "muscular.biceps-femoris.superior-bursa", originalBaseNames: ["Bolsa superior del músculo bíceps femoral"] },
    { stableKey: "muscle", anatomyIdBase: "muscular.biceps-femoris.muscle", originalBaseNames: ["Cabeza corta del músculo bíceps femoral", "Cabeza larga del músculo bíceps femoral"] },
  ],
  "muscular.tibialis-anterior": [
    { stableKey: "subtendinous-bursa", anatomyIdBase: "muscular.tibialis-anterior.subtendinous-bursa", originalBaseNames: ["Bolsa subtendínea del músculo tibial anterior"] },
    { stableKey: "muscle", anatomyIdBase: "muscular.tibialis-anterior.muscle", originalBaseNames: ["Músculo tibial anterior"] },
  ],
  "muscular.gastrocnemius": [
    { stableKey: "lateral-subtendinous-bursa", anatomyIdBase: "muscular.gastrocnemius.lateral-subtendinous-bursa", originalBaseNames: ["Bolsa subtendínea lateral del músculo gastrocnemio"] },
    { stableKey: "medial-subtendinous-bursa", anatomyIdBase: "muscular.gastrocnemius.medial-subtendinous-bursa", originalBaseNames: ["Bolsa subtendínea medial del músculo gastrocnemio"] },
    { stableKey: "muscle", anatomyIdBase: "muscular.gastrocnemius.muscle", originalBaseNames: ["Cabeza lateral del músculo gastrocnemio", "Cabeza medial del músculo gastrocnemio"] },
  ],
  "muscular.adductors": [
    { stableKey: "adductor-brevis", anatomyIdBase: "muscular.adductors.adductor-brevis", originalBaseNames: ["Aductor corto"] },
    { stableKey: "adductor-longus", anatomyIdBase: "muscular.adductors.adductor-longus", originalBaseNames: ["Aductor largo"] },
    { stableKey: "adductor-magnus", anatomyIdBase: "muscular.adductors.adductor-magnus", originalBaseNames: ["Aductor mayor"] },
    { stableKey: "adductor-minimus", anatomyIdBase: "muscular.adductors.adductor-minimus", originalBaseNames: ["(Aductor mínimo)"] },
  ],
  "muscular.fibular-group": [
    { stableKey: "fibularis-longus", anatomyIdBase: "muscular.fibular-group.fibularis-longus", originalBaseNames: ["Músculo fibular largo"] },
    { stableKey: "fibularis-brevis", anatomyIdBase: "muscular.fibular-group.fibularis-brevis", originalBaseNames: ["Músculo fibular corto"] },
    { stableKey: "fibularis-tertius", anatomyIdBase: "muscular.fibular-group.fibularis-tertius", originalBaseNames: ["Músculo fibular tercero"] },
  ],
  "muscular.deep-lateral-rotators": [
    { stableKey: "piriformis", anatomyIdBase: "muscular.deep-lateral-rotators.piriformis", originalBaseNames: ["Músculo piriforme"] },
    { stableKey: "obturator-internus", anatomyIdBase: "muscular.deep-lateral-rotators.obturator-internus", originalBaseNames: ["Obturador interno"] },
    { stableKey: "quadratus-femoris", anatomyIdBase: "muscular.deep-lateral-rotators.quadratus-femoris", originalBaseNames: ["Músculo cuadrado femoral"] },
  ],
  "muscular.foot-intrinsics": [
    { stableKey: "lumbricals", anatomyIdBase: "muscular.foot-intrinsics.lumbricals", originalBaseNames: ["Músculos lumbricales del pie"] },
    { stableKey: "dorsal-interossei", anatomyIdBase: "muscular.foot-intrinsics.dorsal-interossei", originalBaseNames: ["Músculos interóseos dorsales del pie"] },
    { stableKey: "plantar-interossei", anatomyIdBase: "muscular.foot-intrinsics.plantar-interossei", originalBaseNames: ["Músculos interóseos plantares"] },
    { stableKey: "flexor-digitorum-brevis", anatomyIdBase: "muscular.foot-intrinsics.flexor-digitorum-brevis", originalBaseNames: ["Flexor corto de los dedos"] },
  ],
  "muscular.prevertebral-group": [{
    stableKey: "muscle-group",
    anatomyIdBase: "muscular.prevertebral-group",
    originalBaseNames: ["Músculo largo de la cabeza", "Músculo largo del cuello", "Músculo recto anterior de la cabeza", "Músculo recto lateral de la cabeza"],
  }],
  "muscular.pharyngeal-constrictors": [{
    stableKey: "muscle-group",
    anatomyIdBase: "muscular.pharyngeal-constrictors",
    originalBaseNames: ["Constrictor superior de la faringe", "Constrictor medio de la faringe", "Constrictor inferior de la faringe"],
  }],
  "muscular.stylopharyngeus": [{
    stableKey: "muscle",
    anatomyIdBase: "muscular.stylopharyngeus",
    originalBaseNames: ["Músculo estilofaríngeo"],
  }],
  "muscular.sternothyroid": [{
    stableKey: "muscle",
    anatomyIdBase: "muscular.sternothyroid",
    originalBaseNames: ["Músculo esternotiroideo"],
  }],
  "muscular.laryngeal-abductors-adductors": [
    { stableKey: "posterior-cricoarytenoid", anatomyIdBase: "muscular.laryngeal-abductors-adductors.posterior-cricoarytenoid", originalBaseNames: ["Músculo cricoaritenoideo posterior"] },
    { stableKey: "lateral-cricoarytenoid", anatomyIdBase: "muscular.laryngeal-abductors-adductors.lateral-cricoarytenoid", originalBaseNames: ["Músculo cricoaritenoideo lateral"] },
    { stableKey: "transverse-arytenoid", anatomyIdBase: "muscular.laryngeal-abductors-adductors.transverse-arytenoid", originalBaseNames: ["Músculo aritenoideo transverso"] },
  ],
  "muscular.suprahyoid-additional": [
    { stableKey: "stylohyoid", anatomyIdBase: "muscular.suprahyoid-additional.stylohyoid", originalBaseNames: ["Músculo estilohioideo"] },
    { stableKey: "geniohyoid", anatomyIdBase: "muscular.suprahyoid-additional.geniohyoid", originalBaseNames: ["Músculo geniohioideo"] },
  ],
  "muscular.tongue-muscles": [
    { stableKey: "genioglossus", anatomyIdBase: "muscular.tongue-muscles.genioglossus", originalBaseNames: ["Músculo geniogloso"] },
    { stableKey: "hyoglossus", anatomyIdBase: "muscular.tongue-muscles.hyoglossus", originalBaseNames: ["Músculo hiogloso"] },
  ],
  "muscular.palatopharyngeus": [{
    stableKey: "muscle",
    anatomyIdBase: "muscular.palatopharyngeus",
    originalBaseNames: ["Músculo palatofaríngeo"],
  }],
  "muscular.extraocular-group": [
    { stableKey: "levator-palpebrae", anatomyIdBase: "muscular.extraocular-group.levator-palpebrae", originalBaseNames: ["Elevador del párpado superior"] },
    { stableKey: "superior-rectus", anatomyIdBase: "muscular.extraocular-group.superior-rectus", originalBaseNames: ["Músculo recto superior"] },
    { stableKey: "inferior-rectus", anatomyIdBase: "muscular.extraocular-group.inferior-rectus", originalBaseNames: ["Músculo recto inferior"] },
    { stableKey: "medial-rectus", anatomyIdBase: "muscular.extraocular-group.medial-rectus", originalBaseNames: ["Músculo recto medial"] },
    { stableKey: "lateral-rectus", anatomyIdBase: "muscular.extraocular-group.lateral-rectus", originalBaseNames: ["Músculo recto lateral"] },
    { stableKey: "superior-oblique", anatomyIdBase: "muscular.extraocular-group.superior-oblique", originalBaseNames: ["Músculo oblicuo superior del bulbo ocular"] },
    { stableKey: "inferior-oblique", anatomyIdBase: "muscular.extraocular-group.inferior-oblique", originalBaseNames: ["Músculo oblicuo inferior del bulbo ocular"] },
  ],
  "muscular.pterygoid-group": [
    { stableKey: "medial-pterygoid", anatomyIdBase: "muscular.pterygoid-group.medial-pterygoid", originalBaseNames: ["Músculo pterigoideo medial"] },
    { stableKey: "inferior-head-lateral-pterygoid", anatomyIdBase: "muscular.pterygoid-group.inferior-head-lateral-pterygoid", originalBaseNames: ["Cabeza inferior del músculo pterigoideo lateral"] },
    { stableKey: "superior-head-lateral-pterygoid", anatomyIdBase: "muscular.pterygoid-group.superior-head-lateral-pterygoid", originalBaseNames: ["Cabeza superior del músculo pterigoideo lateral"] },
  ],
  "muscular.epicranial-group": [
    { stableKey: "frontalis", anatomyIdBase: "muscular.epicranial-group.frontalis", originalBaseNames: ["Músculo frontal"] },
    { stableKey: "occipitalis", anatomyIdBase: "muscular.epicranial-group.occipitalis", originalBaseNames: ["Músculo occipital"] },
    { stableKey: "temporoparietalis", anatomyIdBase: "muscular.epicranial-group.temporoparietalis", originalBaseNames: ["Músculo temporoparietal"] },
  ],
  "muscular.facial-expression-detailed": [
    { stableKey: "depressor-labii-inferioris", anatomyIdBase: "muscular.facial-expression-detailed.depressor-labii-inferioris", originalBaseNames: ["Depresor del labio inferior"] },
    { stableKey: "depressor-anguli-oris", anatomyIdBase: "muscular.facial-expression-detailed.depressor-anguli-oris", originalBaseNames: ["Depresor del ángulo oral"] },
    { stableKey: "depressor-septi-nasi", anatomyIdBase: "muscular.facial-expression-detailed.depressor-septi-nasi", originalBaseNames: ["Depresor del septo nasal"] },
    { stableKey: "levator-anguli-oris", anatomyIdBase: "muscular.facial-expression-detailed.levator-anguli-oris", originalBaseNames: ["Elevador del angulo de la boca"] },
    { stableKey: "levator-labii-superioris", anatomyIdBase: "muscular.facial-expression-detailed.levator-labii-superioris", originalBaseNames: ["Elevador del labio superior"] },
    { stableKey: "levator-labii-superioris-alaeque-nasi", anatomyIdBase: "muscular.facial-expression-detailed.levator-labii-superioris-alaeque-nasi", originalBaseNames: ["Elevador nasolabial"] },
    { stableKey: "corrugator-supercilii", anatomyIdBase: "muscular.facial-expression-detailed.corrugator-supercilii", originalBaseNames: ["Músculo corrugador del supercilio"] },
  ],
} as const satisfies Readonly<
  Record<string, readonly MuscularEducationalIdentityGroup[]>
>;
