import type { AnatomyDivisionId } from "../types";

/** Capas estáticas generadas desde la jerarquía validada del GLB nervioso. */
export const nervousLayerByOriginalName = {
  " Posterior transverse collateral sulcus.l": "nervous-central",
  " Posterior transverse collateral sulcus.r": "nervous-central",
  "(Rama comunicante del nervio mediano con el nervio ulnar).l": "nervous-peripheral",
  "(Rama comunicante del nervio mediano con el nervio ulnar).r": "nervous-peripheral",
  "Acueducto del mesencéfalo": "nervous-central",
  "Ala del lóbulo central.l": "nervous-central",
  "Ala del lóbulo central.r": "nervous-central",
  "Ampulla del canalículo lacrimal.l": "nervous-sense",
  "Ampulla del canalículo lacrimal.r": "nervous-sense",
  "Amígdala del cerebelo.l": "nervous-central",
  "Amígdala del cerebelo.r": "nervous-central",
  "Anterior occipital sulcus*.l": "nervous-central",
  "Anterior occipital sulcus*.r": "nervous-central",
  "Base del pedúnculo.l": "nervous-central",
  "Base del pedúnculo.r": "nervous-central",
  "Bulbo raquídeo.l": "nervous-central",
  "Bulbo raquídeo.r": "nervous-central",
  "Canal central": "nervous-central",
  "Canal central.001": "nervous-central",
  "Canal nasolagrimal.l": "nervous-sense",
  "Canal nasolagrimal.r": "nervous-sense",
  "Canalículo lagrimal.l": "nervous-sense",
  "Canalículo lagrimal.r": "nervous-sense",
  "Cauda equina": "nervous-peripheral",
  "Cingulate gyrus (Posteroventral part*).l": "nervous-central",
  "Cingulate gyrus (Posteroventral part*).r": "nervous-central",
  "Cingulate gyrus and sulcus (Middle anterior part).l": "nervous-central",
  "Cingulate gyrus and sulcus (Middle anterior part).r": "nervous-central",
  "Cingulate gyrus and sulcus (Middle posterior part).l": "nervous-central",
  "Cingulate gyrus and sulcus (Middle posterior part).r": "nervous-central",
  "Cingulate gyrus and sulcus (Posterior dorsal part).l": "nervous-central",
  "Cingulate gyrus and sulcus (Posterior dorsal part).r": "nervous-central",
  "Cingulate sulcus (Marginal part*).l": "nervous-central",
  "Cingulate sulcus (Marginal part*).r": "nervous-central",
  "Colículo inferior.l": "nervous-central",
  "Colículo inferior.r": "nervous-central",
  "Colículo superior.l": "nervous-central",
  "Colículo superior.r": "nervous-central",
  "Comisura anterior": "nervous-central",
  "Comisura hipocampal": "nervous-central",
  "Comisura posterior": "nervous-central",
  "Cuarto ventrículo": "nervous-central",
  "Cuerda del tímpano.l": "nervous-peripheral",
  "Cuerda del tímpano.r": "nervous-peripheral",
  "Cuerno anterior de la médula espinal": "nervous-central",
  "Cuerno posterior de la médula espinal": "nervous-central",
  "Cuerpo amigdaloide.l": "nervous-central",
  "Cuerpo amigdaloide.r": "nervous-central",
  "Cuerpo calloso": "nervous-central",
  "Cuerpo geniculado lateral.l": "nervous-central",
  "Cuerpo geniculado lateral.r": "nervous-central",
  "Cuerpo geniculado medial.l": "nervous-central",
  "Cuerpo geniculado medial.r": "nervous-central",
  "Cuerpo mamilar.l": "nervous-central",
  "Cuerpo mamilar.r": "nervous-central",
  "Cuerpo vitreo.l": "nervous-sense",
  "Cuerpo vitreo.r": "nervous-sense",
  "Culmen": "nervous-central",
  "Cuneus.l": "nervous-central",
  "Cuneus.r": "nervous-central",
  "Cámara anterior del globo ocular.l": "nervous-sense",
  "Cámara anterior del globo ocular.r": "nervous-sense",
  "Cóclea.l": "nervous-sense",
  "Cóclea.r": "nervous-sense",
  "Córnea.l": "nervous-sense",
  "Córnea.r": "nervous-sense",
  "Declive": "nervous-central",
  "División anterior del nervio mandibular.l": "nervous-peripheral",
  "División anterior del nervio mandibular.r": "nervous-peripheral",
  "División anterior del tronco inferior del plexo braquial.l": "nervous-peripheral",
  "División anterior del tronco inferior del plexo braquial.r": "nervous-peripheral",
  "División anterior del tronco medio del plexo braquial.l": "nervous-peripheral",
  "División anterior del tronco medio del plexo braquial.r": "nervous-peripheral",
  "División anterior del tronco superior del plexo braquial.l": "nervous-peripheral",
  "División anterior del tronco superior del plexo braquial.r": "nervous-peripheral",
  "División posterior del nervio mandibular.l": "nervous-peripheral",
  "División posterior del nervio mandibular.r": "nervous-peripheral",
  "División posterior del tronco inferior del plexo braquial.l": "nervous-peripheral",
  "División posterior del tronco inferior del plexo braquial.r": "nervous-peripheral",
  "División posterior del tronco medio del plexo braquial.l": "nervous-peripheral",
  "División posterior del tronco medio del plexo braquial.r": "nervous-peripheral",
  "División posterior del tronco superior del plexo braquial.l": "nervous-peripheral",
  "División posterior del tronco superior del plexo braquial.r": "nervous-peripheral",
  "Dura espinal": "nervous-central",
  "Esclera.l": "nervous-sense",
  "Esclera.r": "nervous-sense",
  "Estrías talámicas medulares.l": "nervous-central",
  "Estrías talámicas medulares.r": "nervous-central",
  "Fascículo anterior propio": "nervous-central",
  "Fascículo cuneiforme": "nervous-central",
  "Fascículo grácil": "nervous-central",
  "Fascículo lateral propio": "nervous-central",
  "Fascículo posterior del plexo braquial.l": "nervous-peripheral",
  "Fascículo posterior del plexo braquial.r": "nervous-peripheral",
  "Fascículo posterior propio": "nervous-central",
  "Fibras zonulares.l": "nervous-sense",
  "Fibras zonulares.r": "nervous-sense",
  "Flocculus.l": "nervous-central",
  "Flocculus.r": "nervous-central",
  "Folio del vermis": "nervous-central",
  "Fornix.l": "nervous-central",
  "Fornix.r": "nervous-central",
  "Fosa interpeduncular.l": "nervous-central",
  "Fosa interpeduncular.r": "nervous-central",
  "Ganglio espinal.l": "nervous-peripheral",
  "Ganglio espinal.r": "nervous-peripheral",
  "Ganglios del tronco simpático.l": "nervous-peripheral",
  "Ganglios del tronco simpático.r": "nervous-peripheral",
  "Giro angular.l": "nervous-central",
  "Giro angular.r": "nervous-central",
  "Giro frontal medio.l": "nervous-central",
  "Giro frontal medio.r": "nervous-central",
  "Giro frontal superior.l": "nervous-central",
  "Giro frontal superior.r": "nervous-central",
  "Giro lingual.l": "nervous-central",
  "Giro lingual.r": "nervous-central",
  "Giro occipitotemporal lateral.l": "nervous-central",
  "Giro occipitotemporal lateral.r": "nervous-central",
  "Giro poscentral.l": "nervous-central",
  "Giro poscentral.r": "nervous-central",
  "Giro precentral.l": "nervous-central",
  "Giro precentral.r": "nervous-central",
  "Giro supramarginal.l": "nervous-central",
  "Giro supramarginal.r": "nervous-central",
  "Giro temporal inferior.l": "nervous-central",
  "Giro temporal inferior.r": "nervous-central",
  "Giro temporal medio.l": "nervous-central",
  "Giro temporal medio.r": "nervous-central",
  "Giros occipitales superiores.l": "nervous-central",
  "Giros occipitales superiores.r": "nervous-central",
  "Giros orbitales.l": "nervous-central",
  "Giros orbitales.r": "nervous-central",
  "Giros temporales transversos.l": "nervous-central",
  "Giros temporales transversos.r": "nervous-central",
  "Globo pálido.l": "nervous-central",
  "Globo pálido.r": "nervous-central",
  "Glándula lagrimal.l": "nervous-sense",
  "Glándula lagrimal.r": "nervous-sense",
  "Habénula": "nervous-central",
  "Hipocampo.l": "nervous-central",
  "Hipocampo.r": "nervous-central",
  "Hipotálamo": "nervous-central",
  "Hoz del cerebro": "nervous-central",
  "Inferior occipital gyrus and sulcus*.l": "nervous-central",
  "Inferior occipital gyrus and sulcus*.r": "nervous-central",
  "Insula (Subcentral gyrus and ant. and post. sulci*).l": "nervous-central",
  "Insula (Subcentral gyrus and ant. and post. sulci*).r": "nervous-central",
  "Iris.l": "nervous-sense",
  "Iris.r": "nervous-sense",
  "Lat_Fis-ant-Horizont.l": "nervous-central",
  "Lat_Fis-ant-Horizont.r": "nervous-central",
  "Lat_Fis-ant-Vertical.l": "nervous-central",
  "Lat_Fis-ant-Vertical.r": "nervous-central",
  "Lat_Fis-post.l": "nervous-central",
  "Lat_Fis-post.r": "nervous-central",
  "Lateral occipital gyrus (Middle occipital gyrus*).l": "nervous-central",
  "Lateral occipital gyrus (Middle occipital gyrus*).r": "nervous-central",
  "Lente.l": "nervous-sense",
  "Lente.r": "nervous-sense",
  "Ligamento suspensorio del globo ocular.l": "nervous-sense",
  "Ligamento suspensorio del globo ocular.r": "nervous-sense",
  "Lingula del cerebelo": "nervous-central",
  "Lunate sulcus.l": "nervous-central",
  "Lunate sulcus.r": "nervous-central",
  "Lóbulo biventral.l": "nervous-central",
  "Lóbulo biventral.r": "nervous-central",
  "Lóbulo central": "nervous-central",
  "Lóbulo cuadrangular anterior.l": "nervous-central",
  "Lóbulo cuadrangular anterior.r": "nervous-central",
  "Lóbulo cuadrangular posterior.l": "nervous-central",
  "Lóbulo cuadrangular posterior.r": "nervous-central",
  "Lóbulo grácil.l": "nervous-central",
  "Lóbulo grácil.r": "nervous-central",
  "Lóbulo parietal superior.l": "nervous-central",
  "Lóbulo parietal superior.r": "nervous-central",
  "Lóbulo semilunar inferior.l": "nervous-central",
  "Lóbulo semilunar inferior.r": "nervous-central",
  "Lóbulo semilunar superior.l": "nervous-central",
  "Lóbulo semilunar superior.r": "nervous-central",
  "Materia gris del bulbo raquídeo": "nervous-central",
  "Medial occipitotemporal gyrus (Parahippocampal*).l": "nervous-central",
  "Medial occipitotemporal gyrus (Parahippocampal*).r": "nervous-central",
  "Membrana timpánica.l": "nervous-sense",
  "Membrana timpánica.r": "nervous-sense",
  "Mesencéfalo.l": "nervous-central",
  "Mesencéfalo.r": "nervous-central",
  "Nervio abducens (VI).l": "nervous-peripheral",
  "Nervio abducens (VI).r": "nervous-peripheral",
  "Nervio accesorio (XI).l": "nervous-peripheral",
  "Nervio accesorio (XI).r": "nervous-peripheral",
  "Nervio al músculo milohioideo.l": "nervous-peripheral",
  "Nervio al músculo milohioideo.r": "nervous-peripheral",
  "Nervio alveolar inferior.l": "nervous-peripheral",
  "Nervio alveolar inferior.r": "nervous-peripheral",
  "Nervio axilar.l": "nervous-peripheral",
  "Nervio axilar.r": "nervous-peripheral",
  "Nervio bucal.l": "nervous-peripheral",
  "Nervio bucal.r": "nervous-peripheral",
  "Nervio ciático.l": "nervous-peripheral",
  "Nervio ciático.r": "nervous-peripheral",
  "Nervio coclear": "nervous-peripheral",
  "Nervio coclear.l": "nervous-peripheral",
  "Nervio cutáneo antebraquial lateral.l": "nervous-peripheral",
  "Nervio cutáneo antebraquial lateral.r": "nervous-peripheral",
  "Nervio cutáneo antebraquial medial.l": "nervous-peripheral",
  "Nervio cutáneo antebraquial medial.r": "nervous-peripheral",
  "Nervio cutáneo antebraquial posterior.l": "nervous-peripheral",
  "Nervio cutáneo antebraquial posterior.r": "nervous-peripheral",
  "Nervio cutáneo braquial lateral inferior.l": "nervous-peripheral",
  "Nervio cutáneo braquial lateral inferior.r": "nervous-peripheral",
  "Nervio cutáneo braquial lateroposterior.l": "nervous-peripheral",
  "Nervio cutáneo braquial lateroposterior.r": "nervous-peripheral",
  "Nervio cutáneo braquial medial.l": "nervous-peripheral",
  "Nervio cutáneo braquial medial.r": "nervous-peripheral",
  "Nervio cutáneo dorsal intermedio del pie.l": "nervous-peripheral",
  "Nervio cutáneo dorsal intermedio del pie.r": "nervous-peripheral",
  "Nervio cutáneo dorsal medial del pie.l": "nervous-peripheral",
  "Nervio cutáneo dorsal medial del pie.r": "nervous-peripheral",
  "Nervio cutáneo femoral lateral.l": "nervous-peripheral",
  "Nervio cutáneo femoral lateral.r": "nervous-peripheral",
  "Nervio cutáneo femoral posterior.l": "nervous-peripheral",
  "Nervio cutáneo femoral posterior.r": "nervous-peripheral",
  "Nervio cutáneo sural medial.l": "nervous-peripheral",
  "Nervio cutáneo sural medial.r": "nervous-peripheral",
  "Nervio del músculo cuadrado femoral.l": "nervous-peripheral",
  "Nervio del músculo cuadrado femoral.r": "nervous-peripheral",
  "Nervio del músculo piriforme.l": "nervous-peripheral",
  "Nervio del músculo piriforme.r": "nervous-peripheral",
  "Nervio escapular dorsal.l": "nervous-peripheral",
  "Nervio escapular dorsal.r": "nervous-peripheral",
  "Nervio facial (VII).l": "nervous-peripheral",
  "Nervio facial (VII).r": "nervous-peripheral",
  "Nervio femoral.l": "nervous-peripheral",
  "Nervio femoral.r": "nervous-peripheral",
  "Nervio fibular común.l": "nervous-peripheral",
  "Nervio fibular común.r": "nervous-peripheral",
  "Nervio fibular profundo.l": "nervous-peripheral",
  "Nervio fibular profundo.r": "nervous-peripheral",
  "Nervio fibular superficial.l": "nervous-peripheral",
  "Nervio fibular superficial.r": "nervous-peripheral",
  "Nervio genitofemoral.l": "nervous-peripheral",
  "Nervio genitofemoral.r": "nervous-peripheral",
  "Nervio glosofaríngeo (IX).l": "nervous-peripheral",
  "Nervio glosofaríngeo (IX).r": "nervous-peripheral",
  "Nervio glúteo superior.l": "nervous-peripheral",
  "Nervio glúteo superior.r": "nervous-peripheral",
  "Nervio hipogloso (XII).l": "nervous-peripheral",
  "Nervio hipogloso (XII).r": "nervous-peripheral",
  "Nervio ilio-inguinal.l": "nervous-peripheral",
  "Nervio ilio-inguinal.r": "nervous-peripheral",
  "Nervio iliohipogástrico.l": "nervous-peripheral",
  "Nervio iliohipogástrico.r": "nervous-peripheral",
  "Nervio interóseo anterior del antebrazo.l": "nervous-peripheral",
  "Nervio interóseo anterior del antebrazo.r": "nervous-peripheral",
  "Nervio interóseo posterior del antebrazo.l": "nervous-peripheral",
  "Nervio interóseo posterior del antebrazo.r": "nervous-peripheral",
  "Nervio lingual.l": "nervous-peripheral",
  "Nervio lingual.r": "nervous-peripheral",
  "Nervio maxilar.l": "nervous-peripheral",
  "Nervio maxilar.r": "nervous-peripheral",
  "Nervio mediano.l": "nervous-peripheral",
  "Nervio mediano.r": "nervous-peripheral",
  "Nervio mental.l": "nervous-peripheral",
  "Nervio mental.r": "nervous-peripheral",
  "Nervio musculocutáneo.l": "nervous-peripheral",
  "Nervio musculocutáneo.r": "nervous-peripheral",
  "Nervio obturador.l": "nervous-peripheral",
  "Nervio obturador.r": "nervous-peripheral",
  "Nervio oculomotor (III).l": "nervous-peripheral",
  "Nervio oculomotor (III).r": "nervous-peripheral",
  "Nervio oftálmico.l": "nervous-peripheral",
  "Nervio oftálmico.r": "nervous-peripheral",
  "Nervio olfatorio (I).l": "nervous-peripheral",
  "Nervio olfatorio (I).r": "nervous-peripheral",
  "Nervio pectoral lateral.l": "nervous-peripheral",
  "Nervio pectoral lateral.r": "nervous-peripheral",
  "Nervio pectoral medial.l": "nervous-peripheral",
  "Nervio pectoral medial.r": "nervous-peripheral",
  "Nervio plantar lateral.l": "nervous-peripheral",
  "Nervio plantar lateral.r": "nervous-peripheral",
  "Nervio plantar medial.l": "nervous-peripheral",
  "Nervio plantar medial.r": "nervous-peripheral",
  "Nervio pudendo.l": "nervous-peripheral",
  "Nervio pudendo.r": "nervous-peripheral",
  "Nervio radial.l": "nervous-peripheral",
  "Nervio radial.r": "nervous-peripheral",
  "Nervio safeno.l": "nervous-peripheral",
  "Nervio safeno.r": "nervous-peripheral",
  "Nervio subclavio.l": "nervous-peripheral",
  "Nervio subclavio.r": "nervous-peripheral",
  "Nervio subescapular inferior.l": "nervous-peripheral",
  "Nervio subescapular inferior.r": "nervous-peripheral",
  "Nervio subescapular superior.l": "nervous-peripheral",
  "Nervio subescapular superior.r": "nervous-peripheral",
  "Nervio supraescapular.l": "nervous-peripheral",
  "Nervio supraescapular.r": "nervous-peripheral",
  "Nervio sural.l": "nervous-peripheral",
  "Nervio sural.r": "nervous-peripheral",
  "Nervio tibial.l": "nervous-peripheral",
  "Nervio tibial.r": "nervous-peripheral",
  "Nervio toracodorsal.l": "nervous-peripheral",
  "Nervio toracodorsal.r": "nervous-peripheral",
  "Nervio torácico largo.l": "nervous-peripheral",
  "Nervio torácico largo.r": "nervous-peripheral",
  "Nervio trigémino (V).l": "nervous-peripheral",
  "Nervio trigémino (V).r": "nervous-peripheral",
  "Nervio troclear (IV).l": "nervous-peripheral",
  "Nervio troclear (IV).r": "nervous-peripheral",
  "Nervio ulnar.l": "nervous-peripheral",
  "Nervio ulnar.r": "nervous-peripheral",
  "Nervio vago (X).l": "nervous-peripheral",
  "Nervio vago (X).r": "nervous-peripheral",
  "Nervio vestibular.l": "nervous-peripheral",
  "Nervio vestibular.r": "nervous-peripheral",
  "Nervio vestibulococlear (VIII).l": "nervous-peripheral",
  "Nervio vestibulococlear (VIII).r": "nervous-peripheral",
  "Nervio óptico (II).l": "nervous-peripheral",
  "Nervio óptico (II).r": "nervous-peripheral",
  "Nervios intercostales.l": "nervous-peripheral",
  "Nervios intercostales.r": "nervous-peripheral",
  "Nervios simpáticos.l": "nervous-peripheral",
  "Nervios simpáticos.r": "nervous-peripheral",
  "Nódulo del vermis": "nervous-central",
  "Núcleo accesorio del nervio oculomotor.l": "nervous-central",
  "Núcleo accesorio del nervio oculomotor.r": "nervous-central",
  "Núcleo ambiguo.l": "nervous-central",
  "Núcleo ambiguo.r": "nervous-central",
  "Núcleo caudado.l": "nervous-central",
  "Núcleo caudado.r": "nervous-central",
  "Núcleo coclear anterior.l": "nervous-central",
  "Núcleo coclear anterior.r": "nervous-central",
  "Núcleo coclear posterior.l": "nervous-central",
  "Núcleo coclear posterior.r": "nervous-central",
  "Núcleo del nervio abducens.l": "nervous-central",
  "Núcleo del nervio abducens.r": "nervous-central",
  "Núcleo del nervio accesorio.l": "nervous-central",
  "Núcleo del nervio accesorio.r": "nervous-central",
  "Núcleo del nervio hipogloso.l": "nervous-central",
  "Núcleo del nervio hipogloso.r": "nervous-central",
  "Núcleo del nervio oculomotor.l": "nervous-central",
  "Núcleo del nervio oculomotor.r": "nervous-central",
  "Núcleo del nervio troclear.l": "nervous-central",
  "Núcleo del nervio troclear.r": "nervous-central",
  "Núcleo del tracto solitario.l": "nervous-central",
  "Núcleo del tracto solitario.r": "nervous-central",
  "Núcleo intermediolateral": "nervous-central",
  "Núcleo intermediomedial": "nervous-central",
  "Núcleo lentiforme.l": "nervous-central",
  "Núcleo lentiforme.r": "nervous-central",
  "Núcleo motor del nervio facial.l": "nervous-central",
  "Núcleo motor del nervio facial.r": "nervous-central",
  "Núcleo posterior del nervio vago.l": "nervous-central",
  "Núcleo posterior del nervio vago.r": "nervous-central",
  "Núcleo propio": "nervous-central",
  "Núcleo rojo.l": "nervous-central",
  "Núcleo rojo.r": "nervous-central",
  "Núcleo salival inferior.l": "nervous-central",
  "Núcleo salival inferior.r": "nervous-central",
  "Núcleo salival superior.l": "nervous-central",
  "Núcleo salival superior.r": "nervous-central",
  "Núcleos septales": "nervous-central",
  "Núcleos vestibulares.l": "nervous-central",
  "Núcleos vestibulares.r": "nervous-central",
  "Occipitotemporal sulcus (Lateral part*).l": "nervous-central",
  "Occipitotemporal sulcus (Lateral part*).r": "nervous-central",
  "Oliva.l": "nervous-central",
  "Oliva.r": "nervous-central",
  "Orbital gyri (Frontomarginal gyrus and sulcus*).l": "nervous-central",
  "Orbital gyri (Frontomarginal gyrus and sulcus*).r": "nervous-central",
  "Orbital part of  inferior frontal gyrus.l": "nervous-central",
  "Orbital part of  inferior frontal gyrus.r": "nervous-central",
  "Orbital sulci (H-shaped orbital sulci*).l": "nervous-central",
  "Orbital sulci (H-shaped orbital sulci*).r": "nervous-central",
  "Orbital sulci (Lateral Orbital sulcus*).l": "nervous-central",
  "Orbital sulci (Lateral Orbital sulcus*).r": "nervous-central",
  "Paracentral gyrus and sulcus*.l": "nervous-central",
  "Paracentral gyrus and sulcus*.r": "nervous-central",
  "Parte opercular del giro frontal inferior.l": "nervous-central",
  "Parte opercular del giro frontal inferior.r": "nervous-central",
  "Parte triangular del giro frontal inferior.l": "nervous-central",
  "Parte triangular del giro frontal inferior.r": "nervous-central",
  "Pedúnculo cerebeloso superior.l": "nervous-central",
  "Pedúnculo cerebeloso superior.r": "nervous-central",
  "Pedúnculo del flóculo.l": "nervous-central",
  "Pedúnculo del flóculo.r": "nervous-central",
  "Pirámide del bulbo raquídeo.l": "nervous-central",
  "Pirámide del bulbo raquídeo.r": "nervous-central",
  "Pirámide del vermis": "nervous-central",
  "Plano temporal.l": "nervous-central",
  "Plano temporal.r": "nervous-central",
  "Plexo coroideo.l": "nervous-central",
  "Plexo coroideo.r": "nervous-central",
  "Polo occipital.l": "nervous-central",
  "Polo occipital.r": "nervous-central",
  "Polo temporal.l": "nervous-central",
  "Polo temporal.r": "nervous-central",
  "Precentral sulcus (Superior part)*.l": "nervous-central",
  "Precentral sulcus (Superior part)*.r": "nervous-central",
  "Precentral sulcus (inferior part)*.l": "nervous-central",
  "Precentral sulcus (inferior part)*.r": "nervous-central",
  "Precuneus.l": "nervous-central",
  "Precuneus.r": "nervous-central",
  "Proceso reticular espinal": "nervous-central",
  "Puente troncoencefálico.l": "nervous-central",
  "Puente troncoencefálico.r": "nervous-central",
  "Putamen.l": "nervous-central",
  "Putamen.r": "nervous-central",
  "Quiasma óptico.l": "nervous-central",
  "Quiasma óptico.r": "nervous-central",
  "Rama anterior del nervio cutáneo antebraquial medial.l": "nervous-peripheral",
  "Rama anterior del nervio cutáneo antebraquial medial.r": "nervous-peripheral",
  "Rama anterior del nervio obturador.l": "nervous-peripheral",
  "Rama anterior del nervio obturador.r": "nervous-peripheral",
  "Rama dorsal del nervio ulnar.l": "nervous-peripheral",
  "Rama dorsal del nervio ulnar.r": "nervous-peripheral",
  "Rama femoral del nervio genitofemoral.l": "nervous-peripheral",
  "Rama femoral del nervio genitofemoral.r": "nervous-peripheral",
  "Rama genital del nervio genitofemoral.l": "nervous-peripheral",
  "Rama genital del nervio genitofemoral.r": "nervous-peripheral",
  "Rama infrapatelar del nervio safeno.l": "nervous-peripheral",
  "Rama infrapatelar del nervio safeno.r": "nervous-peripheral",
  "Rama meníngea del nervio maxilar.l": "nervous-peripheral",
  "Rama meníngea del nervio maxilar.r": "nervous-peripheral",
  "Rama palmar del nervio mediano.l": "nervous-peripheral",
  "Rama palmar del nervio mediano.r": "nervous-peripheral",
  "Rama palmar del nervio ulnar.l": "nervous-peripheral",
  "Rama palmar del nervio ulnar.r": "nervous-peripheral",
  "Rama posterior del nervio cutáneo antebraquial medial.l": "nervous-peripheral",
  "Rama posterior del nervio cutáneo antebraquial medial.r": "nervous-peripheral",
  "Rama posterior del nervio obturador.l": "nervous-peripheral",
  "Rama posterior del nervio obturador.r": "nervous-peripheral",
  "Rama profunda del nervio radial.l": "nervous-peripheral",
  "Rama profunda del nervio radial.r": "nervous-peripheral",
  "Rama profunda del nervio ulnar.l": "nervous-peripheral",
  "Rama profunda del nervio ulnar.r": "nervous-peripheral",
  "Rama superficial del nervio radial.l": "nervous-peripheral",
  "Rama superficial del nervio radial.r": "nervous-peripheral",
  "Rama superficial del nervio ulnar.l": "nervous-peripheral",
  "Rama superficial del nervio ulnar.r": "nervous-peripheral",
  "Rama sural comunicante del nervio fibular común.l": "nervous-peripheral",
  "Rama sural comunicante del nervio fibular común.r": "nervous-peripheral",
  "Ramas cutáneas anteriores del nervio femoral.l": "nervous-peripheral",
  "Ramas cutáneas anteriores del nervio femoral.r": "nervous-peripheral",
  "Ramas cutáneas crurales mediales del nervio safeno.l": "nervous-peripheral",
  "Ramas cutáneas crurales mediales del nervio safeno.r": "nervous-peripheral",
  "Ramas digitales dorsales del nervio fibular profundo.l": "nervous-peripheral",
  "Ramas digitales dorsales del nervio fibular profundo.r": "nervous-peripheral",
  "Ramas digitales dorsales del nervio fibularo superficial.l": "nervous-peripheral",
  "Ramas digitales dorsales del nervio fibularo superficial.r": "nervous-peripheral",
  "Ramas digitales dorsales del nervio radial.l": "nervous-peripheral",
  "Ramas digitales dorsales del nervio radial.r": "nervous-peripheral",
  "Ramas digitales dorsales del nervio ulnar.l": "nervous-peripheral",
  "Ramas digitales dorsales del nervio ulnar.r": "nervous-peripheral",
  "Ramas digitales palmares comunes del nervio mediano.l": "nervous-peripheral",
  "Ramas digitales palmares comunes del nervio mediano.r": "nervous-peripheral",
  "Ramas digitales palmares comunes del nervio ulnar.l": "nervous-peripheral",
  "Ramas digitales palmares comunes del nervio ulnar.r": "nervous-peripheral",
  "Ramas digitales palmares propias del nervio mediano.l": "nervous-peripheral",
  "Ramas digitales palmares propias del nervio mediano.r": "nervous-peripheral",
  "Ramas digitales palmares propias del nervio ulnar.l": "nervous-peripheral",
  "Ramas digitales palmares propias del nervio ulnar.r": "nervous-peripheral",
  "Ramas digitales plantares comunes del nervio plantar lateral.l": "nervous-peripheral",
  "Ramas digitales plantares comunes del nervio plantar lateral.r": "nervous-peripheral",
  "Ramas digitales plantares comunes del nervio plantar medial": "nervous-peripheral",
  "Ramas digitales plantares comunes del nervio plantar medial.l": "nervous-peripheral",
  "Ramas digitales plantares propias del nervio plantar lateral.l": "nervous-peripheral",
  "Ramas digitales plantares propias del nervio plantar lateral.r": "nervous-peripheral",
  "Ramas digitales plantares propias del nervio plantar medial.l": "nervous-peripheral",
  "Ramas digitales plantares propias del nervio plantar medial.r": "nervous-peripheral",
  "Ramas musculares del nervio axilar.l": "nervous-peripheral",
  "Ramas musculares del nervio axilar.r": "nervous-peripheral",
  "Ramas musculares del nervio fibular profundo.l": "nervous-peripheral",
  "Ramas musculares del nervio fibular profundo.r": "nervous-peripheral",
  "Ramas musculares del nervio mediano.l": "nervous-peripheral",
  "Ramas musculares del nervio mediano.r": "nervous-peripheral",
  "Ramas musculares del nervio radial.l": "nervous-peripheral",
  "Ramas musculares del nervio radial.r": "nervous-peripheral",
  "Ramas musculares del nervio ulnar.l": "nervous-peripheral",
  "Ramas musculares del nervio ulnar.r": "nervous-peripheral",
  "Raíces del plexo braquial.l": "nervous-peripheral",
  "Raíces del plexo braquial.r": "nervous-peripheral",
  "Raíz anterior del nervio cutáneo femoral posterior.l": "nervous-peripheral",
  "Raíz anterior del nervio cutáneo femoral posterior.r": "nervous-peripheral",
  "Raíz anterior del nervio espinal.l": "nervous-peripheral",
  "Raíz anterior del nervio espinal.r": "nervous-peripheral",
  "Raíz motora del nervio trigémino.l": "nervous-peripheral",
  "Raíz motora del nervio trigémino.r": "nervous-peripheral",
  "Raíz posterior del nervio cutáneo femoral posterior.l": "nervous-peripheral",
  "Raíz posterior del nervio cutáneo femoral posterior.r": "nervous-peripheral",
  "Raíz posterior del nervio espinal.l": "nervous-peripheral",
  "Raíz posterior del nervio espinal.r": "nervous-peripheral",
  "Raíz sensorial del nervio trigémino.l": "nervous-peripheral",
  "Raíz sensorial del nervio trigémino.r": "nervous-peripheral",
  "Retina.l": "nervous-sense",
  "Retina.r": "nervous-sense",
  "Saco lagrimal.l": "nervous-sense",
  "Saco lagrimal.r": "nervous-sense",
  "Segmento anterior del globo ocular.l": "nervous-sense",
  "Segmento anterior del globo ocular.r": "nervous-sense",
  "Segmento posterior del globo ocular.l": "nervous-sense",
  "Segmento posterior del globo ocular.r": "nervous-sense",
  "Septum pellucidum": "nervous-central",
  "Straight gyrus (Gyrus rectus).l": "nervous-central",
  "Straight gyrus (Gyrus rectus).r": "nervous-central",
  "Stria terminalis.l": "nervous-central",
  "Stria terminalis.r": "nervous-central",
  "Sulcus interm_prim-Jensen.l": "nervous-central",
  "Sulcus interm_prim-Jensen.r": "nervous-central",
  "Superior temporal gyrus (Lateral part).l": "nervous-central",
  "Superior temporal gyrus (Lateral part).r": "nervous-central",
  "Surco calcarino.l": "nervous-central",
  "Surco calcarino.r": "nervous-central",
  "Surco central.l": "nervous-central",
  "Surco central.r": "nervous-central",
  "Surco circular de la ínsula.l": "nervous-central",
  "Surco circular de la ínsula.r": "nervous-central",
  "Surco colateral.l": "nervous-central",
  "Surco colateral.r": "nervous-central",
  "Surco frontal inferior.l": "nervous-central",
  "Surco frontal inferior.r": "nervous-central",
  "Surco frontal superior.l": "nervous-central",
  "Surco frontal superior.r": "nervous-central",
  "Surco intraparietal.l": "nervous-central",
  "Surco intraparietal.r": "nervous-central",
  "Surco occipital transversal.l": "nervous-central",
  "Surco occipital transversal.r": "nervous-central",
  "Surco olfatorio.l": "nervous-central",
  "Surco olfatorio.r": "nervous-central",
  "Surco paracentral.l": "nervous-central",
  "Surco paracentral.r": "nervous-central",
  "Surco parieto-occipital.l": "nervous-central",
  "Surco parieto-occipital.r": "nervous-central",
  "Surco poscentral.l": "nervous-central",
  "Surco poscentral.r": "nervous-central",
  "Surco subparietal.l": "nervous-central",
  "Surco subparietal.r": "nervous-central",
  "Surco temporal inferior.l": "nervous-central",
  "Surco temporal inferior.r": "nervous-central",
  "Surco temporal superior.l": "nervous-central",
  "Surco temporal superior.r": "nervous-central",
  "Sustancia blanca de la médula espinal": "nervous-central",
  "Sustancia blanca del telencéfalo.l": "nervous-central",
  "Sustancia blanca del telencéfalo.r": "nervous-central",
  "Sustancia intermedia lateral": "nervous-central",
  "Tercer ventrículo": "nervous-central",
  "Tienda del cerebello.l": "nervous-central",
  "Tienda del cerebello.r": "nervous-central",
  "Tracto corticoespinal anterior": "nervous-central",
  "Tracto corticoespinal lateral": "nervous-central",
  "Tracto espinocerebeloso anterior": "nervous-central",
  "Tracto espinocerebeloso posterior": "nervous-central",
  "Tracto espinotalámico anterior": "nervous-central",
  "Tracto espinotalámico lateral": "nervous-central",
  "Tracto posterolateral": "nervous-central",
  "Tracto reticuloespinal lateral": "nervous-central",
  "Tracto reticuloespinal medial": "nervous-central",
  "Tracto rubroespinal": "nervous-central",
  "Tracto spinotectal": "nervous-central",
  "Tracto tectoespinal": "nervous-central",
  "Tracto vestibuloespinal lateral": "nervous-central",
  "Tracto vestibuloespinal medial": "nervous-central",
  "Tracto óptico.l": "nervous-central",
  "Tracto óptico.r": "nervous-central",
  "Transverse frontopolar gyrus and sulcus*.l": "nervous-central",
  "Transverse frontopolar gyrus and sulcus*.r": "nervous-central",
  "Tronco inferior del plexo braquial.l": "nervous-peripheral",
  "Tronco inferior del plexo braquial.r": "nervous-peripheral",
  "Tronco medio del plexo braquial.l": "nervous-peripheral",
  "Tronco medio del plexo braquial.r": "nervous-peripheral",
  "Tronco simpático.l": "nervous-peripheral",
  "Tronco simpático.r": "nervous-peripheral",
  "Tronco superior del plexo braquial.l": "nervous-peripheral",
  "Tronco superior del plexo braquial.r": "nervous-peripheral",
  "Tubo auditivo.l": "nervous-sense",
  "Tubo auditivo.r": "nervous-sense",
  "Tubérculo del vermis": "nervous-central",
  "Tálamo.l": "nervous-central",
  "Tálamo.r": "nervous-central",
  "Ventrículo lateral.l": "nervous-central",
  "Ventrículo lateral.r": "nervous-central",
  "Vestíbulo.l": "nervous-sense",
  "Vestíbulo.r": "nervous-sense",
  "Úvula del vermis": "nervous-central",
} as const satisfies Readonly<Record<string, AnatomyDivisionId>>;
