/** IDs persistentes explícitos para mallas nerviosas sin identidad educativa. */
export const nervousModelNodeStableIdByOriginalName = {
  " Posterior transverse collateral sulcus.l": "nervous.model-node-0001",
  " Posterior transverse collateral sulcus.r": "nervous.model-node-0002",
  "(Rama comunicante del nervio mediano con el nervio ulnar).l": "nervous.model-node-0003",
  "(Rama comunicante del nervio mediano con el nervio ulnar).r": "nervous.model-node-0004",
  "Ampulla del canalículo lacrimal.l": "nervous.model-node-0005",
  "Ampulla del canalículo lacrimal.r": "nervous.model-node-0006",
  "Anterior occipital sulcus*.l": "nervous.model-node-0007",
  "Anterior occipital sulcus*.r": "nervous.model-node-0008",
  "Base del pedúnculo.l": "nervous.model-node-0009",
  "Base del pedúnculo.r": "nervous.model-node-0010",
  "Canal central": "nervous.model-node-0011",
  "Canal central.001": "nervous.model-node-0012",
  "Canalículo lagrimal.l": "nervous.model-node-0013",
  "Canalículo lagrimal.r": "nervous.model-node-0014",
  "Cingulate gyrus (Posteroventral part*).l": "nervous.model-node-0015",
  "Cingulate gyrus (Posteroventral part*).r": "nervous.model-node-0016",
  "Cingulate gyrus and sulcus (Middle anterior part).l": "nervous.model-node-0017",
  "Cingulate gyrus and sulcus (Middle anterior part).r": "nervous.model-node-0018",
  "Cingulate gyrus and sulcus (Middle posterior part).l": "nervous.model-node-0019",
  "Cingulate gyrus and sulcus (Middle posterior part).r": "nervous.model-node-0020",
  "Cingulate gyrus and sulcus (Posterior dorsal part).l": "nervous.model-node-0021",
  "Cingulate gyrus and sulcus (Posterior dorsal part).r": "nervous.model-node-0022",
  "Cingulate sulcus (Marginal part*).l": "nervous.model-node-0023",
  "Cingulate sulcus (Marginal part*).r": "nervous.model-node-0024",
  "Comisura hipocampal": "nervous.model-node-0025",
  "Comisura posterior": "nervous.model-node-0026",
  "Cuerda del tímpano.l": "nervous.model-node-0027",
  "Cuerda del tímpano.r": "nervous.model-node-0028",
  "Cuneus.l": "nervous.model-node-0029",
  "Cuneus.r": "nervous.model-node-0030",
  "División anterior del nervio mandibular.l": "nervous.model-node-0031",
  "División anterior del nervio mandibular.r": "nervous.model-node-0032",
  "División anterior del tronco inferior del plexo braquial.l": "nervous.model-node-0033",
  "División anterior del tronco inferior del plexo braquial.r": "nervous.model-node-0034",
  "División anterior del tronco medio del plexo braquial.l": "nervous.model-node-0035",
  "División anterior del tronco medio del plexo braquial.r": "nervous.model-node-0036",
  "División anterior del tronco superior del plexo braquial.l": "nervous.model-node-0037",
  "División anterior del tronco superior del plexo braquial.r": "nervous.model-node-0038",
  "División posterior del nervio mandibular.l": "nervous.model-node-0039",
  "División posterior del nervio mandibular.r": "nervous.model-node-0040",
  "División posterior del tronco inferior del plexo braquial.l": "nervous.model-node-0041",
  "División posterior del tronco inferior del plexo braquial.r": "nervous.model-node-0042",
  "División posterior del tronco medio del plexo braquial.l": "nervous.model-node-0043",
  "División posterior del tronco medio del plexo braquial.r": "nervous.model-node-0044",
  "División posterior del tronco superior del plexo braquial.l": "nervous.model-node-0045",
  "División posterior del tronco superior del plexo braquial.r": "nervous.model-node-0046",
  "Dura espinal": "nervous.model-node-0047",
  "Estrías talámicas medulares.l": "nervous.model-node-0048",
  "Estrías talámicas medulares.r": "nervous.model-node-0049",
  "Fascículo anterior propio": "nervous.model-node-0050",
  "Fascículo lateral propio": "nervous.model-node-0051",
  "Fascículo posterior propio": "nervous.model-node-0052",
  "Fosa interpeduncular.l": "nervous.model-node-0053",
  "Fosa interpeduncular.r": "nervous.model-node-0054",
  "Giro occipitotemporal lateral.l": "nervous.model-node-0055",
  "Giro occipitotemporal lateral.r": "nervous.model-node-0056",
  "Giros orbitales.l": "nervous.model-node-0057",
  "Giros orbitales.r": "nervous.model-node-0058",
  "Habénula": "nervous.model-node-0059",
  "Hoz del cerebro": "nervous.model-node-0060",
  "Inferior occipital gyrus and sulcus*.l": "nervous.model-node-0061",
  "Inferior occipital gyrus and sulcus*.r": "nervous.model-node-0062",
  "Insula (Subcentral gyrus and ant. and post. sulci*).l": "nervous.model-node-0063",
  "Insula (Subcentral gyrus and ant. and post. sulci*).r": "nervous.model-node-0064",
  "Lat_Fis-ant-Horizont.l": "nervous.model-node-0065",
  "Lat_Fis-ant-Horizont.r": "nervous.model-node-0066",
  "Lat_Fis-ant-Vertical.l": "nervous.model-node-0067",
  "Lat_Fis-ant-Vertical.r": "nervous.model-node-0068",
  "Lat_Fis-post.l": "nervous.model-node-0069",
  "Lat_Fis-post.r": "nervous.model-node-0070",
  "Lateral occipital gyrus (Middle occipital gyrus*).l": "nervous.model-node-0071",
  "Lateral occipital gyrus (Middle occipital gyrus*).r": "nervous.model-node-0072",
  "Ligamento suspensorio del globo ocular.l": "nervous.model-node-0073",
  "Ligamento suspensorio del globo ocular.r": "nervous.model-node-0074",
  "Lunate sulcus.l": "nervous.model-node-0075",
  "Lunate sulcus.r": "nervous.model-node-0076",
  "Materia gris del bulbo raquídeo": "nervous.model-node-0077",
  "Medial occipitotemporal gyrus (Parahippocampal*).l": "nervous.model-node-0078",
  "Medial occipitotemporal gyrus (Parahippocampal*).r": "nervous.model-node-0079",
  "Nervio al músculo milohioideo.l": "nervous.model-node-0080",
  "Nervio al músculo milohioideo.r": "nervous.model-node-0081",
  "Nervio alveolar inferior.l": "nervous.model-node-0082",
  "Nervio alveolar inferior.r": "nervous.model-node-0083",
  "Nervio bucal.l": "nervous.model-node-0084",
  "Nervio bucal.r": "nervous.model-node-0085",
  "Nervio coclear": "nervous.model-node-0086",
  "Nervio coclear.l": "nervous.model-node-0087",
  "Nervio cutáneo antebraquial lateral.l": "nervous.model-node-0088",
  "Nervio cutáneo antebraquial lateral.r": "nervous.model-node-0089",
  "Nervio cutáneo antebraquial medial.l": "nervous.model-node-0090",
  "Nervio cutáneo antebraquial medial.r": "nervous.model-node-0091",
  "Nervio cutáneo antebraquial posterior.l": "nervous.model-node-0092",
  "Nervio cutáneo antebraquial posterior.r": "nervous.model-node-0093",
  "Nervio cutáneo braquial lateral inferior.l": "nervous.model-node-0094",
  "Nervio cutáneo braquial lateral inferior.r": "nervous.model-node-0095",
  "Nervio cutáneo braquial lateroposterior.l": "nervous.model-node-0096",
  "Nervio cutáneo braquial lateroposterior.r": "nervous.model-node-0097",
  "Nervio cutáneo braquial medial.l": "nervous.model-node-0098",
  "Nervio cutáneo braquial medial.r": "nervous.model-node-0099",
  "Nervio cutáneo dorsal intermedio del pie.l": "nervous.model-node-0100",
  "Nervio cutáneo dorsal intermedio del pie.r": "nervous.model-node-0101",
  "Nervio cutáneo dorsal medial del pie.l": "nervous.model-node-0102",
  "Nervio cutáneo dorsal medial del pie.r": "nervous.model-node-0103",
  "Nervio cutáneo femoral posterior.l": "nervous.model-node-0104",
  "Nervio cutáneo femoral posterior.r": "nervous.model-node-0105",
  "Nervio cutáneo sural medial.l": "nervous.model-node-0106",
  "Nervio cutáneo sural medial.r": "nervous.model-node-0107",
  "Nervio del músculo cuadrado femoral.l": "nervous.model-node-0108",
  "Nervio del músculo cuadrado femoral.r": "nervous.model-node-0109",
  "Nervio del músculo piriforme.l": "nervous.model-node-0110",
  "Nervio del músculo piriforme.r": "nervous.model-node-0111",
  "Nervio escapular dorsal.l": "nervous.model-node-0112",
  "Nervio escapular dorsal.r": "nervous.model-node-0113",
  "Nervio ilio-inguinal.l": "nervous.model-node-0114",
  "Nervio ilio-inguinal.r": "nervous.model-node-0115",
  "Nervio iliohipogástrico.l": "nervous.model-node-0116",
  "Nervio iliohipogástrico.r": "nervous.model-node-0117",
  "Nervio interóseo anterior del antebrazo.l": "nervous.model-node-0118",
  "Nervio interóseo anterior del antebrazo.r": "nervous.model-node-0119",
  "Nervio interóseo posterior del antebrazo.l": "nervous.model-node-0120",
  "Nervio interóseo posterior del antebrazo.r": "nervous.model-node-0121",
  "Nervio mental.l": "nervous.model-node-0122",
  "Nervio mental.r": "nervous.model-node-0123",
  "Nervio pectoral lateral.l": "nervous.model-node-0124",
  "Nervio pectoral lateral.r": "nervous.model-node-0125",
  "Nervio pectoral medial.l": "nervous.model-node-0126",
  "Nervio pectoral medial.r": "nervous.model-node-0127",
  "Nervio subclavio.l": "nervous.model-node-0128",
  "Nervio subclavio.r": "nervous.model-node-0129",
  "Nervio subescapular inferior.l": "nervous.model-node-0130",
  "Nervio subescapular inferior.r": "nervous.model-node-0131",
  "Nervio subescapular superior.l": "nervous.model-node-0132",
  "Nervio subescapular superior.r": "nervous.model-node-0133",
  "Nervio toracodorsal.l": "nervous.model-node-0134",
  "Nervio toracodorsal.r": "nervous.model-node-0135",
  "Nervio vestibular.l": "nervous.model-node-0136",
  "Nervio vestibular.r": "nervous.model-node-0137",
  "Núcleo accesorio del nervio oculomotor.l": "nervous.model-node-0138",
  "Núcleo accesorio del nervio oculomotor.r": "nervous.model-node-0139",
  "Núcleo coclear anterior.l": "nervous.model-node-0140",
  "Núcleo coclear anterior.r": "nervous.model-node-0141",
  "Núcleo coclear posterior.l": "nervous.model-node-0142",
  "Núcleo coclear posterior.r": "nervous.model-node-0143",
  "Núcleo del nervio abducens.l": "nervous.model-node-0144",
  "Núcleo del nervio abducens.r": "nervous.model-node-0145",
  "Núcleo del nervio accesorio.l": "nervous.model-node-0146",
  "Núcleo del nervio accesorio.r": "nervous.model-node-0147",
  "Núcleo del nervio hipogloso.l": "nervous.model-node-0148",
  "Núcleo del nervio hipogloso.r": "nervous.model-node-0149",
  "Núcleo del nervio oculomotor.l": "nervous.model-node-0150",
  "Núcleo del nervio oculomotor.r": "nervous.model-node-0151",
  "Núcleo del nervio troclear.l": "nervous.model-node-0152",
  "Núcleo del nervio troclear.r": "nervous.model-node-0153",
  "Núcleo intermediomedial": "nervous.model-node-0154",
  "Núcleo lentiforme.l": "nervous.model-node-0155",
  "Núcleo lentiforme.r": "nervous.model-node-0156",
  "Núcleo motor del nervio facial.l": "nervous.model-node-0157",
  "Núcleo motor del nervio facial.r": "nervous.model-node-0158",
  "Núcleo posterior del nervio vago.l": "nervous.model-node-0159",
  "Núcleo posterior del nervio vago.r": "nervous.model-node-0160",
  "Núcleo propio": "nervous.model-node-0161",
  "Núcleo salival inferior.l": "nervous.model-node-0162",
  "Núcleo salival inferior.r": "nervous.model-node-0163",
  "Núcleo salival superior.l": "nervous.model-node-0164",
  "Núcleo salival superior.r": "nervous.model-node-0165",
  "Núcleos septales": "nervous.model-node-0166",
  "Occipitotemporal sulcus (Lateral part*).l": "nervous.model-node-0167",
  "Occipitotemporal sulcus (Lateral part*).r": "nervous.model-node-0168",
  "Orbital gyri (Frontomarginal gyrus and sulcus*).l": "nervous.model-node-0169",
  "Orbital gyri (Frontomarginal gyrus and sulcus*).r": "nervous.model-node-0170",
  "Orbital part of  inferior frontal gyrus.l": "nervous.model-node-0171",
  "Orbital part of  inferior frontal gyrus.r": "nervous.model-node-0172",
  "Orbital sulci (H-shaped orbital sulci*).l": "nervous.model-node-0173",
  "Orbital sulci (H-shaped orbital sulci*).r": "nervous.model-node-0174",
  "Orbital sulci (Lateral Orbital sulcus*).l": "nervous.model-node-0175",
  "Orbital sulci (Lateral Orbital sulcus*).r": "nervous.model-node-0176",
  "Paracentral gyrus and sulcus*.l": "nervous.model-node-0177",
  "Paracentral gyrus and sulcus*.r": "nervous.model-node-0178",
  "Parte opercular del giro frontal inferior.l": "nervous.model-node-0179",
  "Parte opercular del giro frontal inferior.r": "nervous.model-node-0180",
  "Parte triangular del giro frontal inferior.l": "nervous.model-node-0181",
  "Parte triangular del giro frontal inferior.r": "nervous.model-node-0182",
  "Pedúnculo del flóculo.l": "nervous.model-node-0183",
  "Pedúnculo del flóculo.r": "nervous.model-node-0184",
  "Plano temporal.l": "nervous.model-node-0185",
  "Plano temporal.r": "nervous.model-node-0186",
  "Polo temporal.l": "nervous.model-node-0187",
  "Polo temporal.r": "nervous.model-node-0188",
  "Precentral sulcus (Superior part)*.l": "nervous.model-node-0189",
  "Precentral sulcus (Superior part)*.r": "nervous.model-node-0190",
  "Precentral sulcus (inferior part)*.l": "nervous.model-node-0191",
  "Precentral sulcus (inferior part)*.r": "nervous.model-node-0192",
  "Proceso reticular espinal": "nervous.model-node-0193",
  "Rama anterior del nervio cutáneo antebraquial medial.l": "nervous.model-node-0194",
  "Rama anterior del nervio cutáneo antebraquial medial.r": "nervous.model-node-0195",
  "Rama anterior del nervio obturador.l": "nervous.model-node-0196",
  "Rama anterior del nervio obturador.r": "nervous.model-node-0197",
  "Rama dorsal del nervio ulnar.l": "nervous.model-node-0198",
  "Rama dorsal del nervio ulnar.r": "nervous.model-node-0199",
  "Rama femoral del nervio genitofemoral.l": "nervous.model-node-0200",
  "Rama femoral del nervio genitofemoral.r": "nervous.model-node-0201",
  "Rama genital del nervio genitofemoral.l": "nervous.model-node-0202",
  "Rama genital del nervio genitofemoral.r": "nervous.model-node-0203",
  "Rama infrapatelar del nervio safeno.l": "nervous.model-node-0204",
  "Rama infrapatelar del nervio safeno.r": "nervous.model-node-0205",
  "Rama meníngea del nervio maxilar.l": "nervous.model-node-0206",
  "Rama meníngea del nervio maxilar.r": "nervous.model-node-0207",
  "Rama palmar del nervio mediano.l": "nervous.model-node-0208",
  "Rama palmar del nervio mediano.r": "nervous.model-node-0209",
  "Rama palmar del nervio ulnar.l": "nervous.model-node-0210",
  "Rama palmar del nervio ulnar.r": "nervous.model-node-0211",
  "Rama posterior del nervio cutáneo antebraquial medial.l": "nervous.model-node-0212",
  "Rama posterior del nervio cutáneo antebraquial medial.r": "nervous.model-node-0213",
  "Rama posterior del nervio obturador.l": "nervous.model-node-0214",
  "Rama posterior del nervio obturador.r": "nervous.model-node-0215",
  "Rama profunda del nervio radial.l": "nervous.model-node-0216",
  "Rama profunda del nervio radial.r": "nervous.model-node-0217",
  "Rama profunda del nervio ulnar.l": "nervous.model-node-0218",
  "Rama profunda del nervio ulnar.r": "nervous.model-node-0219",
  "Rama superficial del nervio radial.l": "nervous.model-node-0220",
  "Rama superficial del nervio radial.r": "nervous.model-node-0221",
  "Rama superficial del nervio ulnar.l": "nervous.model-node-0222",
  "Rama superficial del nervio ulnar.r": "nervous.model-node-0223",
  "Rama sural comunicante del nervio fibular común.l": "nervous.model-node-0224",
  "Rama sural comunicante del nervio fibular común.r": "nervous.model-node-0225",
  "Ramas cutáneas anteriores del nervio femoral.l": "nervous.model-node-0226",
  "Ramas cutáneas anteriores del nervio femoral.r": "nervous.model-node-0227",
  "Ramas cutáneas crurales mediales del nervio safeno.l": "nervous.model-node-0228",
  "Ramas cutáneas crurales mediales del nervio safeno.r": "nervous.model-node-0229",
  "Ramas digitales dorsales del nervio fibular profundo.l": "nervous.model-node-0230",
  "Ramas digitales dorsales del nervio fibular profundo.r": "nervous.model-node-0231",
  "Ramas digitales dorsales del nervio fibularo superficial.l": "nervous.model-node-0232",
  "Ramas digitales dorsales del nervio fibularo superficial.r": "nervous.model-node-0233",
  "Ramas digitales dorsales del nervio radial.l": "nervous.model-node-0234",
  "Ramas digitales dorsales del nervio radial.r": "nervous.model-node-0235",
  "Ramas digitales dorsales del nervio ulnar.l": "nervous.model-node-0236",
  "Ramas digitales dorsales del nervio ulnar.r": "nervous.model-node-0237",
  "Ramas digitales palmares comunes del nervio mediano.l": "nervous.model-node-0238",
  "Ramas digitales palmares comunes del nervio mediano.r": "nervous.model-node-0239",
  "Ramas digitales palmares comunes del nervio ulnar.l": "nervous.model-node-0240",
  "Ramas digitales palmares comunes del nervio ulnar.r": "nervous.model-node-0241",
  "Ramas digitales palmares propias del nervio mediano.l": "nervous.model-node-0242",
  "Ramas digitales palmares propias del nervio mediano.r": "nervous.model-node-0243",
  "Ramas digitales palmares propias del nervio ulnar.l": "nervous.model-node-0244",
  "Ramas digitales palmares propias del nervio ulnar.r": "nervous.model-node-0245",
  "Ramas digitales plantares comunes del nervio plantar lateral.l": "nervous.model-node-0246",
  "Ramas digitales plantares comunes del nervio plantar lateral.r": "nervous.model-node-0247",
  "Ramas digitales plantares comunes del nervio plantar medial": "nervous.model-node-0248",
  "Ramas digitales plantares comunes del nervio plantar medial.l": "nervous.model-node-0249",
  "Ramas digitales plantares propias del nervio plantar lateral.l": "nervous.model-node-0250",
  "Ramas digitales plantares propias del nervio plantar lateral.r": "nervous.model-node-0251",
  "Ramas digitales plantares propias del nervio plantar medial.l": "nervous.model-node-0252",
  "Ramas digitales plantares propias del nervio plantar medial.r": "nervous.model-node-0253",
  "Ramas musculares del nervio axilar.l": "nervous.model-node-0254",
  "Ramas musculares del nervio axilar.r": "nervous.model-node-0255",
  "Ramas musculares del nervio fibular profundo.l": "nervous.model-node-0256",
  "Ramas musculares del nervio fibular profundo.r": "nervous.model-node-0257",
  "Ramas musculares del nervio mediano.l": "nervous.model-node-0258",
  "Ramas musculares del nervio mediano.r": "nervous.model-node-0259",
  "Ramas musculares del nervio radial.l": "nervous.model-node-0260",
  "Ramas musculares del nervio radial.r": "nervous.model-node-0261",
  "Ramas musculares del nervio ulnar.l": "nervous.model-node-0262",
  "Ramas musculares del nervio ulnar.r": "nervous.model-node-0263",
  "Raíz anterior del nervio cutáneo femoral posterior.l": "nervous.model-node-0264",
  "Raíz anterior del nervio cutáneo femoral posterior.r": "nervous.model-node-0265",
  "Raíz motora del nervio trigémino.l": "nervous.model-node-0266",
  "Raíz motora del nervio trigémino.r": "nervous.model-node-0267",
  "Raíz posterior del nervio cutáneo femoral posterior.l": "nervous.model-node-0268",
  "Raíz posterior del nervio cutáneo femoral posterior.r": "nervous.model-node-0269",
  "Raíz sensorial del nervio trigémino.l": "nervous.model-node-0270",
  "Raíz sensorial del nervio trigémino.r": "nervous.model-node-0271",
  "Segmento anterior del globo ocular.l": "nervous.model-node-0272",
  "Segmento anterior del globo ocular.r": "nervous.model-node-0273",
  "Segmento posterior del globo ocular.l": "nervous.model-node-0274",
  "Segmento posterior del globo ocular.r": "nervous.model-node-0275",
  "Septum pellucidum": "nervous.model-node-0276",
  "Straight gyrus (Gyrus rectus).l": "nervous.model-node-0277",
  "Straight gyrus (Gyrus rectus).r": "nervous.model-node-0278",
  "Stria terminalis.l": "nervous.model-node-0279",
  "Stria terminalis.r": "nervous.model-node-0280",
  "Sulcus interm_prim-Jensen.l": "nervous.model-node-0281",
  "Sulcus interm_prim-Jensen.r": "nervous.model-node-0282",
  "Surco circular de la ínsula.l": "nervous.model-node-0283",
  "Surco circular de la ínsula.r": "nervous.model-node-0284",
  "Surco colateral.l": "nervous.model-node-0285",
  "Surco colateral.r": "nervous.model-node-0286",
  "Surco frontal inferior.l": "nervous.model-node-0287",
  "Surco frontal inferior.r": "nervous.model-node-0288",
  "Surco frontal superior.l": "nervous.model-node-0289",
  "Surco frontal superior.r": "nervous.model-node-0290",
  "Surco occipital transversal.l": "nervous.model-node-0291",
  "Surco occipital transversal.r": "nervous.model-node-0292",
  "Surco olfatorio.l": "nervous.model-node-0293",
  "Surco olfatorio.r": "nervous.model-node-0294",
  "Surco paracentral.l": "nervous.model-node-0295",
  "Surco paracentral.r": "nervous.model-node-0296",
  "Surco parieto-occipital.l": "nervous.model-node-0297",
  "Surco parieto-occipital.r": "nervous.model-node-0298",
  "Surco poscentral.l": "nervous.model-node-0299",
  "Surco poscentral.r": "nervous.model-node-0300",
  "Surco subparietal.l": "nervous.model-node-0301",
  "Surco subparietal.r": "nervous.model-node-0302",
  "Surco temporal inferior.l": "nervous.model-node-0303",
  "Surco temporal inferior.r": "nervous.model-node-0304",
  "Surco temporal superior.l": "nervous.model-node-0305",
  "Surco temporal superior.r": "nervous.model-node-0306",
  "Sustancia intermedia lateral": "nervous.model-node-0307",
  "Tracto corticoespinal anterior": "nervous.model-node-0308",
  "Tracto espinotalámico anterior": "nervous.model-node-0309",
  "Tracto posterolateral": "nervous.model-node-0310",
  "Tracto reticuloespinal lateral": "nervous.model-node-0311",
  "Tracto reticuloespinal medial": "nervous.model-node-0312",
  "Tracto rubroespinal": "nervous.model-node-0313",
  "Tracto spinotectal": "nervous.model-node-0314",
  "Tracto tectoespinal": "nervous.model-node-0315",
  "Tracto vestibuloespinal lateral": "nervous.model-node-0316",
  "Tracto vestibuloespinal medial": "nervous.model-node-0317",
  "Transverse frontopolar gyrus and sulcus*.l": "nervous.model-node-0318",
  "Transverse frontopolar gyrus and sulcus*.r": "nervous.model-node-0319",
  "Tronco inferior del plexo braquial.l": "nervous.model-node-0320",
  "Tronco inferior del plexo braquial.r": "nervous.model-node-0321",
  "Tronco medio del plexo braquial.l": "nervous.model-node-0322",
  "Tronco medio del plexo braquial.r": "nervous.model-node-0323",
  "Tronco superior del plexo braquial.l": "nervous.model-node-0324",
  "Tronco superior del plexo braquial.r": "nervous.model-node-0325",
} as const satisfies Readonly<Record<string, string>>;
