/**
 * Identidades persistentes para el sistema nervioso.
 * Los valores se conservan aunque cambien nombres, orden o índices del GLB.
 * Cubre las 234 entradas indexadas (central + peripheral + senses + plexus coroideo).
 */
export const nervousStableIdByOriginalName = {
  // ========== CENTRAL (encéfalo, cerebelo, diencéfalo, tronco, médula) ==========
  // Cerebelo
  "Ala del lóbulo central.l": "nervous.central-lobule-wing.left",
  "Ala del lóbulo central.r": "nervous.central-lobule-wing.right",
  "Lóbulo central": "nervous.cerebellar-central-lobule",
  "Flocculus.l": "nervous.flocculus.left",
  "Flocculus.r": "nervous.flocculus.right",
  "Nódulo del vermis": "nervous.cerebellar-nodulus",
  "Pedúnculo cerebeloso superior.l": "nervous.superior-cerebellar-peduncle.left",
  "Pedúnculo cerebeloso superior.r": "nervous.superior-cerebellar-peduncle.right",
  "Amígdala del cerebelo.l": "nervous.cerebellar-amygdala.left",
  "Amígdala del cerebelo.r": "nervous.cerebellar-amygdala.right",
  "Lóbulo biventral.l": "nervous.biventral-lobule.left",
  "Lóbulo biventral.r": "nervous.biventral-lobule.right",
  "Lóbulo cuadrangular anterior.l": "nervous.anterior-quadrangular-lobule.left",
  "Lóbulo cuadrangular anterior.r": "nervous.anterior-quadrangular-lobule.right",
  "Lóbulo cuadrangular posterior.l": "nervous.posterior-quadrangular-lobule.left",
  "Lóbulo cuadrangular posterior.r": "nervous.posterior-quadrangular-lobule.right",
  "Lóbulo grácil.l": "nervous.gracile-lobule.left",
  "Lóbulo grácil.r": "nervous.gracile-lobule.right",
  "Lóbulo semilunar inferior.l": "nervous.inferior-semilunar-lobule.left",
  "Lóbulo semilunar inferior.r": "nervous.inferior-semilunar-lobule.right",
  "Lóbulo semilunar superior.l": "nervous.superior-semilunar-lobule.left",
  "Lóbulo semilunar superior.r": "nervous.superior-semilunar-lobule.right",
  "Folio del vermis": "nervous.folium-vermis",
  "Lingula del cerebelo": "nervous.lingula-cerebelli",
  "Culmen": "nervous.culmen",
  "Declive": "nervous.declive",
  "Pirámide del vermis": "nervous.pyramid-vermis",
  "Tubérculo del vermis": "nervous.tuber-vermis",
  "Úvula del vermis": "nervous.uvula-vermis",
  "Tienda del cerebello.l": "nervous.tentorium-cerebelli.left",
  "Tienda del cerebello.r": "nervous.tentorium-cerebelli.right",
  "Tracto espinocerebeloso anterior": "nervous.anterior-spinocerebellar-tract",

  // Diencéfalo y vías visuales
  "Tálamo.l": "nervous.thalamus.left",
  "Tálamo.r": "nervous.thalamus.right",
  "Hipotálamo": "nervous.hypothalamus",
  "Cuerpo geniculado lateral.l": "nervous.lateral-geniculate-body.left",
  "Cuerpo geniculado lateral.r": "nervous.lateral-geniculate-body.right",
  "Cuerpo geniculado medial.l": "nervous.medial-geniculate-body.left",
  "Cuerpo geniculado medial.r": "nervous.medial-geniculate-body.right",
  "Quiasma óptico.l": "nervous.optic-chiasm.left",
  "Quiasma óptico.r": "nervous.optic-chiasm.right",
  "Tracto óptico.l": "nervous.optic-tract.left",
  "Tracto óptico.r": "nervous.optic-tract.right",
  "Tercer ventrículo": "nervous.third-ventricle",

  // Núcleos basales
  "Núcleo caudado.l": "nervous.caudate-nucleus.left",
  "Núcleo caudado.r": "nervous.caudate-nucleus.right",
  "Putamen.l": "nervous.putamen.left",
  "Putamen.r": "nervous.putamen.right",
  "Globo pálido.l": "nervous.globus-pallidus.left",
  "Globo pálido.r": "nervous.globus-pallidus.right",

  // Corteza cerebral y sistema límbico
  "Giro precentral.l": "nervous.precentral-gyrus.left",
  "Giro precentral.r": "nervous.precentral-gyrus.right",
  "Giro poscentral.l": "nervous.postcentral-gyrus.left",
  "Giro poscentral.r": "nervous.postcentral-gyrus.right",
  "Surco central.l": "nervous.central-sulcus.left",
  "Surco central.r": "nervous.central-sulcus.right",
  "Lóbulo parietal superior.l": "nervous.superior-parietal-lobule.left",
  "Lóbulo parietal superior.r": "nervous.superior-parietal-lobule.right",
  "Giro angular.l": "nervous.angular-gyrus.left",
  "Giro angular.r": "nervous.angular-gyrus.right",
  "Giro supramarginal.l": "nervous.supramarginal-gyrus.left",
  "Giro supramarginal.r": "nervous.supramarginal-gyrus.right",
  "Surco calcarino.l": "nervous.calcarine-sulcus.left",
  "Surco calcarino.r": "nervous.calcarine-sulcus.right",
  "Giros temporales transversos.l": "nervous.transverse-temporal-gyri.left",
  "Giros temporales transversos.r": "nervous.transverse-temporal-gyri.right",
  "Hipocampo.l": "nervous.hippocampus.left",
  "Hipocampo.r": "nervous.hippocampus.right",
  "Cuerpo amigdaloide.l": "nervous.amygdaloid-body.left",
  "Cuerpo amigdaloide.r": "nervous.amygdaloid-body.right",

  // Conexiones profundas y sistema ventricular
  "Cuerpo calloso": "nervous.corpus-callosum",
  "Fornix.l": "nervous.fornix.left",
  "Fornix.r": "nervous.fornix.right",
  "Sustancia blanca del telencéfalo.l": "nervous.telencephalic-white-matter.left",
  "Sustancia blanca del telencéfalo.r": "nervous.telencephalic-white-matter.right",
  "Ventrículo lateral.l": "nervous.lateral-ventricle.left",
  "Ventrículo lateral.r": "nervous.lateral-ventricle.right",

  // Tronco encefálico
  "Mesencéfalo.l": "nervous.midbrain.left",
  "Mesencéfalo.r": "nervous.midbrain.right",
  "Puente troncoencefálico.l": "nervous.pons.left",
  "Puente troncoencefálico.r": "nervous.pons.right",
  "Bulbo raquídeo.l": "nervous.medulla-oblongata.left",
  "Bulbo raquídeo.r": "nervous.medulla-oblongata.right",
  "Colículo superior.l": "nervous.superior-colliculus.left",
  "Colículo superior.r": "nervous.superior-colliculus.right",
  "Colículo inferior.l": "nervous.inferior-colliculus.left",
  "Colículo inferior.r": "nervous.inferior-colliculus.right",

  // Médula espinal
  "Sustancia blanca de la médula espinal": "nervous.spinal-white-matter",
  "Cuerno anterior de la médula espinal": "nervous.spinal-anterior-horn",
  "Cuerno posterior de la médula espinal": "nervous.spinal-posterior-horn",
  "Tracto corticoespinal lateral": "nervous.lateral-corticospinal-tract",
  "Tracto espinotalámico lateral": "nervous.lateral-spinothalamic-tract",
  "Fascículo grácil": "nervous.gracile-fasciculus",
  "Fascículo cuneiforme": "nervous.cuneate-fasciculus",

  // Referencias corticales y núcleos adicionales
  "Giro frontal superior.l": "nervous.superior-frontal-gyrus.left",
  "Giro frontal superior.r": "nervous.superior-frontal-gyrus.right",
  "Giro frontal medio.l": "nervous.middle-frontal-gyrus.left",
  "Giro frontal medio.r": "nervous.middle-frontal-gyrus.right",
  "Giros occipitales superiores.l": "nervous.superior-occipital-gyri.left",
  "Giros occipitales superiores.r": "nervous.superior-occipital-gyri.right",
  "Polo occipital.l": "nervous.occipital-pole.left",
  "Polo occipital.r": "nervous.occipital-pole.right",
  "Giro lingual.l": "nervous.lingual-gyrus.left",
  "Giro lingual.r": "nervous.lingual-gyrus.right",
  "Giro temporal medio.l": "nervous.middle-temporal-gyrus.left",
  "Giro temporal medio.r": "nervous.middle-temporal-gyrus.right",
  "Giro temporal inferior.l": "nervous.inferior-temporal-gyrus.left",
  "Giro temporal inferior.r": "nervous.inferior-temporal-gyrus.right",
  "Superior temporal gyrus (Lateral part).l": "nervous.superior-temporal-gyrus-lateral.left",
  "Superior temporal gyrus (Lateral part).r": "nervous.superior-temporal-gyrus-lateral.right",
  "Surco intraparietal.l": "nervous.intraparietal-sulcus.left",
  "Surco intraparietal.r": "nervous.intraparietal-sulcus.right",
  "Cuerpo mamilar.l": "nervous.mammillary-body.left",
  "Cuerpo mamilar.r": "nervous.mammillary-body.right",
  "Núcleo rojo.l": "nervous.red-nucleus.left",
  "Núcleo rojo.r": "nervous.red-nucleus.right",
  "Núcleo del tracto solitario.l": "nervous.solitary-nucleus.left",
  "Núcleo del tracto solitario.r": "nervous.solitary-nucleus.right",

  // Hitos adicionales
  "Precuneus.l": "nervous.precuneus.left",
  "Precuneus.r": "nervous.precuneus.right",
  "Comisura anterior": "nervous.anterior-commissure",
  "Cuarto ventrículo": "nervous.fourth-ventricle",
  "Acueducto del mesencéfalo": "nervous.cerebral-aqueduct",
  "Oliva.l": "nervous.medullary-olive.left",
  "Oliva.r": "nervous.medullary-olive.right",
  "Pirámide del bulbo raquídeo.l": "nervous.medullary-pyramid.left",
  "Pirámide del bulbo raquídeo.r": "nervous.medullary-pyramid.right",
  "Núcleo ambiguo.l": "nervous.nucleus-ambiguus.left",
  "Núcleo ambiguo.r": "nervous.nucleus-ambiguus.right",
  "Núcleos vestibulares.l": "nervous.vestibular-nuclei.left",
  "Núcleos vestibulares.r": "nervous.vestibular-nuclei.right",
  "Núcleo intermediolateral": "nervous.intermediolateral-nucleus",
  "Tracto espinocerebeloso posterior": "nervous.posterior-spinocerebellar-tract",

  // ========== PERIPHERAL (pares craneales, nervios espinales, plexos, autónomo) ==========
  // Pares craneales
  "Nervio olfatorio (I).l": "nervous.olfactory-nerve.left",
  "Nervio olfatorio (I).r": "nervous.olfactory-nerve.right",
  "Nervio óptico (II).l": "nervous.optic-nerve.left",
  "Nervio óptico (II).r": "nervous.optic-nerve.right",
  "Nervio oculomotor (III).l": "nervous.oculomotor-nerve.left",
  "Nervio oculomotor (III).r": "nervous.oculomotor-nerve.right",
  "Nervio troclear (IV).l": "nervous.trochlear-nerve.left",
  "Nervio troclear (IV).r": "nervous.trochlear-nerve.right",
  "Nervio trigémino (V).l": "nervous.trigeminal-nerve.left",
  "Nervio trigémino (V).r": "nervous.trigeminal-nerve.right",
  "Nervio abducens (VI).l": "nervous.abducens-nerve.left",
  "Nervio abducens (VI).r": "nervous.abducens-nerve.right",
  "Nervio facial (VII).l": "nervous.facial-nerve.left",
  "Nervio facial (VII).r": "nervous.facial-nerve.right",
  "Nervio vestibulococlear (VIII).l": "nervous.vestibulocochlear-nerve.left",
  "Nervio vestibulococlear (VIII).r": "nervous.vestibulocochlear-nerve.right",
  "Nervio glosofaríngeo (IX).l": "nervous.glossopharyngeal-nerve.left",
  "Nervio glosofaríngeo (IX).r": "nervous.glossopharyngeal-nerve.right",
  "Nervio vago (X).l": "nervous.vagus-nerve.left",
  "Nervio vago (X).r": "nervous.vagus-nerve.right",
  "Nervio accesorio (XI).l": "nervous.accessory-nerve.left",
  "Nervio accesorio (XI).r": "nervous.accessory-nerve.right",
  "Nervio hipogloso (XII).l": "nervous.hypoglossal-nerve.left",
  "Nervio hipogloso (XII).r": "nervous.hypoglossal-nerve.right",

  // Nervios espinales, plexo braquial y autónomo
  "Raíz anterior del nervio espinal.l": "nervous.spinal-ventral-root.left",
  "Raíz anterior del nervio espinal.r": "nervous.spinal-ventral-root.right",
  "Raíz posterior del nervio espinal.l": "nervous.spinal-dorsal-root.left",
  "Raíz posterior del nervio espinal.r": "nervous.spinal-dorsal-root.right",
  "Ganglio espinal.l": "nervous.spinal-ganglion.left",
  "Ganglio espinal.r": "nervous.spinal-ganglion.right",
  "Tronco simpático.l": "nervous.sympathetic-trunk.left",
  "Tronco simpático.r": "nervous.sympathetic-trunk.right",
  "Raíces del plexo braquial.l": "nervous.brachial-plexus-roots.left",
  "Raíces del plexo braquial.r": "nervous.brachial-plexus-roots.right",
  "Fascículo posterior del plexo braquial.l": "nervous.brachial-plexus-posterior-cord.left",
  "Fascículo posterior del plexo braquial.r": "nervous.brachial-plexus-posterior-cord.right",
  "Nervios intercostales.l": "nervous.intercostal-nerves.left",
  "Nervios intercostales.r": "nervous.intercostal-nerves.right",
  "Cauda equina": "nervous.cauda-equina",

  // Ramas terminales miembro superior
  "Nervio mediano.l": "nervous.median-nerve.left",
  "Nervio mediano.r": "nervous.median-nerve.right",
  "Nervio ulnar.l": "nervous.ulnar-nerve.left",
  "Nervio ulnar.r": "nervous.ulnar-nerve.right",
  "Nervio radial.l": "nervous.radial-nerve.left",
  "Nervio radial.r": "nervous.radial-nerve.right",
  "Nervio musculocutáneo.l": "nervous.musculocutaneous-nerve.left",
  "Nervio musculocutáneo.r": "nervous.musculocutaneous-nerve.right",
  "Nervio axilar.l": "nervous.axillary-nerve.left",
  "Nervio axilar.r": "nervous.axillary-nerve.right",
  "Nervio torácico largo.l": "nervous.long-thoracic-nerve.left",
  "Nervio torácico largo.r": "nervous.long-thoracic-nerve.right",
  "Nervio supraescapular.l": "nervous.suprascapular-nerve.left",
  "Nervio supraescapular.r": "nervous.suprascapular-nerve.right",

  // Miembro inferior y periné
  "Nervio femoral.l": "nervous.femoral-nerve.left",
  "Nervio femoral.r": "nervous.femoral-nerve.right",
  "Nervio obturador.l": "nervous.obturator-nerve.left",
  "Nervio obturador.r": "nervous.obturator-nerve.right",
  "Nervio ciático.l": "nervous.sciatic-nerve.left",
  "Nervio ciático.r": "nervous.sciatic-nerve.right",
  "Nervio tibial.l": "nervous.tibial-nerve.left",
  "Nervio tibial.r": "nervous.tibial-nerve.right",
  "Nervio fibular común.l": "nervous.common-fibular-nerve.left",
  "Nervio fibular común.r": "nervous.common-fibular-nerve.right",
  "Nervio fibular profundo.l": "nervous.deep-fibular-nerve.left",
  "Nervio fibular profundo.r": "nervous.deep-fibular-nerve.right",
  "Nervio fibular superficial.l": "nervous.superficial-fibular-nerve.left",
  "Nervio fibular superficial.r": "nervous.superficial-fibular-nerve.right",
  "Nervio safeno.l": "nervous.saphenous-nerve.left",
  "Nervio safeno.r": "nervous.saphenous-nerve.right",
  "Nervio sural.l": "nervous.sural-nerve.left",
  "Nervio sural.r": "nervous.sural-nerve.right",
  "Nervio pudendo.l": "nervous.pudendal-nerve.left",
  "Nervio pudendo.r": "nervous.pudendal-nerve.right",

  // Vías autónomas y ramas clínicas
  "Nervios simpáticos.l": "nervous.sympathetic-nerves.left",
  "Nervios simpáticos.r": "nervous.sympathetic-nerves.right",
  "Ganglios del tronco simpático.l": "nervous.sympathetic-chain-ganglia.left",
  "Ganglios del tronco simpático.r": "nervous.sympathetic-chain-ganglia.right",
  "Nervio oftálmico.l": "nervous.ophthalmic-nerve.left",
  "Nervio oftálmico.r": "nervous.ophthalmic-nerve.right",
  "Nervio maxilar.l": "nervous.maxillary-nerve.left",
  "Nervio maxilar.r": "nervous.maxillary-nerve.right",
  "Nervio lingual.l": "nervous.lingual-nerve.left",
  "Nervio lingual.r": "nervous.lingual-nerve.right",
  "Nervio genitofemoral.l": "nervous.genitofemoral-nerve.left",
  "Nervio genitofemoral.r": "nervous.genitofemoral-nerve.right",
  "Nervio cutáneo femoral lateral.l": "nervous.lateral-femoral-cutaneous-nerve.left",
  "Nervio cutáneo femoral lateral.r": "nervous.lateral-femoral-cutaneous-nerve.right",
  "Nervio glúteo superior.l": "nervous.superior-gluteal-nerve.left",
  "Nervio glúteo superior.r": "nervous.superior-gluteal-nerve.right",
  "Nervio plantar medial.l": "nervous.medial-plantar-nerve.left",
  "Nervio plantar medial.r": "nervous.medial-plantar-nerve.right",
  "Nervio plantar lateral.l": "nervous.lateral-plantar-nerve.left",
  "Nervio plantar lateral.r": "nervous.lateral-plantar-nerve.right",

  // ========== SENSES (órganos de los sentidos) ==========
  "Córnea.l": "nervous.cornea.left",
  "Córnea.r": "nervous.cornea.right",
  "Esclera.l": "nervous.sclera.left",
  "Esclera.r": "nervous.sclera.right",
  "Iris.l": "nervous.iris.left",
  "Iris.r": "nervous.iris.right",
  "Lente.l": "nervous.lens.left",
  "Lente.r": "nervous.lens.right",
  "Retina.l": "nervous.retina.left",
  "Retina.r": "nervous.retina.right",
  "Cuerpo vitreo.l": "nervous.vitreous-body.left",
  "Cuerpo vitreo.r": "nervous.vitreous-body.right",
  "Glándula lagrimal.l": "nervous.lacrimal-gland.left",
  "Glándula lagrimal.r": "nervous.lacrimal-gland.right",
  "Membrana timpánica.l": "nervous.tympanic-membrane.left",
  "Membrana timpánica.r": "nervous.tympanic-membrane.right",
  "Cóclea.l": "nervous.cochlea.left",
  "Cóclea.r": "nervous.cochlea.right",
  "Vestíbulo.l": "nervous.vestibule.left",
  "Vestíbulo.r": "nervous.vestibule.right",
  "Tubo auditivo.l": "nervous.auditory-tube.left",
  "Tubo auditivo.r": "nervous.auditory-tube.right",
  "Cámara anterior del globo ocular.l": "nervous.anterior-eye-chamber.left",
  "Cámara anterior del globo ocular.r": "nervous.anterior-eye-chamber.right",
  "Fibras zonulares.l": "nervous.zonular-fibers.left",
  "Fibras zonulares.r": "nervous.zonular-fibers.right",
  "Saco lagrimal.l": "nervous.lacrimal-sac.left",
  "Saco lagrimal.r": "nervous.lacrimal-sac.right",
  "Canal nasolagrimal.l": "nervous.nasolacrimal-canal.left",
  "Canal nasolagrimal.r": "nervous.nasolacrimal-canal.right",

  // ========== ADICIONALES (no están en fichas educativas pero sí en catálogo) ==========
  "Plexo coroideo.l": "nervous.choroid-plexus.left",
  "Plexo coroideo.r": "nervous.choroid-plexus.right",
} as const satisfies Readonly<Record<string, string>>;