/**
 * Identidades persistentes para el sistema esquelético.
 * Los valores se conservan aunque cambien nombres, orden o índices del GLB.
 * Generado para cubrir las 277 entradas del skeletalModelCatalog.
 */
export const skeletalStableIdByOriginalName = {
  // Extremidad superior - mano (metacarpianos y falanges)
  "Primer hueso metacarpiano.l": "skeletal.metacarpals.metacarpal-1.left",
  "Primer hueso metacarpiano.r": "skeletal.metacarpals.metacarpal-1.right",
  "Segundo hueso metacarpiano.l": "skeletal.metacarpals.metacarpal-2.left",
  "Segundo hueso metacarpiano.r": "skeletal.metacarpals.metacarpal-2.right",
  "Tercer hueso metacarpiano.l": "skeletal.metacarpals.metacarpal-3.left",
  "Tercer hueso metacarpiano.r": "skeletal.metacarpals.metacarpal-3.right",
  "Cuarto hueso metacarpiano.l": "skeletal.metacarpals.metacarpal-4.left",
  "Cuarto hueso metacarpiano.r": "skeletal.metacarpals.metacarpal-4.right",
  "Quinto hueso metacarpiano.l": "skeletal.metacarpals.metacarpal-5.left",
  "Quinto hueso metacarpiano.r": "skeletal.metacarpals.metacarpal-5.right",

  "Falange proximal del primer dedo de la mano.l": "skeletal.hand-proximal-phalanges.phalanx-proximal-1.left",
  "Falange proximal del primer dedo de la mano.r": "skeletal.hand-proximal-phalanges.phalanx-proximal-1.right",
  "Falange proximal del segundo dedo de la mano.l": "skeletal.hand-proximal-phalanges.phalanx-proximal-2.left",
  "Falange proximal del segundo dedo de la mano.r": "skeletal.hand-proximal-phalanges.phalanx-proximal-2.right",
  "Falange proximal del tercer dedo de la mano.l": "skeletal.hand-proximal-phalanges.phalanx-proximal-3.left",
  "Falange proximal del tercer dedo de la mano.r": "skeletal.hand-proximal-phalanges.phalanx-proximal-3.right",
  "Falange proximal del cuarto dedo de la mano.l": "skeletal.hand-proximal-phalanges.phalanx-proximal-4.left",
  "Falange proximal del cuarto dedo de la mano.r": "skeletal.hand-proximal-phalanges.phalanx-proximal-4.right",
  "Falange proximal del quinto dedo de la mano.l": "skeletal.hand-proximal-phalanges.phalanx-proximal-5.left",
  "Falange proximal del quinto dedo de la mano.r": "skeletal.hand-proximal-phalanges.phalanx-proximal-5.right",

  "Falange media del segundo dedo de la mano.l": "skeletal.hand-middle-phalanges.phalanx-middle-2.left",
  "Falange media del segundo dedo de la mano.r": "skeletal.hand-middle-phalanges.phalanx-middle-2.right",
  "Falange media del tercer dedo de la mano.l": "skeletal.hand-middle-phalanges.phalanx-middle-3.left",
  "Falange media del tercer dedo de la mano.r": "skeletal.hand-middle-phalanges.phalanx-middle-3.right",
  "Falange media del cuarto dedo de la mano.l": "skeletal.hand-middle-phalanges.phalanx-middle-4.left",
  "Falange media del cuarto dedo de la mano.r": "skeletal.hand-middle-phalanges.phalanx-middle-4.right",
  "Falange media del quinto dedo de la mano.l": "skeletal.hand-middle-phalanges.phalanx-middle-5.left",
  "Falange media del quinto dedo de la mano.r": "skeletal.hand-middle-phalanges.phalanx-middle-5.right",

  "Falange distal del primer dedo de la mano.l": "skeletal.hand-distal-phalanges.phalanx-distal-1.left",
  "Falange distal del primer dedo de la mano.r": "skeletal.hand-distal-phalanges.phalanx-distal-1.right",
  "Falange distal del segundo dedo de la mano.l": "skeletal.hand-distal-phalanges.phalanx-distal-2.left",
  "Falange distal del segundo dedo de la mano.r": "skeletal.hand-distal-phalanges.phalanx-distal-2.right",
  "Falange distal del tercer dedo de la mano.l": "skeletal.hand-distal-phalanges.phalanx-distal-3.left",
  "Falange distal del tercer dedo de la mano.r": "skeletal.hand-distal-phalanges.phalanx-distal-3.right",
  "Falange distal del cuarto dedo de la mano.l": "skeletal.hand-distal-phalanges.phalanx-distal-4.left",
  "Falange distal del cuarto dedo de la mano.r": "skeletal.hand-distal-phalanges.phalanx-distal-4.right",
  "Falange distal del quinto dedo de la mano.l": "skeletal.hand-distal-phalanges.phalanx-distal-5.left",
  "Falange distal del quinto dedo de la mano.r": "skeletal.hand-distal-phalanges.phalanx-distal-5.right",

  // Carpo
  "Hueso escafoides.l": "skeletal.scaphoid.left",
  "Hueso escafoides.r": "skeletal.scaphoid.right",
  "Hueso lunado.l": "skeletal.lunate.left",
  "Hueso lunado.r": "skeletal.lunate.right",
  "Hueso triquetral.l": "skeletal.triquetrum.left",
  "Hueso triquetral.r": "skeletal.triquetrum.right",
  "Hueso pisiforme.l": "skeletal.pisiform.left",
  "Hueso pisiforme.r": "skeletal.pisiform.right",
  "Hueso trapecio.l": "skeletal.trapezium.left",
  "Hueso trapecio.r": "skeletal.trapezium.right",
  "Hueso trapezoide.l": "skeletal.trapezoid.left",
  "Hueso trapezoide.r": "skeletal.trapezoid.right",
  "Hueso capitado.l": "skeletal.capitate.left",
  "Hueso capitado.r": "skeletal.capitate.right",
  "Hueso hamatal.l": "skeletal.hamate.left",
  "Hueso hamatal.r": "skeletal.hamate.right",

  // Miembro superior proximal
  "Clavícula.l": "skeletal.clavicle.left",
  "Clavícula.r": "skeletal.clavicle.right",
  "Escápula.l": "skeletal.scapula.left",
  "Escápula.r": "skeletal.scapula.right",
  "Húmero.l": "skeletal.humerus.left",
  "Húmero.r": "skeletal.humerus.right",
  "Radio.l": "skeletal.radius.left",
  "Radio.r": "skeletal.radius.right",
  "Ulna.l": "skeletal.ulna.left",
  "Ulna.r": "skeletal.ulna.right",

  // Extremidad inferior - pie (metatarsianos y falanges)
  "Primer hueso metatarsiano.l": "skeletal.metatarsals.metatarsal-1.left",
  "Primer hueso metatarsiano.r": "skeletal.metatarsals.metatarsal-1.right",
  "Segundo hueso metatarsiano.l": "skeletal.metatarsals.metatarsal-2.left",
  "Segundo hueso metatarsiano.r": "skeletal.metatarsals.metatarsal-2.right",
  "Tercer hueso metatarsiano.l": "skeletal.metatarsals.metatarsal-3.left",
  "Tercer hueso metatarsiano.r": "skeletal.metatarsals.metatarsal-3.right",
  "Cuarto hueso metatarsiano.l": "skeletal.metatarsals.metatarsal-4.left",
  "Cuarto hueso metatarsiano.r": "skeletal.metatarsals.metatarsal-4.right",
  "Quinto hueso metatarsiano.l": "skeletal.metatarsals.metatarsal-5.left",
  "Quinto hueso metatarsiano.r": "skeletal.metatarsals.metatarsal-5.right",

  "Falange proximal del primer dedo del pie.l": "skeletal.foot-proximal-phalanges.phalanx-proximal-1.left",
  "Falange proximal del primer dedo del pie.r": "skeletal.foot-proximal-phalanges.phalanx-proximal-1.right",
  "Falange proximal del segundo dedo del pie.l": "skeletal.foot-proximal-phalanges.phalanx-proximal-2.left",
  "Falange proximal del segundo dedo del pie.r": "skeletal.foot-proximal-phalanges.phalanx-proximal-2.right",
  "Falange proximal del tercer dedo del pie.l": "skeletal.foot-proximal-phalanges.phalanx-proximal-3.left",
  "Falange proximal del tercer dedo del pie.r": "skeletal.foot-proximal-phalanges.phalanx-proximal-3.right",
  "Falange proximal del cuarto dedo del pie.l": "skeletal.foot-proximal-phalanges.phalanx-proximal-4.left",
  "Falange proximal del cuarto dedo del pie.r": "skeletal.foot-proximal-phalanges.phalanx-proximal-4.right",
  "Falange proximal del quinto dedo del pie.l": "skeletal.foot-proximal-phalanges.phalanx-proximal-5.left",
  "Falange proximal del quinto dedo del pie.r": "skeletal.foot-proximal-phalanges.phalanx-proximal-5.right",

  "Falange media del segundo dedo del pie.l": "skeletal.foot-middle-phalanges.phalanx-middle-2.left",
  "Falange media del segundo dedo del pie.r": "skeletal.foot-middle-phalanges.phalanx-middle-2.right",
  "Falange media del tercer dedo del pie.l": "skeletal.foot-middle-phalanges.phalanx-middle-3.left",
  "Falange media del tercer dedo del pie.r": "skeletal.foot-middle-phalanges.phalanx-middle-3.right",
  "Falange media del cuarto dedo del pie.l": "skeletal.foot-middle-phalanges.phalanx-middle-4.left",
  "Falange media del cuarto dedo del pie.r": "skeletal.foot-middle-phalanges.phalanx-middle-4.right",
  "Falange media del quinto dedo del pie.l": "skeletal.foot-middle-phalanges.phalanx-middle-5.left",
  "Falange media del quinto dedo del pie.r": "skeletal.foot-middle-phalanges.phalanx-middle-5.right",

  "Falange distal del primer dedo del pie.l": "skeletal.foot-distal-phalanges.phalanx-distal-1.left",
  "Falange distal del primer dedo del pie.r": "skeletal.foot-distal-phalanges.phalanx-distal-1.right",
  "Falange distal del segundo dedo del pie.l": "skeletal.foot-distal-phalanges.phalanx-distal-2.left",
  "Falange distal del segundo dedo del pie.r": "skeletal.foot-distal-phalanges.phalanx-distal-2.right",
  "Falange distal del tercer dedo del pie.l": "skeletal.foot-distal-phalanges.phalanx-distal-3.left",
  "Falange distal del tercer dedo del pie.r": "skeletal.foot-distal-phalanges.phalanx-distal-3.right",
  "Falange distal del cuarto dedo del pie.l": "skeletal.foot-distal-phalanges.phalanx-distal-4.left",
  "Falange distal del cuarto dedo del pie.r": "skeletal.foot-distal-phalanges.phalanx-distal-4.right",
  "Falange distal del quinto dedo del pie.l": "skeletal.foot-distal-phalanges.phalanx-distal-5.left",
  "Falange distal del quinto dedo del pie.r": "skeletal.foot-distal-phalanges.phalanx-distal-5.right",

  // Tarso
  "Hueso Talo.l": "skeletal.talus.left",
  "Hueso Talo.r": "skeletal.talus.right",
  "Calcáneo.l": "skeletal.calcaneus.left",
  "Calcáneo.r": "skeletal.calcaneus.right",
  "Hueso navicular.l": "skeletal.navicular.left",
  "Hueso navicular.r": "skeletal.navicular.right",
  "Hueso cuboide.l": "skeletal.cuboid.left",
  "Hueso cuboide.r": "skeletal.cuboid.right",
  "Hueso cuneiforme medial.l": "skeletal.medial-cuneiform.left",
  "Hueso cuneiforme medial.r": "skeletal.medial-cuneiform.right",
  "Hueso cuneiforme intermedio.l": "skeletal.intermediate-cuneiform.left",
  "Hueso cuneiforme intermedio.r": "skeletal.intermediate-cuneiform.right",
  "Hueso cuneiforme lateral.l": "skeletal.lateral-cuneiform.left",
  "Hueso cuneiforme lateral.r": "skeletal.lateral-cuneiform.right",

  // Miembro inferior proximal
  "Hueso coxal.l": "skeletal.hip-bone.left",
  "Hueso coxal.r": "skeletal.hip-bone.right",
  "Hueso Fémur.l": "skeletal.femur.left",
  "Hueso Fémur.r": "skeletal.femur.right",
  "Patela.l": "skeletal.patella.left",
  "Patela.r": "skeletal.patella.right",
  "Tibia.l": "skeletal.tibia.left",
  "Tibia.r": "skeletal.tibia.right",
  "Fíbula.l": "skeletal.fibula.left",
  "Fíbula.r": "skeletal.fibula.right",
  "Huesos sesamoideos del pie.l": "skeletal.foot-sesamoids.left",
  "Huesos sesamoideos del pie.r": "skeletal.foot-sesamoids.right",

  // Cráneo - Neurocráneo
  "Hueso frontal": "skeletal.frontal-bone",
  "Hueso parietal.l": "skeletal.parietal-bone.left",
  "Hueso parietal.r": "skeletal.parietal-bone.right",
  "Hueso temporal.l": "skeletal.temporal-bone.left",
  "Hueso temporal.r": "skeletal.temporal-bone.right",
  "Hueso occipital": "skeletal.occipital-bone",
  "Hueso esfenoide": "skeletal.sphenoid-bone",
  "Hueso etmoides": "skeletal.ethmoid-bone",

  // Cráneo - Viscerocráneo
  "Hueso maxilar.l": "skeletal.maxilla.left",
  "Hueso maxilar.r": "skeletal.maxilla.right",
  "Mandíbula": "skeletal.mandible",
  "Hueso cigomático.l": "skeletal.zygomatic-bone.left",
  "Hueso cigomático.r": "skeletal.zygomatic-bone.right",
  "Hueso nasal.l": "skeletal.nasal-bone.left",
  "Hueso nasal.r": "skeletal.nasal-bone.right",
  "Hueso lagrimal.l": "skeletal.lacrimal-bone.left",
  "Hueso lagrimal.r": "skeletal.lacrimal-bone.right",
  "Hueso palatino.l": "skeletal.palatine-bone.left",
  "Hueso palatino.r": "skeletal.palatine-bone.right",
  "Concha nasal inferior.l": "skeletal.inferior-nasal-concha.left",
  "Concha nasal inferior.r": "skeletal.inferior-nasal-concha.right",
  "Vómer": "skeletal.vomer",

  // Oído medio e hioides
  "Malleus.l": "skeletal.malleus.left",
  "Malleus.r": "skeletal.malleus.right",
  "Incus.l": "skeletal.incus.left",
  "Incus.r": "skeletal.incus.right",
  "Estapedio.l": "skeletal.stapes.left",
  "Estapedio.r": "skeletal.stapes.right",
  "Hueso hioides": "skeletal.hyoid-bone",

  // Columna vertebral
  "Atlas (C1)": "skeletal.atlas",
  "Axis (C2)": "skeletal.axis",
  "Vértebra C3": "skeletal.cervical-vertebrae-c3-c7.vertebra-c3",
  "Vértebra C4": "skeletal.cervical-vertebrae-c3-c7.vertebra-c4",
  "Vértebra C5": "skeletal.cervical-vertebrae-c3-c7.vertebra-c5",
  "Vértebra C6": "skeletal.cervical-vertebrae-c3-c7.vertebra-c6",
  "Vértebra C7": "skeletal.cervical-vertebrae-c3-c7.vertebra-c7",
  "Vértebra T1": "skeletal.thoracic-vertebrae.vertebra-t1",
  "Vértebra T2": "skeletal.thoracic-vertebrae.vertebra-t2",
  "Vértebra T3": "skeletal.thoracic-vertebrae.vertebra-t3",
  "Vértebra T4": "skeletal.thoracic-vertebrae.vertebra-t4",
  "Vértebra T5": "skeletal.thoracic-vertebrae.vertebra-t5",
  "Vértebra T6": "skeletal.thoracic-vertebrae.vertebra-t6",
  "Vértebra T7": "skeletal.thoracic-vertebrae.vertebra-t7",
  "Vértebra T8": "skeletal.thoracic-vertebrae.vertebra-t8",
  "Vértebra T9": "skeletal.thoracic-vertebrae.vertebra-t9",
  "Vértebra T10": "skeletal.thoracic-vertebrae.vertebra-t10",
  "Vértebra T11": "skeletal.thoracic-vertebrae.vertebra-t11",
  "Vértebra T12": "skeletal.thoracic-vertebrae.vertebra-t12",
  "Vértebra L1": "skeletal.lumbar-vertebrae.vertebra-l1",
  "Vértebra L2": "skeletal.lumbar-vertebrae.vertebra-l2",
  "Vértebra L3": "skeletal.lumbar-vertebrae.vertebra-l3",
  "Vértebra L4": "skeletal.lumbar-vertebrae.vertebra-l4",
  "Vértebra L5": "skeletal.lumbar-vertebrae.vertebra-l5",
  "Hueso sacro": "skeletal.sacrum",
  "Cóccix": "skeletal.coccyx",

  // Caja torácica - Costillas
  "Primera costilla.l": "skeletal.first-rib.left",
  "Primera costilla.r": "skeletal.first-rib.right",
  "Segunda costilla.l": "skeletal.ribs-2-10.rib-2.left",
  "Segunda costilla.r": "skeletal.ribs-2-10.rib-2.right",
  "Tercera costilla.l": "skeletal.ribs-2-10.rib-3.left",
  "Tercera costilla.r": "skeletal.ribs-2-10.rib-3.right",
  "Cuarta costilla.l": "skeletal.ribs-2-10.rib-4.left",
  "Cuarta costilla.r": "skeletal.ribs-2-10.rib-4.right",
  "Quinta costilla.l": "skeletal.ribs-2-10.rib-5.left",
  "Quinta costilla.r": "skeletal.ribs-2-10.rib-5.right",
  "Sexta costilla.l": "skeletal.ribs-2-10.rib-6.left",
  "Sexta costilla.r": "skeletal.ribs-2-10.rib-6.right",
  "Séptima costilla.l": "skeletal.ribs-2-10.rib-7.left",
  "Séptima costilla.r": "skeletal.ribs-2-10.rib-7.right",
  "Octava costilla.l": "skeletal.ribs-2-10.rib-8.left",
  "Octava costilla.r": "skeletal.ribs-2-10.rib-8.right",
  "Novena costilla.l": "skeletal.ribs-2-10.rib-9.left",
  "Novena costilla.r": "skeletal.ribs-2-10.rib-9.right",
  "Décima costilla.l": "skeletal.ribs-2-10.rib-10.left",
  "Décima costilla.r": "skeletal.ribs-2-10.rib-10.right",
  "Undécima costilla.l": "skeletal.floating-ribs.rib-11.left",
  "Undécima costilla.r": "skeletal.floating-ribs.rib-11.right",
  "Duodécima costilla.l": "skeletal.floating-ribs.rib-12.left",
  "Duodécima costilla.r": "skeletal.floating-ribs.rib-12.right",

  // Cartílagos costales
  "Cartílago costal de la primera costilla.l": "skeletal.costal-cartilages.costal-cartilage-1.left",
  "Cartílago costal de la primera costilla.r": "skeletal.costal-cartilages.costal-cartilage-1.right",
  "Cartílago costal de la segunda costilla.l": "skeletal.costal-cartilages.costal-cartilage-2.left",
  "Cartílago costal de la segunda costilla.r": "skeletal.costal-cartilages.costal-cartilage-2.right",
  "Cartílago costal de la tercera costilla.l": "skeletal.costal-cartilages.costal-cartilage-3.left",
  "Cartílago costal de la tercera costilla.r": "skeletal.costal-cartilages.costal-cartilage-3.right",
  "Cartílago costal de la cuarta costilla.l": "skeletal.costal-cartilages.costal-cartilage-4.left",
  "Cartílago costal de la cuarta costilla.r": "skeletal.costal-cartilages.costal-cartilage-4.right",
  "Cartílago costal de la quinta costilla.l": "skeletal.costal-cartilages.costal-cartilage-5.left",
  "Cartílago costal de la quinta costilla.r": "skeletal.costal-cartilages.costal-cartilage-5.right",
  "Cartílago costal de la sexta costilla.l": "skeletal.costal-cartilages.costal-cartilage-6.left",
  "Cartílago costal de la sexta costilla.r": "skeletal.costal-cartilages.costal-cartilage-6.right",
  "Cartílago costal de la séptima costilla.l": "skeletal.costal-cartilages.costal-cartilage-7.left",
  "Cartílago costal de la séptima costilla.r": "skeletal.costal-cartilages.costal-cartilage-7.right",
  "Cartílago costal de la octava costilla.l": "skeletal.costal-cartilages.costal-cartilage-8.left",
  "Cartílago costal de la octava costilla.r": "skeletal.costal-cartilages.costal-cartilage-8.right",
  "Cartílago costal de la novena costilla.l": "skeletal.costal-cartilages.costal-cartilage-9.left",
  "Cartílago costal de la novena costilla.r": "skeletal.costal-cartilages.costal-cartilage-9.right",
  "Cartílago costal de la décima costilla.l": "skeletal.costal-cartilages.costal-cartilage-10.left",
  "Cartílago costal de la décima costilla.r": "skeletal.costal-cartilages.costal-cartilage-10.right",

  // Esternón
  "Manubrio del esternón": "skeletal.sternum.manubrium",
  "Cuerpo del esternón": "skeletal.sternum.body",
  "Proceso xifoides": "skeletal.sternum.xiphoid-process",

  // Dientes
  "Diente incisivo inferolateral.l": "skeletal.incisor-teeth.incisor-inferolateral.lower.left",
  "Diente incisivo inferolateral.r": "skeletal.incisor-teeth.incisor-inferolateral.lower.right",
  "Diente incisivo inferomedial.l": "skeletal.incisor-teeth.incisor-inferomedial.lower.left",
  "Diente incisivo inferomedial.r": "skeletal.incisor-teeth.incisor-inferomedial.lower.right",
  "Diente incisivo superolateral.l": "skeletal.incisor-teeth.incisor-superolateral.upper.left",
  "Diente incisivo superolateral.r": "skeletal.incisor-teeth.incisor-superolateral.upper.right",
  "Diente incisivo superomedial.l": "skeletal.incisor-teeth.incisor-superomedial.upper.left",
  "Diente incisivo superomedial.r": "skeletal.incisor-teeth.incisor-superomedial.upper.right",
  "Diente canino inferior.l": "skeletal.canine-teeth.canine.lower.left",
  "Diente canino inferior.r": "skeletal.canine-teeth.canine.lower.right",
  "Diente canino superior.l": "skeletal.canine-teeth.canine.upper.left",
  "Diente canino superior.r": "skeletal.canine-teeth.canine.upper.right",
  "Diente primer premolar inferior.l": "skeletal.premolar-teeth.premolar-1.lower.left",
  "Diente primer premolar inferior.r": "skeletal.premolar-teeth.premolar-1.lower.right",
  "Diente primer premolar superior.l": "skeletal.premolar-teeth.premolar-1.upper.left",
  "Diente primer premolar superior.r": "skeletal.premolar-teeth.premolar-1.upper.right",
  "Diente segundo premolar inferior.l": "skeletal.premolar-teeth.premolar-2.lower.left",
  "Diente segundo premolar inferior.r": "skeletal.premolar-teeth.premolar-2.lower.right",
  "Diente segundo premolar superior.l": "skeletal.premolar-teeth.premolar-2.upper.left",
  "Diente segundo premolar superior.r": "skeletal.premolar-teeth.premolar-2.upper.right",
  "Diente primer molar inferior.l": "skeletal.molar-teeth.molar-1.lower.left",
  "Diente primer molar inferior.r": "skeletal.molar-teeth.molar-1.lower.right",
  "Diente primer molar superior.l": "skeletal.molar-teeth.molar-1.upper.left",
  "Diente primer molar superior.r": "skeletal.molar-teeth.molar-1.upper.right",
  "Diente segundo molar inferior.l": "skeletal.molar-teeth.molar-2.lower.left",
  "Diente segundo molar inferior.r": "skeletal.molar-teeth.molar-2.lower.right",
  "Diente segundo molar superior.l": "skeletal.molar-teeth.molar-2.upper.left",
  "Diente segundo molar superior.r": "skeletal.molar-teeth.molar-2.upper.right",

  // Laringe y nariz (cartílagos)
  "Cartílago aritenoides.l": "skeletal.arytenoid-cartilage.left",
  "Cartílago aritenoides.r": "skeletal.arytenoid-cartilage.right",
  "Cartílago corniculado.l": "skeletal.corniculate-cartilage.left",
  "Cartílago corniculado.r": "skeletal.corniculate-cartilage.right",
  "Cartílago cricoides": "skeletal.cricoid-cartilage",
  "Cartílago tiroideo": "skeletal.thyroid-cartilage",
  "Cartílago alar mayor.l": "skeletal.major-alar-cartilage.left",
  "Cartílago alar mayor.r": "skeletal.major-alar-cartilage.right",
  "Cartílago del septo nasal": "skeletal.nasal-septal-cartilage",
  "Proceso lateral del cartílago septal nasal.l": "skeletal.lateral-nasal-cartilage.left",
  "Proceso lateral del cartílago septal nasal.r": "skeletal.lateral-nasal-cartilage.right",

  // Senos paranasales y celdillas etmoidales
  "Seno del hueso esfenoidal": "skeletal.sphenoidal-sinus",
  "Células óseas etmoidales etmoidales anteriores.l": "skeletal.anterior-ethmoidal-air-cells.left",
  "Células óseas etmoidales etmoidales anteriores.r": "skeletal.anterior-ethmoidal-air-cells.right",
  "Células óseas etmoidales etmoidales medias.l": "skeletal.middle-ethmoidal-air-cells.left",
  "Células óseas etmoidales etmoidales medias.r": "skeletal.middle-ethmoidal-air-cells.right",
  "Células óseas etmoidales etmoidales posteriores.l": "skeletal.posterior-ethmoidal-air-cells.left",
  "Células óseas etmoidales etmoidales posteriores.r": "skeletal.posterior-ethmoidal-air-cells.right",
  "Seno del hueso frontal": "skeletal.frontal-sinus",
} as const satisfies Readonly<Record<string, string>>;